### ISSUE TITLE
📱🔧 React Native

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#10]
# Current Status

- ### Codebase in progress:<br />[github.com/claytonschneider/realworld-react-native](https://github.com/claytonschneider/realworld-react-native)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/react-native](https://gitter.im/realworld-dev/react-native)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

Anyone out there interested in this? Many folks have been asking for a RealWorld React Native codebase. We haven't created any RealWorld based mobile apps (yet), so this would potentially be the first one :)

**Comment by claytonschneider** [comment]
I got it

**Comment by EricSimons** [comment]
Awesome! Since we don't have any mobile versions (yet), you'll actually be creating *the* standard experience for all the future RealWorld mobile apps 🙌

**Comment by claytonschneider** [comment]
@EricSimons Would you be able to help make some app icons for this using the original RealWorld image files? I've used https://makeappicon.com/ before for this -- free and it works pretty well.

**Comment by EricSimons** [comment]
@claytonschneider I'm on it. Will also put those assets in the starter kit once they're ready 👍

**Comment by akshatgoel** [comment]
@claytonschneider I will be happy to work on React native implementation. Need a helping hand?

**Comment by EricSimons** [comment]
@claytonschneider as promised, icons have been uploaded! You can find the link to them in our new [mobile specs](https://github.com/gothinkster/realworld/tree/master/spec#mobile-specs) section  🎉

**Comment by EricSimons** [comment]
Just set up [**the Gitter chatroom**](https://gitter.im/realworld-dev/react-native) for this! Lets do collaborator coordination in there 👍

cc/ @claytonschneider @akshatgoel

**Comment by wilfredonoyola** [comment]
What is the progress for this? Thanks!

**Comment by cylim** [comment]
I am willing to take over the task. :)

I had created a [react-native repo](https://github.com/cylim/realworld-rn) which copied the redux and http code from [react redux real world example app](https://github.com/gothinkster/react-redux-realworld-example-app). It successfully retrieved tags, so I would expect it to be working fine.

What I am going to do
1. Wireframes for the Mobile App, get approval from the community;
2. React Navigation to replace the react-router;
3. implement the UI.

**Comment by cylim** [comment]
<img width="1134" alt="example" src="https://user-images.githubusercontent.com/5622951/43431000-65147c56-949e-11e8-8c88-6007d5c86b27.png">

Is this two screen okay?

**Comment by wilfredonoyola** [comment]
Hi @cylim , Do you have a progress about this?

**Comment by cylim** [comment]
I had created two screens component and stopped.

Even though React Native can use React Redux store, the React app example from RealWorld is using page-specific redux state. To create good practices React Native app, the redux have to rewrite.

I didn't receive any messages on Gitter and Github Issues; it seems like the community is inactive, that's why I stopped.

**Comment by EvanBacon** [comment]
I have some full apps here, feel free to use:
https://github.com/EvanBacon/Expo-Crossy-Road
https://github.com/EvanBacon/apple-notes
https://github.com/EvanBacon/Instagram
https://github.com/EvanBacon/Expo-Pillar-Valley

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
