### ISSUE TITLE
[SWAGGER] register and login response schema issue

### ISSUE THREAD

**Issue by mutoe** [gothinkster/realworld#1007]
https://github.com/gothinkster/realworld/blob/ea33414e71d739d6b87aa0ecdd83d01dc673c3d2/api/openapi.yml#L39-L49

https://github.com/gothinkster/realworld/blob/ea33414e71d739d6b87aa0ecdd83d01dc673c3d2/api/openapi.yml#L679-L689

https://github.com/gothinkster/realworld/blob/ea33414e71d739d6b87aa0ecdd83d01dc673c3d2/api/openapi.yml#L449-L467

We see that the `password` field is returned in the response of the Login and Register. The `password` should not be returned in any form in the response but should be replaced by the `token` field.

I noticed that this modification happens in https://github.com/gothinkster/realworld/commit/1f6218f4f8bff1ac9102b23f8ed68501e3cb7cbc. In that case, `token` should not be used to update the user profile. However, it does not apply to the `User` response.

**Comment by geromegrignon** [comment]
Hi, indeed too many changes occurred on the previous fix.
Thanks for bringing it out: the PR is merged.
