### ISSUE TITLE
Gather statistics from example apps

### ISSUE THREAD

**Issue by Onumis** [gothinkster/realworld#108]
Since all the implementations adhere to the same spec we can say the functionality is mostly the same across all of them.

With this is mind it'd be quite interesting to have a way of checking some statistics, just for :nerd_face: reasons:

- lines of code
- number of files (with / without config files)
- etc.

Ofc as a side effect, this could ignite framework wars...

**Comment by SandeeshS** [comment]
I don't think this would give us accurate results. Some frameworks are heavy and some are very light. Some codebase make heavy use of third party packages and some bare metal. The actual implementations of features vary from user to user and their coding style. This would mean that the statistics you're talking about would be more than inaccurate to judge a framework or language.

**Comment by EricSimons** [comment]
It's def a really cool idea, however I think @SandeeshS hit the nail on the head. Those sorts of statistics wouldn't necessarily be fair representations of what it's actually like to use those frameworks. However, if someone wrote a Medium/blog post and calculated all of these statistics, I'd definitely list that on the readme under community resources :)
