### ISSUE TITLE
🖥 🔧 Vanilla JS (Web Components)

### ISSUE THREAD

**Issue by criticalbh** [gothinkster/realworld#111]
# Current Status

- ### Codebase in progress:<br /> [criticalbh/vanilla-web-components](https://github.com/criticalbh/vanilla-web-components)
- ### Interested in helping out? Say hello! 🎉

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Awesome! Here's a logo you can use for your repo:

![webcomponent](https://cloud.githubusercontent.com/assets/556934/26126314/021150f8-3a3a-11e7-87bd-7bfc7616f6f8.png)

**Comment by somombo** [comment]
hope it will be in Typescript 😉 
https://staltz.com/all-js-libraries-should-be-authored-in-typescript.html

**Comment by EricSimons** [comment]
@somombo unf I don't think it will, but you should totally fork the final version (once it's ready) and add TS types/interfaces/etc :)

**Comment by criticalbh** [comment]
Application is written at the moment in ES6 but as @EricSimons suggested we can fork it and rewrite with typescript.

**Comment by criticalbh** [comment]
@EricSimons, we have completed development. Could you please take a look at it so we can complete docs also?

**Comment by EricSimons** [comment]
@criticalbh awesome work all! Just spun up the official repo for this and added you to it: https://github.com/gothinkster/web-components-realworld-example-app

Once you add the final details into the docs about installing/running/etc I'll list this on the main readme! 🍻  Seriously amazing work —  the code inside of this looks _beautiful_ :)

**Comment by a1nb0** [comment]
can this be installed locally? 
trying with visual studio code i get ERROR in ./app/components/comments-container.comp.js
Module build failed: SyntaxError: Unexpected token, expected , (44:12)
 what i did: 
git clone .... 
npm install
npm start

**Comment by a1nb0** [comment]
is this going to be listed as a tutorial on thinkster.io too?

**Comment by norayr93** [comment]
It will be awesome to wirte it in typescript , also react with typescript.

**Comment by evantd** [comment]
This seems to have fallen through the cracks. It looks like docs were updated on December 20, 2017, so maybe this is ready to be tagged with v1 and officially listed in the README. I'd love to see how it compares in an updated version of https://medium.com/free-code-camp/a-realworld-comparison-of-front-end-frameworks-with-benchmarks-2019-update-4be0d3c78075

**Comment by evantd** [comment]
@norayr93, check out https://github.com/gothinkster/realworld/blob/master/README.md for implementations in React and Typescript (though not both together yet), and then create an implementation with your favorite combination of technologies.
