### ISSUE TITLE
crizmas-mvc

### ISSUE THREAD

**Issue by raulsebastianmihaila** [gothinkster/realworld#117]
A FE implementation with [crizmas-mvc](https://github.com/raulsebastianmihaila/crizmas-mvc).

https://github.com/raulsebastianmihaila/crizmas-mvc-realworld
https://raulsebastianmihaila.github.io/crizmas-mvc-realworld-site/

**Comment by Cameron-C-Chapman** [comment]
@EricSimons crizmas-mvc looks like a framework on top of react, is there any one with some react experience you think makes sense to take a look at this or should we just validate the front end works as expected and add it to the front page?

**Comment by EricSimons** [comment]
@Cameron-C-Chapman good q — I just took a look at the code and it looks good from a React POV. I think @raulsebastianmihaila is the creator of crizmas itself, so he should have us covered there.

The only thing that I think would be helpful is more info in the docs section — @raulsebastianmihaila could you fill out some of the info in the readme for getting it installed/running, basic overview of the app, etc?

**Comment by raulsebastianmihaila** [comment]
@EricSimons I updated the readme.

**Comment by EricSimons** [comment]
@raulsebastianmihaila just added you to the official repo over at https://github.com/gothinkster/realworld-crizmas-mvc! Can you set up github pages for it there? I'll point crizmas-mvc.realworld.io at it 👍

**Comment by raulsebastianmihaila** [comment]
@EricSimons  Sure, but at the moment it looks like I'm not authorized to push to gothinkster/realworld-crizmas-mvc. The logo looks great BTW!

**Comment by raulsebastianmihaila** [comment]
@EricSimons I setup the github pages. Once the new URL is used (crizmas-mvc.realworld.io) the paths to the resources will work as well. Thanks!

**Comment by EricSimons** [comment]
@raulsebastianmihaila URL has been set up (https://crizmas-mvc.realworld.io) and repo is now listed on the main readme — great job on this! 🎉 

Closing out this issue — any future issues should be filed directly on the crizmas repo (https://github.com/gothinkster/crizmas-mvc-realworld-example-app)
