### ISSUE TITLE
🗄 🔧 Yii2

### ISSUE THREAD

**Issue by Julian-B90** [gothinkster/realworld#118]
# Current Status

- ### Codebase in progress:<br /> [https://github.com/Julian-B90/realworld-starter-kit](https://github.com/Julian-B90/realworld-starter-kit)
- ### Interested in helping out? Say hello! 🎉

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Current Status

Codebase in progress @

**Comment by EricSimons** [comment]
@Julian-B90 here's a logo you can use for the repo!

![yii](https://user-images.githubusercontent.com/556934/26852000-8a79fcdc-4ac1-11e7-9c22-74b053cbf1c9.png)

**Comment by Julian-B90** [comment]
@EricSimons thanks for that. I have added it to the repo.

**Comment by dmitryermichev** [comment]
@Julian-B90 I implemented Conduit functionality in [https://github.com/dmitryermichev/realworld-starter-kit](https://github.com/dmitryermichev/realworld-starter-kit). I made pull request to original repository, please approve it.

**Comment by Julian-B90** [comment]
@EricSimons what you must do next?

**Comment by albertborsos** [comment]
FYI: I also implemented a Conduit backend with passing travis builds which runs the postman collection.
https://github.com/albertborsos/yii2-realworld-example-app

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
