### ISSUE TITLE
🗄 🔧 Erlang + Cowboy

### ISSUE THREAD

**Issue by ghost** [gothinkster/realworld#119]
## Progress / ToDo
- [x] :checkered_flag: Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] :art: Create logo for repo & update issue status (@EricSimons)
- [ ] :hammer: Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] :eyes: Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] :tada: Tag v1 release and officially list it on the README!

## Current Status
Codebase in progress: [vadimvera/realworld_starter_kit](https://github.com/vadimvera/realworld_starter_kit)

---
I'll try to start this one as soon as possbile; if there is an Erlang hacker that want to kick it out just do it!

BTW, @EricSimons your logo "magic" is also needed for this one.

**Comment by EricSimons** [comment]
Logo magic activated!

![erlang](https://user-images.githubusercontent.com/556934/26851749-a421440c-4ac0-11e7-868e-c4479b3885c0.png)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
