### ISSUE TITLE
🖥 🔧 Polymer

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#12]
# Current Status

- ### Codebase in progress:<br /> [spirosikmd/polymer-realworld-example-app](https://github.com/spirosikmd/polymer-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/polymer](https://gitter.im/realworld-dev/polymer)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Anyone out there interested in this? Many folks have been asking for a RealWorld Polymer codebase.

**Comment by spirosikmd** [comment]
@EricSimons I would like to work on that! I am thinking of using Polymer 2.0 release candidate. You think this would be ok?

**Comment by EricSimons** [comment]
@spirosikmd for sure! Go ahead and [fork our starter kit](https://github.com/gothinkster/realworld-starter-kit) and post the link to it back here :)

**Comment by spirosikmd** [comment]
@EricSimons here is the link https://github.com/spirosikmd/polymer-realworld-example-app. I am not sure what was the idea about the current history, but I rewrote to include only initial commit. I hope that's ok!

**Comment by EricSimons** [comment]
More than fine! I've been meaning to squash them all, just have been totally swamped since the launch :)

**Comment by EricSimons** [comment]
Also, just made a logo that you can use for the repo:

![polymer](https://cloud.githubusercontent.com/assets/556934/25643293/e8e38ccc-2f53-11e7-9d8c-efc95988acbe.png)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
