### ISSUE TITLE
🖥 🔧 ClojureScript + Keechma

### ISSUE THREAD

**Issue by retro** [gothinkster/realworld#122]
## Progress / ToDo

- [x] 🏁 Fork the starter repo & post the link in this issue
- [X] 🎨 Create logo for repo & update issue status 
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [x] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [x] 🎉 Tag v1 release and officially list it on the README!

## Current Status

Codebase in progress: [keechma/realworld-starter-kit](https://github.com/keechma/realworld-starter-kit)

**Comment by EricSimons** [comment]
Awesome!! Can't wait to see this @retro :)

**Comment by retro** [comment]
I still need to clean up the code, and write the readme, but the app is done! http://retroaktive.me/conduit/

**Comment by retro** [comment]
This is ready for a review

**Comment by retro** [comment]
@EricSimons @Cameron-C-Chapman what needs to be done to move the project to the next step ( Move repo to main org & Peer review final codebase by admins/community (RFC)). The implementation is done.

**Comment by Cameron-C-Chapman** [comment]
@retro At the very least one of the admins will need to take a look and make sure the basic functionality is there, ideally someone in the ClojureScript and/or Keechma community would take a look and give the stamp of approval. I'll try to carve out some time this week to take a look.

**Comment by retro** [comment]
@Cameron-C-Chapman I'm the lead developer on Keechma framework, so it gets the stamp of approval from my side :) . Ping me if you need any help

**Comment by EricSimons** [comment]
@retro @Cameron-C-Chapman awesome! I'm going to take a peek at this first thing tmrw morning & will spun up the official repo for it 🍻

**Comment by EricSimons** [comment]
@retro just added you to the official repo over at https://github.com/gothinkster/clojurescript-keechma-realworld-example-app!

Can you set up GH pages branch for it? I'll then point clojurescript-keechma.realworld.io at it, and then update the main readme 🍻

**Comment by retro** [comment]
@EricSimons GH pages is set-up and ready

**Comment by EricSimons** [comment]
Just added this to the main readme! 🎉 

So sorry about my delay on this btw, I've been underwater the past month or two building a new product we're launching early next week 😓 This codebase is awesome, and I love the in-depth writeup you did on how it works. I'm thinking we'll send the link out to your repo+article in Thinkster's next email blast in 2 weeks (we have ~200k subscribers, so it should drive a handful of folks to the repo :)

Lmk how that sounds & awesome work man, thanks so much for taking the time to contribute this!

**Comment by retro** [comment]
@EricSimons being included in the next email blast sounds awesome :)
