### ISSUE TITLE
🗄 🔧 Nancy

### ISSUE THREAD

**Issue by codeyu** [gothinkster/realworld#123]
# Current Status

- Codebase in progress:
[codeyu/nancy-realworld-example-app](https://github.com/codeyu/nancy-realworld-example-app)

- Interested in helping out? Say hello! 🎉 

Todo:

- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the [spec &  #API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

**Comment by Cameron-C-Chapman** [comment]
Hi @codeyu, we're really excited to see your realworld implementation! Just to be sure will you be implementing the front end or the back end? I'm not familiar with Nancy but at a quick glance it looked like it was geared more towards API's.

**Comment by codeyu** [comment]
It's the back end. @Cameron-C-Chapman

**Comment by codeyu** [comment]
Hi, @dmytrohridin ,yes, thank you. I've added you as a contributor to this repository: https://github.com/codeyu/nancy-realworld-example-app/invitations .

**Comment by lastlink** [comment]
I think that this may have the issues that many other WIP have and are missing, updating an article & tags.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
