### ISSUE TITLE
[Bug]: Immediately signed out after logging in

### ISSUE THREAD

**Issue by scarf005** [gothinkster/realworld#1230]
### Relevant scope

Deployed demo

### Description

https://user-images.githubusercontent.com/54838975/231349129-a460e9ff-1833-44a8-a275-4d22f0ef8e7e.mp4

after logging in, i cannot access to profile because i get immediately signed out.

**Comment by geromegrignon** [comment]
Welcome to this project,
I gave it a try on Firefox Developer Edition (and multiple other browsers), and I can't reproduce it.
Do you have any logs? How does it work on other browsers on your side?

**Comment by jacekszymanski** [comment]
I have a similar problem, both on Firefox and Safari (but not on Edge), on demo.realworld.io, but not on crizmas-mvc.realworld.io.

It looks like the browser is fetching articles from the old api host, gets redirected and then attempts to fetch from the new api host, but it doesn't send the Authorization header.

![image](https://user-images.githubusercontent.com/208228/233710751-c307c20c-a194-4e31-b8b1-387b219103cf.png)

**Comment by geromegrignon** [comment]
The new demo is available at https://demo.realworld.how/
