### ISSUE TITLE
🗄 🔧 Spring Boot (reactive) + Kotlin

### ISSUE THREAD

**Issue by ghost** [gothinkster/realworld#124]
## Progress / ToDo
- [x] :checkered_flag: Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [ ] :art: Create logo for repo & update issue status (@EricSimons)
- [ ] :hammer: Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] :eyes: Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] :tada: Tag v1 release and officially list it on the README!

## Current Status
Codebase in progress: [vadimvera/kotlin-springboot-reactive-realworld-app](https://github.com/vadimvera/kotlin-springboot-reactive-realworld-app)

---
I'm starting this one as soon as possible ― it won't be "completed" until Spring Data have a release with support for reactive (non-blocking) data access...or I can get it done using Redis, MongoDB (preferably) or Cassandra (definitely not this one).

**Comment by sluongng** [comment]
Oh this is exciting

**Comment by Spenhouet** [comment]
Does this project still exist? The repository doesn't and the TODO list doesn't show any progress.

**Comment by Cameron-C-Chapman** [comment]
@Spenhouet would you be interested in taking over? Since you pointed out that the user and repo don't even exist anymore I'll go ahead and close it unless you want to take over the progress.

**Comment by Spenhouet** [comment]
@Cameron-C-Chapman Thank you for taking action. Sorry, I do not have the time for that.

**Comment by Cameron-C-Chapman** [comment]
Since the user and repo don't exist anymore I'm going to close this.
