### ISSUE TITLE
main.css problem

### ISSUE THREAD

**Issue by lsdlab** [gothinkster/realworld#127]
The comment list below the article page, i think the css is something wrong, it doesn't break-word.

![comment list](https://cl.ly/1p1i0e023532/Image%202017-06-25%20at%2002.33.30.png)

I don't know where should i post this issue, so i posted here.

By the way, GREAT WORK!!!

**Comment by EricSimons** [comment]
@lsdlab thanks for letting us know about this (and the kind words)! I'll try and get a fix in for the main CSS file sometime over the weekend 🍻

**Comment by Cameron-C-Chapman** [comment]
I added this as an issue to the theme's repo since if this is a bug it would need to be fixed there.

https://github.com/gothinkster/conduit-bootstrap-template/issues/1
