### ISSUE TITLE
🖥 🔧 Elm

### ISSUE THREAD

**Issue by chrislewispac** [gothinkster/realworld#13]
# Current Status

- ### Codebase in progress:<br /> [fcevado/realworld-elm](https://github.com/fcevado/realworld-elm)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/elm](https://gitter.im/realworld-dev/elm)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Marking this a WIP as @chrislewispac [is planning on creating it](https://github.com/gothinkster/realworld/issues/9#issuecomment-296273172)

**Comment by fcevado** [comment]
Has anyone started a repo?

**Comment by EricSimons** [comment]
@fcevado nope! Feel free to start one :)

**Comment by fcevado** [comment]
ok :+1:

**Comment by fcevado** [comment]
Just created the repo
https://github.com/fcevado/realworld-elm

**Comment by brwr** [comment]
@EricSimons Can we get a logo for this? 👍

**Comment by EricSimons** [comment]
Just spun up a [gitter room](https://gitter.im/realworld-dev/elm) for this and created the logo for the repo's readme:

![elm](https://cloud.githubusercontent.com/assets/556934/25448178/3e7dc5c0-2a7d-11e7-8069-06da5169dae6.png)

**Comment by pdamoc** [comment]
There is a full implementation of Conduit at:
https://github.com/rtfeldman/elm-spa-example

**Comment by Janiczek** [comment]
"Just Do It™" approach :D

**Comment by EricSimons** [comment]
woot! just added to our main readme :) great work all!
