### ISSUE TITLE
[Bug]: server ERROR 500

### ISSUE THREAD

**Issue by hosseinghs** [gothinkster/realworld#1326]
### Relevant scope

Backend specs

### Description

I called registration and articles endpoint and **server responded with error code 500** and following description: 

"\nInvalid `prisma.article.count()` invocation:\n\n\nCan't reach database server at `db.xkockycklewsktbgowbo.supabase.co`:`5432`\n\nPlease make sure your database server is running at `db.xkockycklewsktbgowbo.supabase.co`:`5432`."

**Comment by geromegrignon** [comment]
Hi, thanks for reporting this issue.

I had a related issue earlier today trying to connect the production database locally but it was still working fine in production with the demo.

I'll investigate tomorrow.

**Comment by geromegrignon** [comment]
Fixed.
It took longer than expected but I took advantage of it to update the API dependencies.
