### ISSUE TITLE
Postman Collection Not Working without Token

### ISSUE THREAD

**Issue by jazib-bashir** [gothinkster/realworld#133]
Hi
I'm working with laravel-realworld-example-app and i have successfully setup application in my linux mint 18 development environment now i'm testing my API call using postman but unable to register a new user.
Test fails with error message: There was an error during JSON.parse(): Unexpected token N in JSON at position 0 and postman return Not allowed. message

![postman-body](https://user-images.githubusercontent.com/8025562/28370439-bfd36ada-6cb3-11e7-8ec5-1381f6686ba2.png)
![postman-enviroment](https://user-images.githubusercontent.com/8025562/28370440-bfd9bf98-6cb3-11e7-8a3d-82c318a70b68.png)
![postman-full](https://user-images.githubusercontent.com/8025562/28370441-bfd9b6c4-6cb3-11e7-9eb1-5ed34b269f74.png)

Kindly Guide me how i fix this issue!

Thanks!

**Comment by jazib-bashir** [comment]
Issue fixed using * at CORS Setting in Laravel

**Comment by Cameron-C-Chapman** [comment]
Glad to hear you got it working @jazib-bashir!
