### ISSUE TITLE
ReasonML frontend project

### ISSUE THREAD

**Issue by Korbin73** [gothinkster/realworld#136]
# Current Status

- ### Codebase now in RFC:<br /> [https://github.com/gothinkster/reasonml-realworld-example-app](https://github.com/gothinkster/reasonml-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Since I will be finishing up my F# backend project in a few weeks. I was wondering if there was any interest in adding a ReasonML (https://reasonml.github.io/) frontend. If so, we can link the start of the project to a repo I have created: https://github.com/Korbin73/realworld-reasonml

**Comment by EricSimons** [comment]
Absolutely! Just updated the status. Will create a logo tmrw for your repo :)

**Comment by nhducit** [comment]
awesome @Korbin73

**Comment by Korbin73** [comment]
This is complete. This project has also been updated to the latest version of ReasonML that has the new javascript like syntax.

**Comment by EricSimons** [comment]
@Korbin73 awesome work!! I just spun up the official repo and added you to it: https://github.com/gothinkster/reasonml-realworld-example-app

I'm pinging some folks in the ReasonML community right now to do a RFC 👍

**Comment by rainerlopez** [comment]
Awesome !

**Comment by sunndeath** [comment]
Could you please close this issue in case of duplicate: #196

**Comment by sunndeath** [comment]
@Korbin73 Could you please close this issue in case of duplicate: #196 ?
