### ISSUE TITLE
[Bug]:  Demo server status is 503

### ISSUE THREAD

**Issue by niyaco** [gothinkster/realworld#1366]
### Relevant scope

Deployed demo

### Description

[https://demo.realworld.io](https://demo.realworld.io/#/) HTTP status is 503,My request in native returns Application Error.

![image](https://github.com/gothinkster/realworld/assets/53268471/449df8f6-e5e8-41a2-a40e-8c870cf640cc)

**Comment by geromegrignon** [comment]
Hi, thanks for the report.

Heroku is unreliable lately, I had to trigger a manual deployment to fix it.
