### ISSUE TITLE
🗄 🔧 Kotlin + Ktor

### ISSUE THREAD

**Issue by AndreasVolkmann** [gothinkster/realworld#138]
# Progress / ToDo
- [x] 🏁 Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

# Current Status

Codebase in progress: [dragneelfps/realworld-kotlin-ktor](https://github.com/dragneelfps/realworld-kotlin-ktor)

**Comment by EricSimons** [comment]
@goreRatzete awesome man! Can't wait to see this!

**Comment by Muhannad508** [comment]
@goreRatzete is this project still active? I'm trying to get involved here. And unfortunately, there is no Issues tab in your Github forked project, which make it hard to discuss

**Comment by goreRatzete** [comment]
@Muhannad508 Hi there. Yes it is still alive. I had a smaller break but will continue working on it soon. I haven't created any issues since I was working alone so far. I can either tell you what needs to be done, or you can have a look yourself. 
Also I have placed many TODOs in the code to show what is missing. If you go through the routes you can quickly find them. 

2 things I am not 100% sure on yet: 
1. Database access and design
2. Json serialization

**Comment by soywiz** [comment]
I have implemented a realworld backend using ktor and mongodb here: https://github.com/soywiz/realworld-kotlin

**Comment by AndreasVolkmann** [comment]
@soywiz Hi there, no it's not finished. Mainly I am waiting for the optional auth feature before proceeding. I see you build it manually in your repo. 

Is your's feature complete yet? Of course we can / should merge. 
One thing that I would change in your setup is the use of Mongo. 
I use an in-memory H2 DB which makes it lighter and easier to try out locally, because you do not have to install any db.

**Comment by soywiz** [comment]
@AndreasVolkmann Nice. FYI: We have just released 0.9.3 that supports optional authentication.

**Comment by AndreasVolkmann** [comment]
@soywiz Yeah I saw it 👍 Great job by the way. 
Again, is you version feature complete yet? 
I see no reason to maintain two separate repos. 
We have a couple of options afaik: 
* Merge your code into my project
* Deprecate my project and use yours from now on

**Comment by soywiz** [comment]
My version is feature complete as far as I know, but it's a bit quick and dirty and needs reviewing and a bit polishing.

Using h2 to not have external dependencies is a good idea for people to use it, but I also think that using another readical different db engine like mongodb provides value to show another way of doing things.
I think that realworld won't require too much effort maintaining once it is done and people could contribute to the implementation.

My proposal would be to complete your version and publish it, and maybe, later, add a folder with another possible implementation using mongodb?

**Comment by anishkny** [comment]
@AndreasVolkmann @soywiz did we settle on a final merged version of this repo? If so could we get this building on TravisCI. It really helps get rid of system dependent hacks and gets everyone on the same page. Thanks!

**Comment by soywiz** [comment]
Nothing new from my side. But my proposal is still to finish the H2 version, and once it is published explore options.
@AndreasVolkmann I can help you finish your implementation if you don't have enough time, and if you are accepting PRs

**Comment by dragneelfps** [comment]
Is this still alive? I am planning to build it from scratch for learning purposes.

**Comment by AndreasVolkmann** [comment]
@dragneelfps please go ahead. I am not working on this anymore.

**Comment by dragneelfps** [comment]
Hi, I have started working on it.
https://github.com/dragneelfps/realworld-kotlin-ktor
@AndreasVolkmann can you update the top post status so that it reflect that I am working on it. It will be helpful for people reading this issue.

**Comment by dragneelfps** [comment]
I have completed the features as per the API spec. But there might be things that I overlooked so I'll do revisions if needed. Also, any PR is welcome. 
I need to do documentation about the stuff the backend is built on, in the readme and some in code, though it mostly is self explanatory. 
If someone can review my code, so we can move forward.

**Comment by dragneelfps** [comment]
Any update?

**Comment by anishkny** [comment]
Could you run the API tests given in this repo (/api folder). Also could you add some CI service on your repo (eg TravisCI). Thanks!

**Comment by dragneelfps** [comment]
@anishkny the tests in the postman collection mentions "celebs" but in the API spec there is not mention of that. Are both, API spec and postman updated? I followed the API spec in my code.

**Comment by anishkny** [comment]
Yup looks good! It also helps a lot setting up CI - could you try that next?

**Comment by dragneelfps** [comment]
What kind of CI does need to be set up? For the .sh provided or ktor unit tests?

**Comment by dragneelfps** [comment]
Any update?

**Comment by anishkny** [comment]
Hey why was [build #3](https://travis-ci.org/dragneelfps/realworld-kotlin-ktor/builds/549436015) cancelled? That had Postman tests correct?

**Comment by dragneelfps** [comment]
[#3](https://travis-ci.org/dragneelfps/realworld-kotlin-ktor/builds/549436015)
was cancelled because the .travis.yaml configuration was wrong. I need help setting up configuration for postman test. My problem is how to run the server, run the .sh test and then stop the server gracefully.

**Comment by anishkny** [comment]
Hmm. How about :

```yaml
script:
  - ./gradlew test build
  - ./gradlew run &    ## <---- notice ampersand
  - ./postman_tests/run-api-tests.sh
  - ./gradlew --stop
```

**Comment by dragneelfps** [comment]
@anishkny thank you for your input. It works now. If there is nothing more to do, I think this repo is ready to be included in the realworld.io project.

**Comment by anishkny** [comment]
great! LGTM PTAL @Cameron-C-Chapman

**Comment by dragneelfps** [comment]
@anishkny should I create a PR to add the repo link to `README` or someone else will update the `README`?
