### ISSUE TITLE
AppRun

### ISSUE THREAD

**Issue by yysun** [gothinkster/realworld#139]
# Current Status

### Todo:

- [X]  🏁 Fork the starter repo & post the link in this issue
- [x]   🎨 Create logo for repo & update issue status (@EricSimons)
- [x]   🔨 Implement all of Conduit's functionality per the spec & API
- [ ]   👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]   🎉 Tag v1 release and officially list it on the README!

----
[AppRun](https://github.com/yysun/apprun) is a 3K frontend library for developing applications using the elm style model-view-update architecture based on event pub and sub pattern. https://yysun.github.io/apprun

**Comment by yysun** [comment]
@EricSimons, Logo has been created.
![logo](https://user-images.githubusercontent.com/170547/30236931-0b73d444-94f4-11e7-8a45-675d330c2461.png)
https://github.com/yysun/realworld-starter-kit/blob/master/logo.png

**Comment by yysun** [comment]
@EricSimons, Functionality developed. Please review the code.

**Comment by EricSimons** [comment]
@yysun sorry about my delay here! Just seeing this now - will get it moved to the main repo tmrw morning :)

**Comment by EricSimons** [comment]
@yysun just added you to the new repo and listed on the main readme!! Thanks so much for your awesome work on this :D

**Comment by yysun** [comment]
Thanks a lot!
