### ISSUE TITLE
Haskell / Scotty

### ISSUE THREAD

**Issue by eckyputrady** [gothinkster/realworld#140]
# Current Status

Codebase in progress: https://github.com/eckyputrady/haskell-scotty-realworld-example-app

## Todo:

- [x] 🏁  Fork the starter repo & post the link in this issue
- [x] 🎨  Create logo for repo & update issue status (@EricSimons)
- [x] 🔨  Implement all of Conduit's functionality per the spec & API
- [ ]  👀  Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉  Tag v1 release and officially list it on the README!

**Comment by EricSimons** [comment]
@eckyputrady woot! Can't wait to see this!!

**Comment by StevenXL** [comment]
@eckyputrady I too can't to see this.

**Comment by madnight** [comment]
any progress?

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
