### ISSUE TITLE
Typescript + node + express

### ISSUE THREAD

**Issue by skopekreep** [gothinkster/realworld#141]
# Progress

 - [x] 🏁  Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
 - [x] 🎨 Create logo for repo & update issue status (@EricSimons)
 - [ ] 🔨 Implement all of Conduit's functionality per the spec & API
 - [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
 - [ ]  🎉 Tag v1 release and officially list it on the README!

&nbsp;
# Current Status

Codebase (in progress):  
[skopekreep/typescript-node-express-realworld-example-app](https://github.com/skopekreep/typescript-node-express-realworld-example-app)

&nbsp;
# Logo (@EricSimons)
![logo](https://user-images.githubusercontent.com/8973526/30294299-da6516da-96f9-11e7-9637-413d2632b8ae.png)

**Comment by EricSimons** [comment]
@skopekreep woot! Can't wait to play around with this!! 👍

**Comment by championswimmer** [comment]
I am working on this

**Comment by wilson-adap** [comment]
+1

**Comment by kmturley** [comment]
@championswimmer Where are you working on it? I would love to have a Typescript version, so I can pair it with Typescript Angular :)

**Comment by championswimmer** [comment]
Oh I'll push it to my github, it is just 4-5 commits down, didn't push it yet.

**Comment by skopekreep** [comment]
Hi @championswimmer, it's been a while since I started this project, but it's about time to get back to it.  If you have made any progress on it please submit a pull request.  Thanks!

**Comment by ngfelixl** [comment]
Is there any progress on it?

**Comment by taylorzhangyx** [comment]
Looking forward to this one!

**Comment by kunwar97** [comment]
I am working on it

**Comment by kunwar97** [comment]
@skopekreep https://github.com/skopekreep/typescript-node-express-realworld-example-app/pull/2

**Comment by LouSypher** [comment]
https://github.com/gothinkster/realworld-starter-kit/issues/53

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
