### ISSUE TITLE
[Bug]: demo APIs down?

### ISSUE THREAD

**Issue by ondblclick** [gothinkster/realworld#1411]
### Relevant scope

Demo APIs

### Description

Looks like demo APIs are down. Getting 503 when performing request in swagger.
Performing the same request in a client also returns 503.
<img width="985" alt="Screenshot 2023-09-05 at 14 08 06" src="https://github.com/gothinkster/realworld/assets/2869150/2cf1d08d-45d9-4fa0-ab40-2c6be9140544">
<img width="816" alt="Screenshot 2023-09-05 at 14 14 32" src="https://github.com/gothinkster/realworld/assets/2869150/8cd4638c-096f-45fb-9b20-03282162e52d">

**Comment by geromegrignon** [comment]
Hi there is an issue with GitHub and Heroku: https://status.heroku.com/

I won't have the bandwidth to fix it with the recommended workaround solution for the next hours. It should be ok before the end of the day.
