### ISSUE TITLE
typescript + node.js(koa)

### ISSUE THREAD

**Issue by LimarenkoDenis** [gothinkster/realworld#142]
# Progress

 [*] 🏁 Fork the starter repo & post the link in this issue
 [  ] 🎨 Create logo for repo & update issue status (@EricSimons)
 [  ] 🔨 Implement all of Conduit's functionality per the spec & API
 [  ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
 [  ]  🎉 Tag v1 release and officially list it on the README!

# Current Status
Codebase (in progress):
[LimarenkoDenis/typescript-node-koa-realworld-example-app](https://github.com/LimarenkoDenis/typescript-node-koa-realworld-example-app)

**Comment by EricSimons** [comment]
@LimarenkoDenis awesome!! Can't wait to see this one :D

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
