### ISSUE TITLE
Angular 4+ / MobX

### ISSUE THREAD

**Issue by davidpodhola** [gothinkster/realworld#143]
Hi, I would like to create an Angular 4+ / MobX frontend implementation. Thanks, David

**Comment by davidpodhola** [comment]
Repository already [created](https://github.com/hsharpsoftware/angular-mobx-realworld-example-app) by forking the original Angular 4+, MobX is being added

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
