### ISSUE TITLE
API server doesn't work

### ISSUE THREAD

**Issue by fullnamemillie** [gothinkster/realworld#1432]
### Relevant Scope

Backend specs

### Description

Server has been down since yesterday
![156](https://github.com/gothinkster/realworld/assets/125590278/64df752f-4286-4280-9410-d11209dc6118)
![157](https://github.com/gothinkster/realworld/assets/125590278/ea4340e1-dbb3-448c-9d67-69a9512cb0b1)

**Comment by geromegrignon** [comment]
Hi @fullnamemillie, that's fixed
