### ISSUE TITLE
Google Cloud Functions + Datastore

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#144]
Serverless Google [Cloud Functions](https://cloud.google.com/functions/) + [Cloud Datastore](https://cloud.google.com/datastore/).

Repo is ready for review: https://github.com/anishkny/realworld-gcp-datastore-cloud-functions

**Comment by EricSimons** [comment]
Woot!! I'm going to ping some folks on the GCP team and see if they can help with the RFC 🎉

**Comment by anishkny** [comment]
friendly 🅿️ing!

**Comment by EricSimons** [comment]
Now listed on the main readme!! Thanks for the awesome work here @anishkny :) I'm actually chatting w/ some gcp folks now about having them tweet this out/etc!

**Comment by anishkny** [comment]
W00t! Thanks so much. 

@EricSimons @apai4 Do you think I can get write access to the [repo](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app)? I wanted to make minor enhancements and get it building in CircleCI.

**Comment by EricSimons** [comment]
@anishkny just added you! I must've forgot to add ya before- sorry about that 😅

**Comment by anishkny** [comment]
Sweet!

Do you think you could enable [Greenkeeper](https://account.greenkeeper.io/account/gothinkster) for gothinkster so I can enable it for the [gcp-datastore repo](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app)? It has been pretty amazing at ensuring dependencies stay up to date.

**Comment by anishkny** [comment]
Hmm, still cant seem to add `gothinkster/gcp-datastore-cloud-functions-realworld-example-app` on my [Greenkeeper config page](https://github.com/settings/installations/55159), I only see my repos:

<img width="752" alt="greenkeeper-gothinkster-issue" src="https://user-images.githubusercontent.com/357499/33092271-a843841a-cec7-11e7-8119-8354f2d170e8.png">
