### ISSUE TITLE
AngularJS 1.2 

### ISSUE THREAD

**Issue by mihail-petrov** [gothinkster/realworld#147]
I am going to start building the Realworld application using the oldschool AngularJS 1.2 

The project repository can be accessed from [here](https://github.com/mihail-petrov/angularjs-1.2-realworld-example-app) 

# Work in progress steps
- fork the realworld repository
- create README 
- develop the application
- have fun

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
