### ISSUE TITLE
Vanilla PHP

### ISSUE THREAD

**Issue by mihail-petrov** [gothinkster/realworld#148]
I am going to start building the Realworld application using the good old vanilla PHP and some utility libraries

The project repository can be accessed from [here](https://github.com/mihail-petrov/vanilla-php-realworld-example-app)

# Work in progress steps

- fork the realworld repository
- create README
- develop the application
- have fun

**Comment by alhoqbani** [comment]
I like the idea. Is it possible to do it without any utility libraries? that's would be awesome.

**Comment by mihail-petrov** [comment]
Challenge accepted. I will include no utility library. But I am also going to prepare another branch that is going to use the bare minimum of utility library like **Guzzle** for example because handling http request by your own it'n no fun.

My thoughts regarding this example is to provide a solution that is based on Vanilla PHP (no framework what so ever) but to provide a base of utility libraries to manage more **realworld** kind of scenario ( no pun intended)

**Comment by Semaho** [comment]
Repo still empty at this time, did you give up ? 😏

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
