### ISSUE TITLE
The user and users routes are Failing Integration Tests on Travis

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [gothinkster/realworld#149]
Something is causing an issue with the automated integration tests. I haven't dug into it yet but it seems to be something with what's returned from the user routes.

https://travis-ci.org/gothinkster/realworld/builds/300696387

**Comment by anishkny** [comment]
The login credentials for johnjacob are not working anymore. Credentials should be passed to the Postman collection via encrypted env vars in Travis. I can look into it tomorrow.

**Comment by Cameron-C-Chapman** [comment]
Thanks @anishkny!
