### ISSUE TITLE
Vanilla Backbone.js

### ISSUE THREAD

**Issue by mihail-petrov** [gothinkster/realworld#152]
I am going to start building the Realworld application using the vanilla version of Backbone.js and no external libraries.

The project repository can be accessed from [here](https://github.com/mihail-petrov/backbone.js-realworld-example-app)

# Work in progress steps
- fork the realworld repository
- create README
- develop the application
- have fun

**Comment by EricSimons** [comment]
@mihail-petrov awesome!! I can't wait to see this :D

**Comment by mihail-petrov** [comment]
After this application is done I am going for Marionette.js  :D

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
