### ISSUE TITLE
[Bug]: API doesn't work

### ISSUE THREAD

**Issue by hyex** [gothinkster/realworld#1535]
### Relevant scope

Backend specs

### Description

Hi, The database server appears to be down. 
API returns a 500 response in both Swagger and the browser.

![image](https://github.com/gothinkster/realworld/assets/48546343/52d06e5e-0c74-4ad1-9e8f-aafadec94c70)

**Comment by SwederellNF** [comment]
Not working for me either

**Comment by geromegrignon** [comment]
Hello, I'll work on this issue tomorrow.
Thanks for the alert.

**Comment by geromegrignon** [comment]
Sorry for the delay, I've been sick for a few days.
Working on it today.

**Comment by geromegrignon** [comment]
Fixed (new Supabase connection string updated).

Have a great day.
