### ISSUE TITLE
[Bug]:CORS Issue 

### ISSUE THREAD

**Issue by abdulrahmanalaa123** [gothinkster/realworld#1537]
### Relevant scope

Frontend specs

### Description

Im facing CORS Problem i presume its a server issue because everything was working fine until it wasnt and after searching most solutions refer to a server fix and not a client fix
this is the error on the deployed site
![image](https://github.com/gothinkster/realworld/assets/29045466/16c62960-1cee-4a46-92b6-35905fe23491)
if it is not a server issue I dont know how to solve it i tried the with credentials solution on my axios and didnt work and here is my axios object
 
![image](https://github.com/gothinkster/realworld/assets/29045466/96a834aa-07b0-45db-87cd-f60928d71975)

and thank you in advance

**Comment by geromegrignon** [comment]
Hello @abdulrahmanalaa123,

It sounds fixed. I was able to reproduce it earlier today though.
CORS settings are fine on the API side: I didn't make any changes, I suspect the domain itself (which i do not own).
