### ISSUE TITLE
[Bug]: Demo backend is down

### ISSUE THREAD

**Issue by illright** [gothinkster/realworld#1538]
### Relevant scope

Deployed demo

### Description

Making a request to, say, https://api.realworld.io/api/tags, results in a Heroku error page

**Comment by geromegrignon** [comment]
Hello @illright,

I restarted the server but still leading to the error.
I can't do much more from my phone, I'll investigate next week (there are anormal memory usage above the allowed limit for the current plan)

Have a great weekend.

**Comment by geromegrignon** [comment]
The server is back.
The application now requires more than 500mb memory for some reason.
I had to upgrade the existing plan.

I'll monitor it for the next week. If it stays the same, I'll stop the server as I can't afford to pay for the new plan alone.
