### ISSUE TITLE
[Bug]: Site Not found

### ISSUE THREAD

**Issue by kirandash** [gothinkster/realworld#1543]
### Relevant scope

Backend specs

### Description

![image](https://github.com/gothinkster/realworld/assets/13310363/75769b4e-6c62-4f9d-8eec-f413e701f121)

The docs site is down

**Comment by geromegrignon** [comment]
Hello @kirandash, thanks for opening this issue.
By trying to log on to my Netlify account, I found out the account is suspended for some unknown reasons.
I'm waiting for support feedback.

You can find the raw version of the documentation here: https://github.com/gothinkster/realworld/tree/main/apps/documentation/docs

**Comment by geromegrignon** [comment]
I got the answer, that's really dumb:

> Hello, your account was reported to be hosting a phishing website and was subsequently suspended.

I guess I'll have to find a Netlify alternative...
