### ISSUE TITLE
[Bug]: CORS problem for the demo

### ISSUE THREAD

**Issue by c4ffein** [gothinkster/realworld#1556]
### Relevant scope

Deployed demo

### Description

I get a `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.realworld.io/api/tags. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 400.` in the console at [https://demo.realworld.io/#/](https://demo.realworld.io/#/)

I can investigate and try to fix it, but maybe you can do it faster.

**Comment by geromegrignon** [comment]
Hi @c4ffein I don't have control over this domain, you can use demo.realworld.how

**Comment by xarielah** [comment]
Still happens, also the new API doesn't work

**Comment by Yugoslife** [comment]
I met the same problem

**Comment by c4ffein** [comment]
See #1611
