### ISSUE TITLE
Adonis

### ISSUE THREAD

**Issue by Utwo** [gothinkster/realworld#156]
# Current Status
## Repository:

[Utwo/adonis-realworld-example-app](https://github.com/Utwo/adonis-realworld-example-app)

- [X] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status ([@EricSimons](https://github.com/ericsimons))
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [x] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉Tag v1 release and officially list it on the README!

**Comment by EricSimons** [comment]
@Utwo can't wait to see this one!!

**Comment by Utwo** [comment]
I have a little block right now. 😞
I don't know how to get current auth user in a Model (eg. Article.js). I need that for knowing if that article was favorited by current user or not.

**Comment by Utwo** [comment]
Ok, I think I finished the API implementation according to the specs 🎉 
@EricSimons what's the next step?

**Comment by Utwo** [comment]
@EricSimons , @Cameron-C-Chapman The codebase is ready for the review. Thank you in advance!

**Comment by anishkny** [comment]
@Utwo could you run Postman API tests specified here: https://github.com/gothinkster/realworld/tree/master/api

Thanks!

**Comment by Utwo** [comment]
I pushed some refactoring and I just run all the tests. I have 3 tests failed because the article slug was deleted right before the test.

**Comment by jaonoctus** [comment]
@Utwo I would like to help you write more tests, I saw that the project only has 1 unit test

**Comment by Utwo** [comment]
Sure, I appreciate any help you can provide! You can open a new PR and I'll take a look ;)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !

**Comment by Utwo** [comment]
This one is not work in progress, the project is ready.

**Comment by geromegrignon** [comment]
Great, fell free to submit it there : https://codebase.show/projects/realworld
