### ISSUE TITLE
[Bug]: 404 Page no found on link in Styles Specifications

### ISSUE THREAD

**Issue by ngterry** [gothinkster/realworld#1564]
### Relevant scope

Frontend specs

### Description

In https://realworld-docs.netlify.app/specifications/frontend/styles/ , a link pointing to "templates & info required to get up and running" is not found.

**Comment by yurisldk** [comment]
@geromegrignon @ngterry this error related for all Markdown links containing .md extensions. I've a solution that should fix this bug. https://github.com/gothinkster/realworld/pull/1580
