### ISSUE TITLE
Hyperloop

### ISSUE THREAD

**Issue by jmenaguale22** [gothinkster/realworld#157]
<h1>Current Status</h1>

<h3>Codebase in progress:</h3>
<a href="https://github.com/ruby-hyperloop/realworld-hyperloop">ruby-hyperloop/realworld-hyperloop</a>

<h3>Interested in helping out? Say hello!</h3>
<a href="http://www.gitter.im/ruby-hyperloop/realworld">gitter.im/ruby-hyperloop/realworld</a>

<h3>Todo:</h3>

- [x] :checkered_flag: Fork the starter repo & post the link in this issue
- [x] :art: Create logo for repo & update issue status (@EricSimons)
- [ ] :hammer: Implement all of Conduit's functionality per the spec & API
- [ ] :eyes: Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] :tada: Tag v1 release and officially list it on the README!

**Comment by mvila** [comment]
Since the [repo](https://github.com/ruby-hyperloop/realworld-hyperloop) is archived, I close this issue.
