### ISSUE TITLE
ClojreScript + re-frame

### ISSUE THREAD

**Issue by jacekschae** [gothinkster/realworld#159]
Repo: https://github.com/jacekschae/conduit
Demo: https://jacekschae.github.io/conduit/

## Todo:

- [x]  🏁 Fork the starter repo & post the link in this issue
- [x]  🎨 Create logo for repo & update issue status (@EricSimons)
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

**Comment by jacekschae** [comment]
I saw that there is #74 but felt like starting from scrach

**Comment by jacekschae** [comment]
Hi @EricSimons, what would be the next step here? Is there anything else you would expect me to do here?

**Comment by EricSimons** [comment]
@jacekschae incredible work!! So sorry about my delay here, I'm just seeing this now 😅  I just spun up the official repo and added you to it: https://github.com/gothinkster/clojurescript-reframe-realworld-example-app

Listing on the main readme now— thanks so much for all your hard work here & congrats sir!  🍻

**Comment by jacekschae** [comment]
@EricSimons thanks for RealWorld! All of this wouldn't be possible without this project.
