### ISSUE TITLE
📱🔧 Ionic 2+

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#16]
# Current Status

- ### Codebase in progress:<br /> [shumbo/ionic-realworld-example-app](https://github.com/shumbo/ionic-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/ionic](https://gitter.im/realworld-dev/ionic)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

This has been a common RealWorld framework request. @mlynch — know anyone in the team/community who would be down to add support for this? :)

**Comment by EricSimons** [comment]
Also, the core logic from the Angular 2 version should be completely reusable here, so most of the work would be strictly related to UI & gluing services together.

**Comment by EricSimons** [comment]
Here's a custom logo that we can use for the project: 
![ionic-realworld-logo](https://cloud.githubusercontent.com/assets/556934/25296463/44395602-269d-11e7-9d53-20c1782190bd.png)

**Comment by shumbo** [comment]
I'm interested on this but seems like the implementation of React Native is in progress. Should I wait and see their design and consider that as a standard?

**Comment by EricSimons** [comment]
@shumbo I can help you w/ the getting the general design set up (I can make the templates/styles, and you can add in the logic), so we should be good to get started 👍 Feel free to fork the starter repo and post in this issue!

**Comment by shumbo** [comment]
@EricSimons Thank you. 

https://github.com/shumbo/ionic-realworld-example-app

Here I folked the repo and started ionic project. I'm not really sure about `community styleguides & best practices`, please let me know if there's better ways.

**Comment by EricSimons** [comment]
@shumbo Ang2 styleguide is probably the most relevant one to follow for this codebase. Also, we have an Ang2 app we can steal services/logic from (https://github.com/gothinkster/angular2-realworld-example-app)

**Comment by ellipizle** [comment]
I will love to help out

**Comment by hamzahamidi** [comment]
I'm working an ionic3 application with firebase, if you're interested https://github.com/hamzahamidi/todo-list. I also made a PWA version. Everything is in the repo. Don't hesitate to open issues. I'll fix them as soon as possible

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
