### ISSUE TITLE
Ractive

### ISSUE THREAD

**Issue by PaulMaly** [gothinkster/realworld#162]
Codebase in progress  [@ here](https://github.com/PaulMaly/realworld-starter-kit)

Will be fully isomorphic and able to work without JS on the client.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
