### ISSUE TITLE
Vert.x (Java)

### ISSUE THREAD

**Issue by skanjo** [gothinkster/realworld#163]
Vert.x implementation in Java.

https://github.com/skanjo/realworld-vertx

**Comment by Cameron-C-Chapman** [comment]
Looking forward to seeing this @skanjo! I marked this as a backend wip but that was a bit of an assumption on my part. If you plan on implementing the front end let me know and I'll update the labels.

**Comment by skanjo** [comment]
Ii will be backend only and is in-progress.

**Comment by leosilvadev** [comment]
What about the impl?
If some help is needed you can count on me to work on backend side. :)

**Comment by skanjo** [comment]
@leosilvadev Help is welcome. Do you have much experience with vert.x? I have limited experience and was trying to learn as I went along. Lately I have been deep in clojure and not spending time on this.

**Comment by leosilvadev** [comment]
Hi @skanjo, yes, I do. I can work on this then, will finish up some pending things and start beginning of June

**Comment by skanjo** [comment]
Sounds good!

**Comment by JosemyDuarte** [comment]
Hi! I don't have to much experience with Vertx, have tried some dummy things on my laptop but nothing professional. But I would like to help you and get some experience along the way. I will try to get some feature ready on the repo.

**Comment by skanjo** [comment]
Well we are in the same boat then for the most part.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
