### ISSUE TITLE
Database Consistency

### ISSUE THREAD

**Issue by tjhunkin** [gothinkster/realworld#164]
The nodejs implementation uses mongodb and the Laravel implementation uses MySQL. Shouldn't the nodejs implementation rather use knexjs (for example) to keep consistency? Which can support a wider variety of databases (mongo-to-knex can be used for mongodb).

I'd like to use the nodejs with MySQL, but I have to now replace the welded on var mongoose = require('mongoose');  because it's hard-coded.

**Comment by Cameron-C-Chapman** [comment]
@tjhunkin, this might be a question that belongs in the individual repos and not necessarily at the realworld level. I'm guessing the node and/or laravel projects would be happy to accept any suggestions or pull requests that would make them more flexible but at the realworld requirement level we aren't really requiring any specific database implementation.

**Comment by tjhunkin** [comment]
I think it should be a standard that each implementation supports multiple database drivers.

**Comment by EricSimons** [comment]
@tjhunkin creating a RealWorld codebase is a huge time investment as is, and forcing specific databases would only make it harder for folks to contribute. Instead, we encourage folks to fork any backend & swap out the DB layer and we'll list their implementation on the readme 👍
