### ISSUE TITLE
Repository Pattern

### ISSUE THREAD

**Issue by tjhunkin** [gothinkster/realworld#165]
Looking at the nodejs implementation, for example, the controllers are very messy with large functions. It's better practice to shift the code into a separate area rather than shoving it all into the controller. In a larger project, the controllers can get extremely bloated.

I understand that this project is to demonstrate implementations, but it'll be better to teach new guys and gals better principles.

**Comment by Cameron-C-Chapman** [comment]
@tjhunkin I agree that best practices are ideal for any of the realworld projects but those best practices can differ quite a bit between the languages/frameworks. We rely on a review process for each project specific to members of that community to help determine if the project is a good representative. It would be really hard to enforce best practices architecturally for such varied code bases. 

Does this feel like something that would be better addressed in the individual repos or maybe an improvement to our review process?

**Comment by tjhunkin** [comment]
I think it should be a standard to separate the code out. Based on this comment and your comment on the database consistency issue, it seems that we're not on the same page. I will refrain from any further comments due to the futility.

**Comment by Cameron-C-Chapman** [comment]
I don't think it's futile or that you need to refrain from submitting questions and ideas @tjhunkin, I'm just giving you my personal opinion but I'm just one opinion.

@gothinkster/realworld-admins any other thoughts on this and/or #166? I think these kind of requirements would be misplaced at the realworld requirement level and make more sense at the individual repo level to be required during the RFC process.

**Comment by EricSimons** [comment]
@tjhunkin I appreciate you imparting feedback on this project but please refrain from insulting our community members.

From a purely technical point of view, I agree that many of these implementations could use some reorganization/refactoring/etc. However, these codebases are intentionally designed to be beginner friendly per the 'golden rule' in our [spec/guidelines](https://github.com/gothinkster/realworld/tree/master/spec#remember-keep-your-codebases-simple-yet-robust): keep the codebases simple yet robust.

If you have comments about how specific implementations can be improved (i.e. node), feel free to open up an issue and/or PR on that repo specifically 👍
