### ISSUE TITLE
Lumen + MongoDB 

### ISSUE THREAD

**Issue by elcobvg** [gothinkster/realworld#166]
Borrows heavily from the existing Laravel implementation, since I only started this because I wanted to give MongoDB a try and I thought this would be a good use case for a document-oriented db. (You know, blog post with embedded comments, tags, user profiles.) Turns out the API specs don't ask for getting article data all-at-once, but I still hope it may be useful to some. 

https://github.com/elcobvg/lumen-realworld-example-app

**Comment by Cameron-C-Chapman** [comment]
@elcobvg so is this project complete and ready to be reviewed or still a WIP?

**Comment by elcobvg** [comment]
Yeah, it's ready to be reviewed. I intended to have a complete test suite, but haven't found the time yet. 
Regarding #165 the repository pattern, I did consider using repositories but decided against it as it seemed a bit too much hassle: based on the API specs, they would all be incomplete implementations anyway.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
