### ISSUE TITLE
Dojo 2

### ISSUE THREAD

**Issue by agubler** [gothinkster/realworld#167]
A Dojo 2 implementation of [Conduit RealWorld application](https://agubler.github.io/dojo2-realworld/dist/)

The project repository can be is [here](https://github.com/agubler/dojo2-realworld)

Please let me know if there is anything more that needs doing! Thanks!

**Comment by agubler** [comment]
Hey all, is there anything I need to do help get this implementation through?

**Comment by Cameron-C-Chapman** [comment]
This looks awesome @agubler 😄 

Hi @agubler, typically we like to get some review from some members of the frameworks community. Do you know anyone who has some experience with Dojo who can give a thumbs up? If not we'll just need to verify everything works and we'll get it added to the home page. 

Let us know if you have anyone who can review or if you're ready for us to just go ahead and verify functionality.

**Comment by agubler** [comment]
Hey @cameron-c-chapman, I’m a contributor on Dojo 2 so I think you can go ahead and review the functionality if that’s okay?

Let me know if you find anything that’s not quite right and I’ll fix it up 😃

**Comment by quanla** [comment]
Hi @agubler, I just tried login using your demo and when server return error, my email/password inputs are cleared so I need to retype. Can I have those values stay in the input so I can change and submit again easier? Does Dojo 2 support that?

**Comment by agubler** [comment]
@quanla could potentially not clear the email input, but it seems common practice to clear at least the password input after a failed login attempt. It’s not any limitation of Dojo 2 but simply by my initial design 😃

**Comment by Cameron-C-Chapman** [comment]
@agubler I'm starting to look at it as well and I had to install the dojo cli but I didn't see that in the README. That would be a good note to add.

**Comment by quanla** [comment]
Ok. Great to know. Thanks @agubler. Btw, is Dojo 2 a reactive programing framework?

**Comment by agubler** [comment]
@cameron-c-chapman Ah yup you need the cli, i’ll add that to the readme. Thanks!

**Comment by agubler** [comment]
@quanla yes Dojo 2 is a reactive framework written in Typescript.

**Comment by Cameron-C-Chapman** [comment]
@agubler this looks good to me. Awesome work! Dojo 2 looks pretty cool, I might have to play around with it a little bit 😄 

@EricSimons Are you good with getting this added officially?

**Comment by agubler** [comment]
@Cameron-C-Chapman Thanks! I added the `@dojo/cli` as a development dependency, added a few npm scripts and updated the readme instructions so it should just work out of the box now.

**Comment by agubler** [comment]
@EricSimons @Cameron-C-Chapman is there anything more I need to do to get this officially added? Thanks!

**Comment by agubler** [comment]
@EricSimons Thank you!!

**Comment by EricSimons** [comment]
This is now listed on the main readme! Amazing work @agubler!! 🎉

**Comment by agubler** [comment]
Awesome thanks @EricSimons

**Comment by agubler** [comment]
@EricSimons Do you mind if I update the realworld repo for Dojo2 directly? Is there a ghpages that it deploys to or do I need to keep that pointing to my ghpage deployment?
