### ISSUE TITLE
Go + net/http Package 

### ISSUE THREAD

**Issue by Kartikkh** [gothinkster/realworld#168]
Hey I am trying to create Realworld with Go+net/HTTP  (https://github.com/Kartikkh/Medium)
The previous work was not completed fully so I have taken a torch from @Jacky (https://github.com/gothinkster/realworld/issues/45)

Thanks

**Comment by Cameron-C-Chapman** [comment]
Awesome look forward to seeing this one 😄

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
