### ISSUE TITLE
Quasar framework

### ISSUE THREAD

**Issue by geoidesic** [gothinkster/realworld#171]
# Current Status
## Repository:
https://github.com/geoidesic/realworld-quasar

- [x] 🏁 Fork the starter repo & post the link in this issue
- [x]  🎨 Create logo for repo & update issue status (@EricSimons)
- [ ]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

**Comment by Cameron-C-Chapman** [comment]
@geoidesic I'm excited to see this one! Just to verify this is a mobile app right?

**Comment by geoidesic** [comment]
Quasar deploys to multiple platforms, mobile being one of them yes.

**Comment by geoidesic** [comment]
@Cameron-C-Chapman Not sure I understand the labels (like does frontend mean it's a web app or does it mean it's not a backend implementation) but to be clear Quasar is a front-end UI framework built on VueJS which deploys to various platforms including web, mobile, desktop. That's its beauty.

**Comment by Cameron-C-Chapman** [comment]
@geoidesic I labeled this mobile because I saw Quasar supported deploying to mobile, I added the frontend label to better categorize it. We don't really have a desktop category but I guess we could, it would be cool to see what this looks like as a desktop app or even an electron version.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
