### ISSUE TITLE
Rust / Rocket

### ISSUE THREAD

**Issue by TatriX** [gothinkster/realworld#172]
https://github.com/TatriX/realworld-starter-kit

**Comment by Cameron-C-Chapman** [comment]
Just to verify is this going to implement the front end or back end?

**Comment by TatriX** [comment]
It's backend.

**Comment by Cameron-C-Chapman** [comment]
Awesome, looking forward to seeing it!

**Comment by TatriX** [comment]
Ok, it's currently passes all the tests and mostly works. Sure it's still need some polish and such. For example I need to get rid of all the `expect`s and rename things to make them consistent.

It would be good if someone could review the code. Thanks!

**Comment by TatriX** [comment]
I think all the required functionality is done. What is the next step?

**Comment by Cameron-C-Chapman** [comment]
@TatriX typically we look for one other member of the Rust community to take a look and give it a stamp of approval. If we can't make that happen then we will clone the repo and test locally and verify everything is working as expected.

One thing I did notice was the blank Demo link. If there won't be a hosted Demo you might just remove that link, not like that would hold us up from merging but just an observation.

I'll make a note to take a look this weekend if no one from the Rust community can chime in.

FYI, this looks really cool, excited to dig in a little bit 😄

**Comment by TatriX** [comment]
Awesome, thanks!

**Comment by TatriX** [comment]
@anishkny sure, done.

**Comment by Cameron-C-Chapman** [comment]
@TatriX I started looking at this and ran into an issue. I've never used rust so maybe I'm doing something wrong but I followed the instructions on your repo and got all the way to `cargo run` but then I hit some errors. 

I was going to file an issue in your repo but it looks like Issues are turned off?

This is what I see:
<img width="848" alt="screenshot 2018-04-07 13 33 47" src="https://user-images.githubusercontent.com/1323581/38458884-ad288d74-3a68-11e8-8e1e-f3a36bdc57ef.png">

Running on a Mac:
System Version:	macOS 10.13.3 (17D102)
Kernel Version:	Darwin 17.4.0

**Comment by TatriX** [comment]
Oh, I don't know why issues was disabled.
The error is strange, maybe `nightly` is broken. I'm going to update and check it.

**Comment by TatriX** [comment]
Yes, it's a mainstream [problem](https://github.com/SergioBenitez/Rocket/issues/601)
I'll find `rustc` version which works.

**Comment by TatriX** [comment]
```sh
rustup toolchain install nightly-2018-04-01
rustup default nightly-2018-04-01
cargo run
```
This seems to work.

**Comment by anishkny** [comment]
Hmm, seems like this was fine [3 days ago](https://travis-ci.org/TatriX/realworld-rust-rocket/builds/362481500). Maybe stable pinned version of rust should be used in README and for TravisCI? Also, turning on [daily cron](https://docs.travis-ci.com/user/cron-jobs/) on TravisCI may not be a bad idea. I too am a total rust noob btw 😄

**Comment by TatriX** [comment]
It works fine now. Do `cargo update` if you want to fix an existing installation.

**Comment by Cameron-C-Chapman** [comment]
@TatriX this looks good to me. 

I only have a couple comments:
* The tests still fail for me. Seems to be around authorization:
```
failures:
    a_auth::register
    b_auth::login
    b_auth::login_and_save_credentials
    c_auth::current_user
```
* With the addition of the `/api/` on the routes the Postman collections provided won't work. Adding that to the route makes sense to me but I just wanted to mention that the postman collections won't work out of the box.

I'm good with adding this to the main page as is though. @EricSimons I'd say this one is ready to go 😄 

Nice job @TatriX!

**Comment by TatriX** [comment]
bump?
