### ISSUE TITLE
Does user sign-up page redirection happens?

### ISSUE THREAD

**Issue by rajeget** [gothinkster/realworld#174]
Hi 

I am trying to create backend API , with angular-2 as frontend.

When the user registers to /api/user POST method , the page is not getting redirected to #/ (home) . 
I have tried to replicate the https://conduit.productionready.io/api/users POST api. 

Can someone confim how the redirect happens?

-Raj

**Comment by Cameron-C-Chapman** [comment]
@rajeget the redirect would be implemented on the front end, after the response is returned. The api itself isn't issuing any redirect headers, all the routing is happening on the front end.
