### ISSUE TITLE
Swift Vapor

### ISSUE THREAD

**Issue by amadeu01** [gothinkster/realworld#175]
## Progress
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

## Current Status
Codebase (in progress):
https://github.com/amadeu01/swift-vapor-conduit-example-app

**Comment by amadeu01** [comment]
@Cameron-C-Chapman Actually, it is not a mobile. It is a server-side (backend) application. `Vapor` is like Django (Python), Rails (Ruby), Express (Node)... Just a webframework

**Comment by amadeu01** [comment]
Hi @Cameron-C-Chapman 

Actually, Vapor is a web framework just like Django, Rails, Express. That is not a mobile project.

**Comment by amadeu01** [comment]
Hi @EricSimons 

Sorry for bothering you, but do you have some time to make the logo for the repository?

**Comment by sherlockmac** [comment]
![vapor_logo](https://user-images.githubusercontent.com/10830730/54496582-173cc200-4906-11e9-9d49-ec11e7a64e15.png)
![swift_vapor_logo](https://user-images.githubusercontent.com/10830730/54496630-d5604b80-4906-11e9-9a6e-34d94e35db73.png)

There you go. I'd also like to help with coding as I'm experimenting with Vapor.

**Comment by amadeu01** [comment]
@sherlockmac I had stopped, but I'll add the logo and make it again hehe. 🎉 
thanks!

**Comment by sherlockmac** [comment]
Let's keep the ball rolling ... let's get Swifty

**Comment by amadeu01** [comment]
@sherlockmac sorry my delay! We got the first PR. I'm gonna give more time to this project !

**Comment by sherlockmac** [comment]
@amadeu01 It's fine.

Let me know if I could help :)

**Comment by jirwong** [comment]
awesome!

**Comment by amadeu01** [comment]
@sherlockmac sorry! I changed from one company to another and things got a little overwhelming. But, I'll keep it rolling now.

**Comment by iq3addLi** [comment]
Hello @amadeu01 
I also intend to implement RealWorld backend with Vapor on Swift.
Please tell me the state if you like 🙏
Thanks

**Comment by amadeu01** [comment]
@iq3addLi sorry my delay. You can open any PR to the project. I'm really slow on this, but I'm going to work on that this weekend 😄

**Comment by iq3addLi** [comment]
@amadeu01
Thank you for reply!
I understand that you will continue the project.
I looked at your project and it seems that the architecture is different from me.
So I'm considering starting a project with a different name, are you in favor?

**Comment by iq3addLi** [comment]
@amadeu01 
Thank you! Let's advance toward completion each other. 😊

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
