### ISSUE TITLE
Angular 6 + @ngrx/store + nrwl/nx

### ISSUE THREAD

**Issue by stefanoslig** [gothinkster/realworld#178]
## **Current Status**

**Codebase ready for the review:**
[https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app](https://github.com/stefanoslig/angular-ngrx-nx-realworld-example-app)

**Demo**
[https://stefanoslig.github.io/angular-ngrx-nx-realworld-example-app](https://stefanoslig.github.io/angular-ngrx-nx-realworld-example-app/#/)

Todo:
- [x] 🏁Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by stefanos-** [comment]
@EricSimons , @Cameron-C-Chapman The codebase is ready for the review.

**Comment by stefanoslig** [comment]
Hello guys, is there any chance to add this project in the main  list or in the WIP list? It's in the same status for so long time. Thank you!

**Comment by anishkny** [comment]
@stefanoslig sorry for the delay. I played around with the deployed app and also locally **and things look good overall**!

I tried to execute tests but did not work:
```
npm test

## This shows up in browser:
AppComponent should create
Failed: Template parse errors:
Can't bind to 'isLoggedIn' since it isn't a known property of 'app-navbar'.
1. If 'app-navbar' is an Angular component and it has 'isLoggedIn' input, then verify that it is part of this module.
2. If 'app-navbar' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
```

It would be good to document in the README how to run tests, and link to TravisCI/CircleCI if you have it setup.

**Comment by stefanoslig** [comment]
hello @anishkny. Thanks for your response. I updated the README as you mentioned and npm test now is working. I need to work on unit tests for libs and this will be one of my first priorities. Of course if someone wants to help, any help is more than welcome.

**Comment by Cameron-C-Chapman** [comment]
Hi @stefanoslig. This looks awesome 😄 

All the tests are passing but I do see some strange behavior where after the initial 3 tests pass the console doesn't free up, and when I try to kill it, it kicks off some new compilation and take a few tries to kill the console. That could just be my machine but something to be aware of.

It looks good to me, we'll get it added to the main readme soon. Thanks for putting it together 🎉
