### ISSUE TITLE
Updating Article Slugs (API Spec)

### ISSUE THREAD

**Issue by xemexpress** [gothinkster/realworld#18]
1. According to the instructions in Rails Course (https://thinkster.io/tutorials/rails-json-api/adding-articles-crud), The slug won't be changed when the title is changed
Please refer to https://github.com/xemexpress/realworld/blob/master/api/README.md 
"The slug also gets updated when the title is changed"

2. Delete Article is missing

**Comment by EricSimons** [comment]
This is intended functionality, no?

**Comment by xemexpress** [comment]
Yes though :stuck_out_tongue:  I just don't know why users shouldn't make that change (on :slug)
Any help?

**Comment by EricSimons** [comment]
Ahhh I understand what you're saying now. Changing the slug won't actually cause anything to break, as the frontends redirect to whatever slug you hand back in the article payload for the [PUT request](https://github.com/gothinkster/realworld/tree/master/api#update-article). So updating slugs are a "nice-to-have" but not mission critical for core functionality :)

That said, @apai4 any recs on how the Rails stack could support updating article slugs?

Btw I just updated the API spec w/ the delete call FYI, shocked no one has caught that until now!

**Comment by apai4** [comment]
@xemexpress The original thinking was that you wouldn't want your URL's to change when the author makes changes to the title otherwise you could get broken links if someone linked to a post externally.

You can make the slugs update on every save by changing this line in `article.rb` in the `before_validate` block:

```diff
before_validation do
- self.slug ||= "#{title.to_s.parameterize}-#{rand(36**6).to_s(36)}"
+ self.slug = "#{title.to_s.parameterize}-#{rand(36**6).to_s(36)}"
end
```
