### ISSUE TITLE
React Universal Hot

### ISSUE THREAD

**Issue by apapacy** [gothinkster/realworld#186]
Creating a new example frontend universal (isomorphic) web app with react, react-router 4, redux, webpack 4: [https://github.com/apapacy/realworld-react-universal-hot ](https://github.com/apapacy/realworld-react-universal-hot)

[Demo](https://realworld-react-universal-hot-ugoaishgjo.now.sh)

**Comment by Cameron-C-Chapman** [comment]
Looks good @apapacy! Is this done and ready for review/addition to the homepage?

**Comment by apapacy** [comment]
Yes, the project is ready for review

**Comment by anishkny** [comment]
hey @apapacy could you help fill out the README Getting Started section? Thanks!

**Comment by apapacy** [comment]
@anishkny 
Updated:
latest versions of webpack, babel
README Getting Started section

**Comment by Cameron-C-Chapman** [comment]
Looks good @apapacy!

A couple of things I noticed and I think we could add it to the main page 🎉 

* Code linting should be `npm run lint`.
*  There is a linting error currently (although if it doesn't break the build I guess it doesn't necessarily have to be fixed but I just want to make sure you're aware of that). 
```
8:19  error  Unable to resolve path to module '../dist/stats.generated'  import/no-unresolved
```
* Running the app in dev mode or production mode is giving me an error.
```
TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/cameronchapman/Personal/realworld-react-universal-hot/node_modules/webpack-cli/bin/config-yargs.js:89:48)
```

It seems like you're super close but I'm not able to run it. I'm on `node v8.11.2`. Could you update the instructions or make the fix so anyone starting from scratch can get the project running?

**Comment by apapacy** [comment]
Thank. I fix the bug with `npm run lint`.

But the bug with the `TypeError: Cannot read property 'properties' of undefined` does not seem to be related not to my project, but to webpack-cli itself. See https://github.com/webpack/webpack/issues/8082

I cleaned npm_modules and executed npm install. This bug has not been reproduced.
node v8.11.2, npm 5.6.0, ubuntu  18.04.1.

**Comment by apapacy** [comment]
@Cameron-C-Chapman 

Thank.

I fix the bug with npm run lint.

But the bug with the TypeError: Cannot read property 'properties' of undefined does not seem to be related to my project, but to webpack-cli itself. See https://github.com/webpack/webpack/issues/8082

I cleaned npm_modules and executed npm install. This bug has not been reproduced.
node v8.11.2, npm 5.6.0, ubuntu 18.04.1.

**Comment by apapacy** [comment]
@Cameron-C-Chapman @anishkny 

Thank. I have not reproduce a bug due to a local file package-lock.json. Now I checked the installation without this file and corrected the bug (changed the version of the weback and wenpack-cli). And now it works

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
