### ISSUE TITLE
API Get Profile is required authentication ?

### ISSUE THREAD

**Issue by koyoyo** [gothinkster/realworld#187]
I tried calling GET https://conduit.productionready.io/api/profiles/:username without Token and it's returned 401 Unauthorized.

But from your [API Spec](https://github.com/gothinkster/realworld/tree/master/api#get-profile). It's said that "Authentication optional". So, it should return profile if found or 404 if not.

Is there anything wrong or am I misunderstanding ??

**Comment by Cameron-C-Chapman** [comment]
Hi @koyoyo 👋 

I was able to run the following curl with no authentication and didn't need to be authorized. What is the user you were searching for?

`
curl -X GET \
  https://conduit.productionready.io/api/profiles/rick \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -H 'X-Requested-With: XMLHttpRequest'
`

**Comment by koyoyo** [comment]
Sorry, My mistake. I used Postman and attached local Token to your testing site.
