### ISSUE TITLE
Angular2 - TypeError: error.json is not a function

### ISSUE THREAD

**Issue by rajeget** [gothinkster/realworld#188]
Hi 

At load time Angular2 is showing this error ( Please see below) . Also If there is a error send from backend , it does not show . For example if Sign-in screen doesnot show error message for say 403 reply from server. 

`
ERROR 
TypeError
columnNumber: 38
fileName: "http://localhost:4200/main.bundle.js line 486 > eval"
lineNumber: 26
message: "error.json is not a function"
stack: "ApiService.prototype.formatErrors@webpack-internal:///../../../../../src/app/shared/services/api.service.ts:26:38\nCatchSubscriber.prototype.error@webpack-internal:///../../../../rxjs/_esm5/operators/catchError.js:108:26\nSubscriber.prototype._error@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:136:9\nSubscriber.prototype.error@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:110:13\nSubscriber.prototype._error@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:136:9\nSubscriber.prototype.error@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:110:13\nOuterSubscriber.prototype.notifyError@webpack-internal:///../../../../rxjs/_esm5/OuterSubscriber.js:26:9\nInnerSubscriber.prototype._error@webpack-internal:///../../../../rxjs/_esm5/InnerSubscriber.js:30:9\nSubscriber.prototype.error@webpack-internal:///../../../../rxjs/_esm5/Subscriber.js:110:13\nonError@webpack-internal:///../../../common/esm5/http.js:2341:17\nZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:421:17\nonInvokeTask@webpack-internal:///../../../core/esm5/core.js:4941:24\nZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:420:17\nZone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:188:28\nZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:495:24\ninvokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1536:9\nglobalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1562:17\n"`

**Comment by rajeget** [comment]
Anyone any update ?

**Comment by Cameron-C-Chapman** [comment]
Hi @rajeget 😄 Is this an issue with the Angular front end implementation? If so that should be filed as an issue in that specific repo, not this repo.

If that doesn't make sense let me know, but I'm going to close this now so you can file the issue in the Angular repo.
