### ISSUE TITLE
Blazor

### ISSUE THREAD

**Issue by torhovland** [gothinkster/realworld#191]
## Codebase in progress:
https://github.com/torhovland/blazor-realworld-example-app
If you'd like to help out, you're welcome!
## Demo:
https://blazor-realworld.azurewebsites.net

**Comment by stavroskasidis** [comment]
Is this dead ? Can someone else give it a go ?

**Comment by burke166** [comment]
I'm working on something using Razor Components aka Server-Side Blazor, which is similar to this but not exactly the same. [https://github.com/computercodeblue/razor-components-realworld-example-app](https://github.com/computercodeblue/razor-components-realworld-example-app). Routing seems to be no worky as I write this, but I just got to the point that it works on my local machine and in IIS.

**Comment by HugoDoyon** [comment]
Guys: Why the Blazer.net demo app taking so long to load compare to React demo (see here https://github.com/gothinkster/realworld)? 

Is it Blazor.net "Server" version that create this "loading..." delay? 

Hoping C# will be able to challenge React or Angular speed one day!

**Comment by coman3** [comment]
@HugoDoyon, have a close look at the network tab in chrome. You'll see that the app is just HUGE compared as it needs to download the mono WASM runtime...

**Comment by HugoDoyon** [comment]
Indeed Mono WASM is Massive 1.72MB! Microsoft can do much better than that!
![image](https://user-images.githubusercontent.com/17368121/80648306-f23ddc80-8a3d-11ea-8b4b-00d1ae645d80.png)

**Comment by rohanbojja** [comment]
@HugoDoyon Indeed, perhaps in the near future. They addressed this in one of the Blazor sessions.

**Comment by joey32793** [comment]
Following up on this. From the looks of the two previously linked repos in this thread, it seems that both projects have been somewhat abandoned. I'd like to offer up my implementation using the latest version of .NET Core:

Repo: https://github.com/joey32793/BlazorConduit
Demo: https://blazor-conduit.netlify.app/

While I'm positive there's still some work to do (currently at `v1.0.0-mvp`), anyone is welcome to pitch in. I've completed all the required workflows and added a few cypress tests, but I would like to eventually add bUnit tests if anyone is interested in a good first issue. CI/CD is hooked up through Azure DevOps, and I'll be continually working on this as time permits.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
