### ISSUE TITLE
Bridge.Spaf

### ISSUE THREAD

**Issue by markjackmilian** [gothinkster/realworld#193]
Spaf is a framework build on top of Bridge.Net.

Codebase in progress:
[https://github.com/markjackmilian/bridge.spaf-realworld-app](https://github.com/markjackmilian/bridge.spaf-realworld-app)

Demo:
[https://markjackmilian.github.io/realworld.spaf](https://markjackmilian.github.io/realworld.spaf)

Tests:
[https://markjackmilian.github.io/realworld.spaf.tests/](https://markjackmilian.github.io/realworld.spaf.tests/)

**Comment by markjackmilian** [comment]
all functionality has been done. Can it be considered completed?

**Comment by anishkny** [comment]
great work @markjackmilian. Do you think you can build this project on some CI system (TravisCI/CirlceCI/Azure Pipelines) to demonstrate how to build it? That would be really helpful!

**Comment by markjackmilian** [comment]
I'll look at it as soon as I can.

**Comment by markjackmilian** [comment]
hi!
i add a simple azure pipeline with badge on repo.
Do you think it's ok?

**Comment by anishkny** [comment]
Thanks - although I can't see the project - could you make it publicly visible?

[![Build Status](https://dev.azure.com/markjackmilian/realworld/_apis/build/status/markjackmilian.bridge.spaf-realworld-app?branchName=master)](https://dev.azure.com/markjackmilian/realworld/_build/latest?definitionId=1&branchName=master)

**Comment by markjackmilian** [comment]
sorry, i just modify project policy. Can you try again?

**Comment by anishkny** [comment]
LGTM PTAL @Cameron-C-Chapman
