### ISSUE TITLE
ReasonReact (ReasonML)

### ISSUE THREAD

**Issue by jihchi** [gothinkster/realworld#196]
## Progress

- [x]  🏁 Fork the starter repo & post the link in this 
- [x]  🎨 Create logo for repo & update issue status
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

## Current Status
Codebase (done):
https://github.com/jihchi/reason-react-realworld-example-app

**Comment by jihchi** [comment]
New logo: ![logo](https://cdn.rawgit.com/jihchi/reason-react-realworld-example-app/b14cc7a2/logo.png)

**Comment by jihchi** [comment]
Hi @Cameron-C-Chapman , The codebase is done.

**Comment by anishkny** [comment]
@jihchi awesome! Do you think you could fill out README sections on How it works, getting started etc? Also, would be great if there was a hosted demo we could look at?

Cheers!

**Comment by jihchi** [comment]
@anishkny Wow, thank you for so fast response.

I'm working README, unit test and hosted demo.
I'll update here when its done.

**Comment by jihchi** [comment]
@anishkny I've completed README, minimum unit test and hosted demo.

**Comment by anishkny** [comment]
Great. Played around a little bit and looks good. For some reason I am seeing different fonts compared to the [React/Redux Demo](https://react-redux.realworld.io/), but rest seems awesome.

**Comment by jihchi** [comment]
@anishkny I forgot to delete unused CSS. Its back to normal. Thank you.

**Comment by jihchi** [comment]
I haven't found #136  before (tried [search](https://github.com/gothinkster/realworld/search?q=reason&type=Issues) but didn't see it).

**Comment by Cameron-C-Chapman** [comment]
Looks good to me too! Nice work @jihchi!

I didn't realize there was 2 ReasonML implementations in progress. Looking at the issues it looks like it was complete awhile ago also. 😬 

@jihchi you mind taking a look and seeing if there is anything different between the 2 repos approaches? We should probably add them both to the README so it would be nice if there was some difference (version, architecture), etc that we could differentiate the 2 somehow.

**Comment by jihchi** [comment]
@Cameron-C-Chapman 

There are some different between tech stack:

Tool | gothinkster/reasonml-realworld-example-app | jihchi/reason-react-realworld-example-app
---|---|---
Version of ReasonReact | `^0.2.4` | `0.4.1`
Version of BuckleScript | `2.0` | `3.0`
JS Bundler / Dev-server | Custom Webpack config | react-scripts@next
Client-side Routing |`bs-director` | ReasonRouter's built-in router
Testing |`bs-jest` | `bs-jest` + Enzyme
Form & Validation | N/A | `re-formality`
Storage of toke | LocalStorage | Cookie

I think **gothinkster/reasonml-realworld-example-app** is a little of out-dated.

**Comment by anishkny** [comment]
Pinged the ReasonML [Discord](https://discordapp.com/invite/reasonml) to get a review!

**Comment by Madsn** [comment]
I tried cloning and running the repo, exactly as described in the readme - I'm getting a lot of CRA linting warnings on the generated JS.

e.g.
```
<snip>
[ReasonML] >>>> Finish compiling
[CRA] Failed to compile.
[CRA]
[CRA] ./src/Profile.bs.js
[CRA] Compiling...
[CRA] Compiled with warnings.
[CRA]
[CRA] ./src/API.bs.js
[CRA] /d/repo/reason-react-realworld-example-app/src/API.bs.js
[CRA]   2:1  warning  'use strict' is unnecessary inside of modules  strict
[CRA]
[CRA] ✖ 1 problem (0 errors, 1 warning)
[CRA]   0 errors, 1 warning potentially fixable with the `--fix` option.
[CRA]
[CRA]
[CRA] ./src/App.bs.js
[CRA] /d/repo/reason-react-realworld-example-app/src/App.bs.js
<snip>
```

**Comment by jihchi** [comment]
@Madsn 

Yes, It works as expected. It's just warning, you still could start & build the project.

**Comment by Madsn** [comment]
A bucklescript hook to add eslint ignore comment to the top of the file *might* remove the linting errors, depending on if the hook is run before or after the file is actually saved to disk and then caught by the linter.

Not ideal for sure, would be a bit of a performance hit, but might be less of a performance cost than linting the generated files.

https://bucklescript.github.io/docs/en/build-configuration.html#js-post-build

**Comment by jpeg729** [comment]
Works only partially.

I cloned, built and ran it. Ok.
I tried signing up and got the following error messages displayed.

* Username can't be blank
* Email can't be blank
* Password can't be blank

They weren't blank.

**Comment by jihchi** [comment]
@jpeg729 I'll take a look later. Thanks for your report.

**Comment by jihchi** [comment]
@jpeg729 I've fixed and deployed. thanks for your feedback.

**Comment by forrest-akin** [comment]
Hi, just checking in. The project looks like it's more or less ready to merge, but there hasn't been any activity here in awhile. What are the next steps here? Thanks!

**Comment by jihchi** [comment]
Hi @forrest-akin ,

Currently, I'm working on upgrading `re-formality` to latest version.
My goal is migrating codebase to use React Hooks.
You can see it at [this](https://github.com/jihchi/reason-react-realworld-example-app/tree/upgrade_react_hooks) branch, It's still a work in progress.

**Comment by sunndeath** [comment]
Is it relevant?
I don't see the app in the list on the main page.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
