### ISSUE TITLE
Add Testing

### ISSUE THREAD

**Issue by Branksy** [gothinkster/realworld#203]
Add most commonly used test frameworks for current codebases - e.g. RSpec for Rails

**Comment by Cameron-C-Chapman** [comment]
@Branksy I agree I'd love to see unit testing as part of each codebase. We're making more of a point of bringing that up during the initial review before adding a project to the homepage now but there are a lot of projects that don't have any testing.

I would say that it would be more appropriate to bring those issue up in the respective repository and work on getting them added to the project there as opposed to bringing it up globally here. You'll definitely get more traction that way.
