### ISSUE TITLE
Surplus wip

### ISSUE THREAD

**Issue by adamhaile** [gothinkster/realworld#204]
I did an implementation for [Surplus](https://github.com/adamhaile/surplus), available [here](https://github.com/adamhaile/surplus-realworld).  Still need to add some tests for final submission.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
