### ISSUE TITLE
Serverless Typescript + Mongodb (implementation done)

### ISSUE THREAD

**Issue by QingpingMeng** [gothinkster/realworld#206]
Backend, runs in AWS Lambda environment + mongodb.
Repository : https://github.com/QingpingMeng/medium-clone-api

Functionality per the spec & API has been implemented. Just deploy and connect to your front end and you are good to go!

- [x] 🏁Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@EricSimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

**Comment by gyukebox** [comment]
Which serverless framework are you using?

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
