### ISSUE TITLE
Scala akka-http implementation of realworld

### ISSUE THREAD

**Issue by lilac** [gothinkster/realworld#207]
[Work in Progress] [Link to repo](https://github.com/lilac/realworld-scala/tree/akka-http)
It is based on the scala play implementation.

**Comment by 1984weed** [comment]
Hi there.
Now I'm working on it. It's different from the top of comment repo.
https://github.com/1984weed/akka-http-realworld-example

If I could complete it, would you accept my repo? 

thanks

**Comment by anishkny** [comment]
@1984weed go for it! I have opened a new issue (#345) to track Akka HTTP. 

Looks like Scala Play is already added to main READE so closing out this issue.
