### ISSUE TITLE
Azure Functions + CosmosDb

### ISSUE THREAD

**Issue by BennyM** [gothinkster/realworld#209]
I've started building a backend using Azure Functions and CosmosDb, forked [here](https://github.com/BennyM/realworld-starter-kit).

**Current Status**
_Todo_
- [ ] Users (Registration) Endpoint
- [ ] User Endpoint
- [ ] Profile Endpoint
- [ ] Articles CRUD Endpoint
- [ ] Articles Comment Endpoint
- [ ] Articles Favorite Endpoint
- [ ] Tags Endpoint
- [ ] Azure ARM template
- [ ] Demo App

**Comment by starketin** [comment]
Hi @BennyM,

is there any progress on this? I'm currently looking for a reference application using Azure Functions.

Thx
Simon

**Comment by HowardEdidin** [comment]
If you are not working on this,  I can take over. I am a former MS  MVP for Cosmos DB and an Azure Architect

**Comment by BennyM** [comment]
I’ve only dabbled with the setup, so feel free to pick it up.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
