### ISSUE TITLE
🗄🔧 Firebase + GCP Cloud Functions

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#21]
# Current Status

- ### Codebase in progress:<br /> [github.com/anishkny/realworld-firebase-gcp-cloud-functions](https://github.com/anishkny/realworld-firebase-gcp-cloud-functions)

- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/firebase-gcp](https://gitter.im/realworld-dev/firebase-gcp)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

My *most favorite* backend as a service! ☺️

**Comment by EricSimons** [comment]
Mine too :) I'm wondering what the best way to implement the RealWorld spec w/ Firebase would be. Using the wrapper libraries like AngularFire, ReactFire, etc? Or do a lot of people use just the vanilla Firebase JS lib?

**Comment by anishkny** [comment]
Personally I am a fan of VueJS and hence by extension VueFire, but that or AngularFire/ReactFire would be for the front end right?

I was thinking of implementing the **backend** API with a thin [GCP Cloud Functions](https://cloud.google.com/functions/docs/) layer backed by Firebase. Since the spec backend API won't be supported out of the box by Firebase.

Btw, I am fairly new to GCP and backend work, but thought this would be a great way to teach myself. Also this is a such a great idea, thanks to you and the team for setting it up. It seems a natural progression from [TodoMVC](http://todomvc.com) for the full stack! 💯

**Comment by EricSimons** [comment]
I hadn't even considered GCP Cloud + Firebase — that's an _excellent_ idea. I can't wait to see one :) Wanna fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) and post the link back here so folks can watch/fork your work?

**Comment by EricSimons** [comment]
@anishkny I just created a logo that you can use for the readme:


![firebase-gcp](https://cloud.githubusercontent.com/assets/556934/25307519/1a53bcdc-2757-11e7-8401-c48eb67ba349.png)

**Comment by anishkny** [comment]
Thanks for the logo!

Forked the starter & WIP: [anishkny/realworld-firebase-gcp-cloud-functions](https://github.com/anishkny/realworld-firebase-gcp-cloud-functions)

**Comment by EricSimons** [comment]
Just set up [**the Gitter chatroom**](https://gitter.im/realworld-dev/ember) for this! Lets do any collaborator coordination in there 👍

cc/ @anishkny

**Comment by brwr** [comment]
Hey @anishkny! Any update on this? Anything we can do to help?

**Comment by chencitrix** [comment]
So what about this pattern：( how do you do it or what? )

This has become a popular Solitaire game tonight, and is the subject of
repeated tonight.
Can we enter the topic?

ChenCritix

2017/4/26 下午11:06，"James Brewer" <notifications@github.com>寫道：

**Comment by anishkny** [comment]
@chencitrix not sure if this the right thread?

Updates: So far I have managed to setup the entry point handler with few routes implemented.

Meanwhile, Firebase database design is evolving in README.

Also setup an overall v1 [tracker](https://github.com/anishkny/realworld-firebase-gcp-cloud-functions/issues/1).

I am looking for collaborators, with interest shown from @RomarioRaffington and @rezn5447

**Comment by chencitrix** [comment]
The prerequisite is that immediate short-term contracts should be provided
to provide the largest common denominator of a pipeline, short-term
commodity content can not be too competitive, it is important to note that
in a dark period, it is in accordance with a prospective psychological, but
the creation of goods Value rather than profit or speculation with a
temporary pipeline, making an inconsistent move to create a maximum degree
of reflow and expansion.

anishkny <notifications@github.com> 於 2017年4月26日 星期三寫道：

> <https://github.com/chencitrix>

> @chencitrix <https://github.com/chencitrix> not sure if this the right
thread?
>
> Updates: So far I have managed to setup the entry point handler with few
routes implemented.
>
> Meanwhile, Firebase database design is evolving in README.
>
> Also setup an overall v1 tracker
<https://github.com/anishkny/realworld-firebase-gcp-cloud-functions/issues/1>
.
>
> I am looking for collaborators, with interest shown from
@RomarioRaffington <https://github.com/RomarioRaffington> and @rezn5447
<https://github.com/rezn5447>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/gothinkster/realworld/issues/21#issuecomment-297447314>,
or mute the thread

**Comment by doowb** [comment]
I just discovered this realworld project and started looking for firebase related projects and found this one. However, this is using Google Cloud Functions directly instead of using Firebase Cloud Functions (which run on top of GCF). Would it be out of scope if I created a parallel project using Firebase Cloud Functions to show the tools and patterns used for those? I think I could also contribute to some of the missing pieces here.

**Comment by anishkny** [comment]
hi @doowb Firebase really shines when used as a Fullstack implementation, since it has mature JS APIs that plugin directly into the frontend codebase. Would you be interested in starting a new Firebase full stack repo? If so you can send a PR linking it here:

https://github.com/gothinkster/realworld#fullstack

I have sort of abandoned [Firebase + Cloud Functions](https://github.com/anishkny/realworld-firebase-gcp-cloud-functions) in favor of [Datastore + Cloud Functions](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app) which is now feature complete.

**Comment by Cameron-C-Chapman** [comment]
@anishkny Is this really still active? Can we go ahead and close it?

**Comment by anishkny** [comment]
Abandoned in favor of [GCP Cloud Functions + Datastore](https://github.com/gothinkster/gcp-datastore-cloud-functions-realworld-example-app) BE implementation. Please reopen if anyone else wants to work on this.
