### ISSUE TITLE
Fulcro (Clojure + Clojurescript)

### ISSUE THREAD

**Issue by LiesbethW** [gothinkster/realworld#210]
# Current Status
## Progress
- [x]  🏁 Fork the starter repo & post the link in this
- [ ]  🎨 Create logo for repo & update issue status
- [ ]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

## Codebase (in progress):
https://github.com/LiesbethW/realworld-fulcro-fullstack

**Comment by myguidingstar** [comment]
I'm working on another implementation here: https://github.com/walkable-server/realworld-fulcro

Atm, server side is complete, frontend is a wip

**Comment by souenzzo** [comment]
I'm working on this one 
https://github.com/souenzzo/eql-realworld-example-app/

It already looks OK and it's able to login.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
