### ISSUE TITLE
SailsJs 1.0 Example Application

### ISSUE THREAD

**Issue by brookesb91** [gothinkster/realworld#211]
https://github.com/brookesb91/sailsjs-realworld-example-app

Framework homepage - https://sailsjs.com

An example SailsJs application with views. 

- [x] Fork the starter repo & post the link in this issue
- [ ] Create logo for repo & update issue status
- [ ] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase
- [ ] Tag v1 release and officially list it on the README

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
