### ISSUE TITLE
Express w/ Bookshelf.js

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [gothinkster/realworld#212]
https://github.com/tanem/express-bookshelf-realworld-example-app

- [x] Fork the starter repo & post the link in this issue
- [ ] Create logo for repo & update issue status
- [ ] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase
- [ ] Tag v1 release and officially list it on the README

**Comment by tanem** [comment]
Hey @Cameron-C-Chapman, I just merged down a bunch of stuff re `docker-compose`, so I think the repo is ready for at least an initial glance? 👀 

I've noted it in the testing part of the `README`, but the project is passing it's internal test suite as well as the [`realworld-server-tester`](https://github.com/agrison/realworld-server-tester).

There's definitely more that can be done to improve things, for example the docs are still a WIP really, plus some parts of the implementation I have more exp. with than others, so I'd be super grateful for any feedback at all 🙏 

Thanks!

**Comment by Cameron-C-Chapman** [comment]
I think this looks awesome @tanem! Great work! I'll go ahead and get this added to the main repo.

Awesome job! 🎉

**Comment by tanem** [comment]
That's great 😃 Thanks for taking the time to do this!
