### ISSUE TITLE
Can't login after logout, clear cache and refresh

### ISSUE THREAD

**Issue by geoidesic** [gothinkster/realworld#214]
Hi,

I've tried on a number of the official front-end releases (Vue and clojurescript-keechma) and I can register an account once but after I logout, clear cache and refresh (or using a different browser), I cannot log back in using that account details. I also can't re-register using the same account details.
I suspect that the login back-end API is expecting a JWT which isn't being sent in this case.

If I register then logout, then immediately login (without clear cache and refresh) then it works.

Is this a flaw in the back-end API spec or the front-end one?

**Comment by Cameron-C-Chapman** [comment]
This might be an issue with the deployed instance which is the rails backend implementation.

We can try running against one of the other back ends to see if we can reproduce and if not we probably should file this as an issue in that repo.

**Comment by abhinavsharma629** [comment]
hey can you assign me this task? I can fix it for Django.

**Comment by cirosantilli** [comment]
I think this should be moved as an issue to each specific implementation.
