### ISSUE TITLE
Golang + Echo

### ISSUE THREAD

**Issue by xesina** [gothinkster/realworld#216]
Hi,
Work in progress at https://github.com/xesina/golang-echo-realworld-example-app

**Comment by SUP3RIA** [comment]
@xesina Are you still working on this? Would love to see this getting finished!

**Comment by xesina** [comment]
@SUP3RIA Yes, I've tested it with React/Vue frontend and it's fully working now
It just needs a little bit of clean up and docs. I'm getting it ready by the end of this week.

**Comment by recoilme** [comment]
looks clean!

**Comment by xesina** [comment]
@Cameron-C-Chapman I think it's ready. I wrote the minimum tests and also tested it with react and vue frontend

**Comment by recoilme** [comment]
@xesina i like your work. Take a look please on my version of totally refactored realworld app 
https://github.com/gothinkster/realworld/issues/234
I start from scratch this project - and if you like it and have time -  it's open source and opens for contributors. Not finished now, but looks promising

**Comment by xesina** [comment]
@Cameron-C-Chapman This is finished about 20 days ago, can you take a look at this?

**Comment by Cameron-C-Chapman** [comment]
@xesina Sorry for the delay.

I started taking a look at this but ran into some issues. I'm not super familiar with go so it might be an obvious path related issue but since the instructions should be easy to follow for a beginner I think it's relevant.

I can't add an issue directly to your repo so I'll add the issue here.

Following the directions exactly I run into this issue:

```
$ which go
/usr/local/bin/go

$ which dep
/usr/local/bin/dep

$ dep ensure
/Users/cameronchapman/Personal/golang-echo-realworld-example-app is not within a known GOPATH/src

$ go run main.go
main.go:5:2: cannot find package "github.com/xesina/golang-echo-realworld-example-app/db" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/xesina/golang-echo-realworld-example-app/db (from $GOROOT)
	/Users/cameronchapman/go/src/github.com/xesina/golang-echo-realworld-example-app/db (from $GOPATH)
main.go:7:2: cannot find package "github.com/xesina/golang-echo-realworld-example-app/handler" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/xesina/golang-echo-realworld-example-app/handler (from $GOROOT)
	/Users/cameronchapman/go/src/github.com/xesina/golang-echo-realworld-example-app/handler (from $GOPATH)
main.go:4:2: cannot find package "github.com/xesina/golang-echo-realworld-example-app/router" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/xesina/golang-echo-realworld-example-app/router (from $GOROOT)
	/Users/cameronchapman/go/src/github.com/xesina/golang-echo-realworld-example-app/router (from $GOPATH)
main.go:6:2: cannot find package "github.com/xesina/golang-echo-realworld-example-app/store" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/xesina/golang-echo-realworld-example-app/store (from $GOROOT)
	/Users/cameronchapman/go/src/github.com/xesina/golang-echo-realworld-example-app/store (from $GOPATH)
```

Maybe some instructions about configuring the path make sense to add?

**Comment by xesina** [comment]
@Cameron-C-Chapman Thanks for your review. I added detailed instructions and helpful links.
I will update links later to point to this repo on gothinkster.

**Comment by xesina** [comment]
@Cameron-C-Chapman How Can we proceed on this? It's seems that you're too busy :)

**Comment by anishkny** [comment]
@xesina do you think you could try and build this project on [TravisCI](https://docs.travis-ci.com/user/languages/go/). This should help prevent machine specific setup pitfalls?

**Comment by xesina** [comment]
@anishkny Good Idea! thanks, Done.

**Comment by xesina** [comment]
@anishkny @Cameron-C-Chapman

**Comment by anishkny** [comment]
LGTM #287
