### ISSUE TITLE
User management or Superadmin

### ISSUE THREAD

**Issue by entrptaher** [gothinkster/realworld#217]
RealWorld is great and I've used this as baseline for many different projects. With all awesome features floating around, I felt there is one thing missing, and which is a super admin or user role management. 

However, I assume the team over gothinkster doesn't have any plan to add a user management system if I am right. What can be done in this particular case?

If anyone implemented such, please reply with some guideline/resources.

**Comment by anishkny** [comment]
@entrptaher thanks for your kind words, glad RealWorld is of use!

We kind of wanted to keep things simple for v1 but discussed the idea of having "extra credit" features, could you chime in at #90?

**Comment by entrptaher** [comment]
Will follow up on that issue, thanks.
