### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#218]
Trying out a RealWorld FE implementation using [Nuxt.js](https://nuxtjs.org) over at [anishkny/realworld-nuxt](https://github.com/anishkny/realworld-nuxt)

**Comment by devJang** [comment]
@anishkny 

this issue still work in progress?
I built a nuxt project for realworld example app

- [x] Nuxt
- [x] TypeScript
- [x] Nuxt Composition API
- [x] finish all features done

Demo: https://nuxt-realworld.vercel.app
Repo: https://github.com/devJang/nuxt-realworld

**Comment by adriatic** [comment]
I was planning to create the nuxt.js based front end - and then found this https://github.com/devJang/nuxt-realworld. @devJang - is this project finished? If not do you need any help?

**Comment by devJang** [comment]
> I was planning to create the nuxt.js based front end - and then found this https://github.com/devJang/nuxt-realworld. @devJang - is this project finished? If not do you need any help?

yes! this project(https://github.com/devJang/nuxt-realworld) finished to completed all feature

**Comment by adriatic** [comment]
Thank you - I will look for something else

**Comment by mvila** [comment]
Thanks, @devJang! 😄 

I added your Nuxt.js implementation in #600 and merged it to master.
