### ISSUE TITLE
Serverless+Typescript with AWS as the provider (Lambda, SSM, DynamoDB)

### ISSUE THREAD

**Issue by Roustalski** [gothinkster/realworld#219]
https://github.com/bakerstreet-industries/aws-realworld-starter
No EC2 instances required.

- [X] 🏁Fork the starter repo & post the link in this issue
- [X] 🎨 Create logo for repo & update issue status (@EricSimons)
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

**Comment by asahasrabuddhe** [comment]
What's the progress here?

**Comment by Roustalski** [comment]
Howdy. Been a busy season post-summer. Hoping to pick this back up towards the end of this month or next.

**Comment by asahasrabuddhe** [comment]
Thanks for your response. Please let me know if I can contribute to your effort.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
