### ISSUE TITLE
NativeScript (Angular)

### ISSUE THREAD

**Issue by nea** [gothinkster/realworld#221]
Hi

I created a [NativeScript](https://www.nativescript.org/) (Angular) mobile frontend implementation of Conduit. 

Go check out the source at the repository or the app on the [Google Play Store](https://play.google.com/store/apps/details?id=com.insanitydesign.nativescriptrealworldexampleapp&referrer=utm_source%3Dgithub%26utm_medium%3Dissue%26utm_content%3Drealworld). I released an open beta as I was only able to test it on the emulator and one device and am happy about any feedback and suggestions.

## Repository
https://github.com/nea/nativescript-realworld-example-app

## Status
* Conduit spec & API has been implemented
  * As there was no concrete reference, based on the Medium.com app and some other implementations some choices of design and functionality have been made to fit both, the spec and the Medium.com app
  * Settings dialog to connect to other/own backends
* Tested on Android Emulator and Device
  * An e2e test has been created to show the possibilities
* Translated to English and German
* Published to the Google PlayStore as open beta release

### Progress
- [X] 🏁 Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@EricSimons)
- [X] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [X] 🎉 Tag v1 release 
- [X] 🎉 Deploy to Google PlayStore
- [ ] 🎉 Deploy to Apple AppStore
- [ ] 🎉 Officially list it on the README!

## Notes
I am really no designer ^^' Most of the styling is done more from a programmer's art perspective and I am happy about suggestions how to improve the styling.

The app has been translated to EN and DE. Any other [translation](https://github.com/nea/nativescript-realworld-example-app/blob/master/app/i18n/en.default.json) is greatly welcomed.

Thanks a lot, and Cheers

**Comment by anishkny** [comment]
Was added to main README: https://github.com/gothinkster/realworld/blob/master/etc/mobile-repos.yaml
