### ISSUE TITLE
Crystal (Onyx)

### ISSUE THREAD

**Issue by vladfaust** [gothinkster/realworld#223]
Hello all, I've implemented [Crystal](https://crystal-lang.org/) version of Conduit and called it [Crystal World](https://github.com/vladfaust/crystalworld). ~~It has some issues to fix and then it's ready to go (as much as a Crystal application can be :sweat_smile:).~~

~~I haven't tested it with front-end implementations though (apart from Postman collection).~~
Included integration tests in the CI: https://travis-ci.org/vladfaust/crystalworld

I'm open to suggestions and maybe needed clarifications due to my [Curse of knowledge](https://en.wikipedia.org/wiki/Curse_of_knowledge). :smile: 

---

- [x] Fork the starter repo & post the link in this issue
- [x] Create logo for repo & update issue status (@EricSimons)
- [x] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] Tag v1 release and officially list it on the README!

**Comment by vladfaust** [comment]
CrystalWorld got [v0.1.0-ed](https://github.com/vladfaust/crystalworld/releases/tag/v0.1.0), RFC!

**Comment by anishkny** [comment]
Pinged [Crystal Gitter](https://gitter.im/crystal-lang/crystal) for RFC!

**Comment by vladfaust** [comment]
Updated to use with the [Onyx Framework](https://github.com/onyxframework) :tada:

**Comment by vladfaust** [comment]
So what's my next steps, @anishkny?

**Comment by anishkny** [comment]
LGTM. Created PR #348 @Cameron-C-Chapman
