### ISSUE TITLE
Vertx + Reactive + MongoDB

### ISSUE THREAD

**Issue by greyseal** [gothinkster/realworld#228]
An exemplary real-world application to showcase the awesomeness of [Vertx](https://vertx.io/).
I will start working on this soon. However, any help would be appreciated.

[Github](https://github.com/greyseal/vertx-realworld-example-app)

**Comment by shihuaguo** [comment]
have you started working on this?

**Comment by greyseal** [comment]
Yeas, I have started this project. Will commit initial version this weekend.

**Comment by greyseal** [comment]
I have added the initial code. Any help would be appreciated.

**Comment by shihuaguo** [comment]
i'm studing your vertx-boot project，looking forward to this project.

**Comment by AndierZ** [comment]
Thanks so much for putting it together. It looks like solid work. I'm starting to teach myself vert.x and full stack development in general. This is great material. Appreciate it.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
