### ISSUE TITLE
AngularFire, ReactFire, VueFire, etc

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#23]
We currently have a [Firebase + GCP backend](https://github.com/gothinkster/realworld/issues/21) in the works, but it would also be cool to create "backend-less" versions of Conduit using Firebase's JS libs.

A good strategy might be to fork our existing Angular/React/Vue etc RealWorld codebases, rip out all the API logic and replace it with Firebase methods.

Also, considering Firebase's data is non-relational, implementing the feed/following/liking functionality might be a bit tricky. So before we get started on any of these, I think it would be great to have one of the Firebase folks advise a standard data spec that all of these frontends could adhere to.

**Comment by EricSimons** [comment]
@davideast do you know of anyone in the Firebase/Angular community who might be interested in creating the AngularFire version of this? I'm thinking the other implementations could just mimic its database setup/implementation once completed 👍

**Comment by sebastiandg7** [comment]
@EricSimons Hey, I would like to take up on this: Firebase + Angular (AngularFire) + Nx.
