### ISSUE TITLE
Fullstack Golang (tgram)

### ISSUE THREAD

**Issue by recoilme** [gothinkster/realworld#234]
Work in progress here: https://github.com/recoilme/tgram

Based on golang/gin/slowpoke backend: https://github.com/recoilme/golang-gin-realworld-example-app

It will use Gin, Slowpoke and vanilla javascript

I have plans do it more close to "real world" then usually 
With the medium like editor, medium like looks and feel and so on. But i am not good web developer any help - welcome!

**Comment by recoilme** [comment]
<img width="652" alt="screen shot 2018-07-10 at 13 08 03" src="https://user-images.githubusercontent.com/417177/42503827-5c2c7ae2-8442-11e8-880e-890b4a08d1dd.png">

<img width="803" alt="screen shot 2018-07-10 at 13 09 26" src="https://user-images.githubusercontent.com/417177/42503877-86b83044-8442-11e8-9fb0-cf43b39dc41c.png">
First alpha (technical build) - may be available here:
http://tgr.am/

**Comment by recoilme** [comment]
Looks like finished, but i use another design and UI, not from realworld.io
I think my version is much more functional. More "real"
Demo: [http://tgr.am/](http://tgr.am/)

**Comment by recoilme** [comment]
Screenshots if my site will down:
User pages:
<img width="680" alt="screen shot 2018-07-17 at 19 21 36" src="https://user-images.githubusercontent.com/417177/42831331-bab351d0-89f6-11e8-9dca-477d0de987c1.png">
<img width="813" alt="screen shot 2018-07-17 at 19 23 24" src="https://user-images.githubusercontent.com/417177/42831403-e9b591b4-89f6-11e8-8cf7-a058596eb0aa.png">

**Comment by Cameron-C-Chapman** [comment]
@recoilme this looks really cool!

Does this implement the realworld spec though? This looks like a similar but different project, is the backend api the realworld api? If not I'm not sure we'd want to add it as a realworld project. We could add it as a community project possibly but the value of everyone adhering to the same specification is that every comparison is "apples to apples". This might be more valuable to the go community than the realworld community.

Thoughts? @anishkny

**Comment by recoilme** [comment]
@Cameron-C-Chapman Hello, thank you for your attention! I started this project as realworld app but now it totally different from backend to frontend. Typegram has the same functionality in many places. Anyway it may be interesting to  realworld community, i don't know
I published it in golang nuts, but with zero comments( 
https://groups.google.com/d/msg/golang-nuts/sR2YICtuEgM/uKhEgWyBBgAJ

**Comment by geromegrignon** [comment]
Hello,

Great work but as it doesn't follow the specs anymore, we won't add it on this repo.
