### ISSUE TITLE
hapi pal

### ISSUE THREAD

**Issue by devinivy** [gothinkster/realworld#237]
Working on a backend implementation using [hapi pal](https://hapipal.com/), a suite of tooling and methodologies for building nodejs web services with hapijs.  The model layer is based upon [Objection ORM](https://github.com/Vincit/objection.js).

Track progress here! https://github.com/devinivy/hapipal-realworld-example-app

- [x] Fork the starter repo & post the link in this issue
- [x] Create logo for repo & update issue status
- [x] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase
- [ ] Tag v1 release and officially list it on the README

**Comment by devinivy** [comment]
I still need to write the readme, but this is essentially ready for review.  Here's all you need to know to get started,
 - Deployment and configuration is contained in `server/`.  You must `cp server/.env-keep server/.env` then set an `APP_SECRET` in there, used for generating JWTs.
 - Application code is contained in `lib/`.
 - It runs under sqlite3, which is installed during `npm install`.
 - The database is keyed off of the `NODE_ENV`, and persisted to the filesystem at `.{env}.db` within the project's root directory.  So `NODE_ENV=production` is persisted to `.production.db`, `NODE_ENV=development` to `.development.db`, and a missing `NODE_ENV` to `.default.db`.
 - `npm test` runs tests and `npm start` runs the server.

**Comment by devinivy** [comment]
This really oughtta be good to go—I would love a review!  There is now a fairly extensive explainer in the readme: https://github.com/devinivy/hapipal-realworld-example-app

**Comment by Cameron-C-Chapman** [comment]
Trying to get to it soon @devinivy, sorry for the delay 😬The repo looks great, I just need to run it locally and take a look. I'll try to get to it this week at some point.

**Comment by devinivy** [comment]
No sweat at all—thanks for the update!

**Comment by anishkny** [comment]
@devinivy would you mind adding this to TravisCI? Thanks!

**Comment by devinivy** [comment]
@anishkny should be all set now 👌

**Comment by devinivy** [comment]
@anishkny @Cameron-C-Chapman is there any action I need to take here?

**Comment by anishkny** [comment]
I tried it out locally and looks good to me. Great work! @devinivy

**Comment by devinivy** [comment]
Cheers, and thanks for the review!
