### ISSUE TITLE
Enterprise Web Library fullstack

### ISSUE THREAD

**Issue by william-gross** [gothinkster/realworld#243]
This is a fullstack implementation using a built-in UI, so it looks different from the templates, but all functionality is there.

Repo: https://github.com/enduracode/ewl-realworld-example-app
Demo: http://ewl.enterpriseweblibrary.org/RealWorld
Blog post: http://enterpriseweblibrary.org/blog/2018/7/24/the-smallest-realworld-implementation

It would be great to have this listed on https://realworld.io/ in the Fullstack section. Is there anything I can do to help make this happen?

Thank you for creating RealWorld! It's the best "Rosetta Stone" web application that I've seen; it's small enough to implement in a few days, yet it manages to involve so many different pieces of functionality.

**Comment by william-gross** [comment]
@anishkny this framework is designed for rapid development of line-of-business applications. While it would technically be possible to use the RealWorld HTML templates and CSS, this would not be in the spirit of the framework and would likely double the size of the source code. Is there any chance you could list this in a new category, e.g. "Fullstack business application frameworks"?

**Comment by geromegrignon** [comment]
Hello,

The goal of the project is to help people to see how each solution works based on the same specs.
Having to double size the source code to fit the specs is precious information to evaluate a solution.

Even by adding a new category, it won't respect the current specs.

However we'll be happy to add it if changes occurs.
By the way we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
