### ISSUE TITLE
Go Clean Architecture

### ISSUE THREAD

**Issue by err0r500** [gothinkster/realworld#245]
Hey,
Another golang backend but using clean architecture : https://medium.com/@matthieujacquot/clean-architecture-in-golang-7ebafe4c70db

repo : https://github.com/err0r500/go-realworld-clean

**Comment by err0r500** [comment]
Hi,
I updated the repo, everything should be ok now. 
I'll improve the test coverage in the days to come.
If I have something more specific to do, tell me. 😀

**Comment by anishkny** [comment]
This looks very interesting indeed. Could you run the RW API tests by following instructions [here](https://github.com/gothinkster/realworld/tree/master/api#how-to-use-the-supplied-postman-configuration) to ensure it adheres? Thanks!

**Comment by err0r500** [comment]
Hi @anishkny !

Thanks a lot. I updated the repo in order to have the tests included (with the testing instructions).

About the postman collection : I just changed the order of some requests in order to have the POST requests before the GET/PUT and the DELETE at the end (because, obviously one can't get something that hasn't been created yet or that has already been deleted).

This way, the whole test suit passes, I hope its fine.

**Comment by err0r500** [comment]
Hey,
I improved the test coverage and discovered while testing with a frontend that articles without comments should return an empty array instead of a null (not covered in newman) along with a few other details of the same kind.
I played a bit with the elm frontend and everything seem to work fine now.
Tell me if it looks good to you :)
Best,

**Comment by err0r500** [comment]
Hi,
I don't see any progress in this issue, it's not listed in the main README, so I'm wondering : is something is missing ? What would be the next step ?
Best,

**Comment by err0r500** [comment]
hi ! 
Is there something missing ?
I tested it with the elm frontend without noticing any problem but if you found something, tell me and I'll try to get it fixed ASAP.
Best,

**Comment by err0r500** [comment]
Up?

**Comment by anishkny** [comment]
Hi @err0r500 sorry for the delay! Could you send a PR adding this to [etc/backend-repos.yaml](https://github.com/gothinkster/realworld/blob/master/etc/backend-repos.yaml)? Thanks!
