### ISSUE TITLE
Mframejs

### ISSUE THREAD

**Issue by vegarringdal** [gothinkster/realworld#246]
Made a sample with a framework I made last year
Was thinking I could submit it, but maybe having my own hobby project here isnt a good thing ?
Tried it it the chrome audit, did not do too bad, but maybe all others have not been updated lately
Its not bug free, but Ive had a lot of fun with it with fusebox bundler and stackblitz.

**Demo:**
https://mframejs.github.io/mframejs-sample-realworld/dist/

**Repo demo:**
https://github.com/mframejs/mframejs-sample-realworld

**Repo framework**
https://github.com/mframejs/mframejs

**Docs:**
https://mframejs.gitbook.io/docs/

**Stackblitz links:**
 [stackblitz](https://stackblitz.com/@vegarringdal)

**Comment by Cameron-C-Chapman** [comment]
@vegarringdal I think realworld is the perfect place to show off a framework you created 😄 

We'll work on getting it reviewed. If you could create a logo with the same dimensions as the other projects on the main readme that would be a big help.

**Comment by vegarringdal** [comment]
@Cameron-C-Chapman 

> We'll work on getting it reviewed.

Dont get scared, some parts might be weird :-)
Cant do all the fancy stuff the big frameworks can do.

>  If you could create a logo with the same dimensions as the other projects on the main readme that would be a big help.

fixed
also updated some parts

**Comment by vegarringdal** [comment]
Dunno if it matters, added it also to stackblitz (love that site)
https://stackblitz.com/edit/mframejs-real-world-v1
Only had to change my `require()` to `import()`, so thats was good.

Also found this a few days ago:
https://developers.google.com/web/tools/lighthouse/run
Made one test:
https://builder-dot-lighthouse-ci.appspot.com/report.1533756838239.html

**Comment by anishkny** [comment]
Hey @vegarringdal for some reason [your demo](https://mframejs.github.io/mframejs-realworld-example-app/dist/) fonts do not match the [React/Redux demo](https://react-redux.realworld.io/) and other demos. Could you take a look?

**Comment by vegarringdal** [comment]
@anishkny 
Thanks, I didnt notice this.
Im starting to get old, need glasses :-)

Updated the demo.

**Comment by vegarringdal** [comment]
I was trying to get "Accessibility" in lighthouse audit up.
https://builder-dot-lighthouse-ci.appspot.com/report.1533897942149.html

Getting errors:
> Background and foreground colors do not have a sufficient contrast ratio.

But to fix this the main css needs to be updated, is this something you guys are considering ?
This would help all realworld apps.
If I was good at CSS I would have suggested a fix, but CSS does not like me 😂

**Comment by vegarringdal** [comment]
Added service worker + misc
Now all of lighthouse audits are green :-)

Demo:
https://mframejs.github.io/mframejs-sample-realworld/dist/

Tested with this lighthouse test app:
https://developers.google.com/web/tools/lighthouse/run

**Comment by vegarringdal** [comment]
@Cameron-C-Chapman @anishkny 
Was there anything more I needed to do btw ?

**Comment by Cameron-C-Chapman** [comment]
@vegarringdal we just need to validate it works with the realworld backends and it adheres to the front end spec. I'm on vacation starting in a few hours and won't be able to take a look until probably next week. 

Sorry for the delay and please keep pinging us if you don't hear back soon.

**Comment by vegarringdal** [comment]
@Cameron-C-Chapman 
Thanks for the feedback, just wanted to know if you guys where waiting for me.
Hope you have a nice vacation  :-)

**Comment by Cameron-C-Chapman** [comment]
@vegarringdal is there something special I need to do to get the `manifest.json` file? I'm getting an error due to a missing file when I run watch or build.

I'm on node v.8.11.2.

```
$ node watch.js
[20:53:34] Starting 'default'
[20:53:34] Starting 'clean'
[20:53:34] Resolved 'clean' after 3ms
[20:53:34] Starting 'copy-manifest'
→Copy to dev/
Error: ENOENT: no such file or directory, stat '/Users/cameronchapman/Personal/mframejs-sample-realworld/manifest.json' 
```

**Comment by vegarringdal** [comment]
@Cameron-C-Chapman 
Lets hope everything goes well next time you get time.
Even took and tested it on my new "dev" unbuntu vmware image :-)

**Comment by vegarringdal** [comment]
Have some changes I want to do
Lets put this on hold for now until I get time to do it.
