### ISSUE TITLE
Zend Framework

### ISSUE THREAD

**Issue by unckleg** [gothinkster/realworld#247]
Hi! I'd like to implement the backend with **Zend 3 Framework**, if I find time 'll try to port it to **Zend expressive**.

Repo link is: [https://github.com/unckleg/realworld-zendframework](https://github.com/unckleg/realworld-zendframework)

Tomorrow 'll be first commit :) 
<hr>

- [x] Mirrored readme.md from the starter repo & post the link in this issue
- [x] Create logo for repo & update issue status
- [ ] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase
- [ ] Tag v1 release and officially list it on the README

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
