### ISSUE TITLE
Flutter Framework

### ISSUE THREAD

**Issue by lastlink** [gothinkster/realworld#250]
Another mobile ui framework. Flutter is owned by google.

**Comment by sluongng** [comment]
Very much interested in this as well.

**Comment by Cameron-C-Chapman** [comment]
I'm excited to see this one! Add details to this ticket as you make progress 😄

**Comment by mikaelmello** [comment]
I don't know the specs required for it to be feature here, but I really liked the way this app is structured:

https://github.com/jesusrp98/spacex-go

**Comment by anishkny** [comment]
Closing in favor of #312 which seems farther along. Please reopen/merge as necessary.
