### ISSUE TITLE
Migrate to OpenAPI 3

### ISSUE THREAD

**Issue by ciarancourtney** [gothinkster/realworld#256]
Any plans to migrate to generic spec? (not swagger)

**Comment by Cameron-C-Chapman** [comment]
Sorry for the super late reply @ciarancourtney 😬 

There are no plans to update the spec that have really progressed much.

We could include both specs and let the implementers choose what makes the most sense for their tooling, or just vote on one over the other and update the spec accordingly. As long as there aren't incompatibilities with the way the API is structured/implemented I don't see any issue with getting that definition out there.

If you'd like to explore this some more I say go for it. After all, it is Hacktober 😉

**Comment by Ryandaydev** [comment]
I ran the swagger.json through the mermade converter. The openapi.yml is attached. I confirmed it validates, but didn't verify otherwise.

[openapi.yml.txt](https://github.com/gothinkster/realworld/files/2699246/openapi.yml.txt)

**Comment by geromegrignon** [comment]
Merged
