### ISSUE TITLE
Mint

### ISSUE THREAD

**Issue by gdotdesign** [gothinkster/realworld#265]
I've implemented the realworld frontend in [Mint](https://www.mint-lang.com).

Mint is a language which compiles to JavaScript and it's also a framework which means that there are no third party dependencies other than the standard library.

Source: https://github.com/mint-lang/mint-realworld
Demo: https://realworld.mint-lang.com

There are a few difference to other implementations:
* since Mint has a built in way of styling HTML elements I wanted to showcase that, so the design of the application greatly differs from the original one
* the end result is also a Progressive Web App which is not included in the original spec (as far as I can tell)
* the routes are not using hash (/#/) but full URLs and paths are different also

It implements all of the functionality that the spec outlines.

I don't know if it qualifies as a proper frontend, but I though I would share it :slightly_smiling_face:

**Comment by anishkny** [comment]
@gdotdesign this is awesome. Although to get apples-to-apples comparison, could you make the styling similar to one of the official implementations (say [this one](https://react-redux.realworld.io/))?

You could always have an alternate URL that showcases the builtin styling. WDYT?

**Comment by gdotdesign** [comment]
It is possible to apply the same CSS and templates but it would require refactoring which I don't have time now.

The other option would be making it look like the original design using built in styles but it still would not be a fair comparison.

I'm OK if it's not listed as a proper frontend, I just was hoping that it would be listed somewhere :)

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
