### ISSUE TITLE
🖥 🔧 Aurelia

### ISSUE THREAD

**Issue by jadhavajay** [gothinkster/realworld#27]
# Current Status

- ### Codebase in progress:<br /> [jadhavajay/aurelia-realworld-example-app](https://github.com/jadhavajay/aurelia-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/aurelia](https://gitter.im/realworld-dev/aurelia)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

http://aurelia.io/

**Comment by EricSimons** [comment]
@EisenbergEffect do you know anyone who would be down to create the [RealWorld](https://github.com/gothinkster/realworld) app in Aurelia?

**Comment by EisenbergEffect** [comment]
We can check into it.

**Comment by EricSimons** [comment]
@jadhavajay just saw that you started on this! I updated issue status w/ a gitter room and here's a logo I created for your repo's readme:

![aurelia](https://cloud.githubusercontent.com/assets/556934/25449069/2e342c38-2a80-11e7-92e6-321c43d8e6d1.png)

**Comment by CalvinAllen** [comment]
This is a great idea! (saw it in the Aurelia Weekly)

I'm still learning Aurelia, but would love to help - as I am also trying to build a "RealWorld" enterprise application.

**Comment by ViktorDimitrievski** [comment]
Hello, 
I can try to help to build this app.

**Comment by jadhavajay** [comment]
@CalvinAllen & @ViktorDimitrievski Thanks for taking initiative. Please fork the [repo](https://github.com/jadhavajay/aurelia-realworld-example-app) and you can start submitting the PRs.

**Comment by EricSimons** [comment]
@CalvinAllen @ViktorDimitrievski @jadhavajay great to see this project moving forward! 🎉  Is there anything I can do to help?

**Comment by loaded02** [comment]
Hi @EricSimons. I have coded a conduit app in aurelia. It is complete and a pending PR for @jadhavajay  [fork.](https://github.com/jadhavajay/aurelia-realworld-example-app/pull/2) But somehow he isnt responding for 20 days now. In the gitter channel also nobody responds. I was looking forward to participate in this project. What should I do? Should I fork the starterkit myself?

**Comment by jadhavajay** [comment]
Hi @loaded02, your PR is merged. Sorry i missed your message on the gitter channel.

**Comment by EricSimons** [comment]
@jadhavajay @loaded02 is the functionality feature complete? If so, lmk and I'll move the repo to the main org and list it on the readme! Thanks so much for your awesome work guys!!

**Comment by loaded02** [comment]
@EricSimons imo it is complete. What do you think @jadhavajay ?

**Comment by jadhavajay** [comment]
@EricSimons @loaded02 UI wise things looks good to me, however looks like the "Sign In" and "Sign Up" is still pending.

**Comment by loaded02** [comment]
@jadhavajay My mistake. I removed the wrong file during refactoring. I created a new PR. Now it should be working.

**Comment by loaded02** [comment]
@jadhavajay whats the status of the project? Imo it is complete. Unfortunatley your not responding on gitter, so I give it here a try. Are you planning to move your repo and list it on the readme?

**Comment by EricSimons** [comment]
@jadhavajay is this repo good to go? Will create the official repo and list on the readme if so!

**Comment by fmonroe** [comment]
@EricSimons : Thanks for this great web site. I believe this repo is ready to be "moved to the main org and be listed on the readme".  That would be beneficial to people interested in Aurelia. Thanks.

**Comment by jadhavajay** [comment]
@EricSimons and @loaded02 - I have merged the PR - the sign-in and sign-up is working fine.

**Comment by jadhavajay** [comment]
@EricSimons I think this repo is good to go now. Please go ahead and create an official repo.

**Comment by loaded02** [comment]
@EricSimons how would you like to proceed with this issue?

**Comment by jadhavajay** [comment]
@EricSimons Let me know if there is anything needed from my side...

**Comment by EricSimons** [comment]
@jadhavajay @loaded02 hey guys! So sorry about my delay here- I'll get this added to the main readme first thing tomorrow morn 👍  amazing work on this!!

**Comment by EisenbergEffect** [comment]
Wow. Wow. Wow. And Super WOW! Great job to everyone who worked on this. I just had a look over all the code and ran the app on my machine. It looks great. This was not a small effort and I and the rest of the core team are very grateful for this work. I'd love to have a blog post to feature this group's work on the official Aurelia blog. Is anyone interested in writing that? We'd love to showcase you :)

**Comment by EricSimons** [comment]
This is now listed on the main readme! Thanks for taking the time to look over this codebase @EisenbergEffect and amazing job @jadhavajay & @loaded02!! Looking fwd to reading the blog post about it 🎉 ❤️

**Comment by loaded02** [comment]
[Blogpost](http://aurelia.io/blog/2018/04/04/aurelia-realworld-app) @ aurelia.io
