### ISSUE TITLE
Conduit.postman Environment File Missing for import

### ISSUE THREAD

**Issue by itsmeguru786** [gothinkster/realworld#271]
Hi,

There is mention to import in online tutorial for managing environments for https://raw.githubusercontent.com/gothinkster/realworld/master/api/Conduit.postman_environment.json but this is not available in the repo. 

Is this missing or the file name or repo path has changed?

**Comment by anishkny** [comment]
Which online tutorial are you referring to?

This file was recently removed as unnecessary: 8547f1da42c32ab3fe8f70f089adf12d00ff1aac

**Comment by itsmeguru786** [comment]
No probs. I created my own environment variable and is good.

**Comment by dtbradfield** [comment]
File still missing

**Comment by liamwaugh** [comment]
File is still missing

**Comment by HamzaMasood1** [comment]
File still missing.

**Comment by carballosa** [comment]
File is still missing. Please update the tutorial or add the file back

**Comment by oelsons** [comment]
File still missing
