### ISSUE TITLE
Clojure with Polylith architecture

### ISSUE THREAD

**Issue by furkan3ayraktar** [gothinkster/realworld#277]
A [Clojure](https://clojure.org) implementation with using [Polylith](https://polylith.gitbook.io/polylith/) architecture:

[https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app)

**Comment by furkan3ayraktar** [comment]
All tests are passing now. Here is a screenshot from tests:
<img width="1123" alt="screen shot 2018-10-02 at 7 34 23 pm" src="https://user-images.githubusercontent.com/3882707/46366443-5be7e000-c67b-11e8-8f41-cc79ede52f1e.png">

**Comment by anishkny** [comment]
Wow! This looks really well thought out! Since API tests are passing, you may want to consider adding them to CircleCI/local testing? 

Would you mind reviewing this @tengstrand and James Trunk?

cc: @Cameron-C-Chapman

**Comment by Misophistful** [comment]
Hi Anish, I'm not sure what you'd like us to review - the tests? We were sat next to Furkan when he ran them, so I can confirm that they're working. Adding the tests to CircleCI is a great idea, and Furkan will do that today.

**Comment by furkan3ayraktar** [comment]
@anishkny when can we add this one to the main Readme and close this issue?

**Comment by anishkny** [comment]
Hey @furkan3ayraktar it looks great to me. I didn't realize the authors of Polylith have reviewed the repo. I would like one more admin to take a look before adding.

**Comment by Cameron-C-Chapman** [comment]
Hi @furkan3ayraktar this looks awesome!

I went through the getting started instructions and ran into an issue.

`lein ring server-headless` tells me `ring is not a task`

and when I try to use 

`lein run` I get `No :main namespace specified in project.clj.`

I used the homebrew method of installing Leiningen, am I on a version that doesn't know about `ring` or do I need to be in a different directory other than the project root?

```
$ lein -v
Leiningen 2.8.1 on Java 1.8.0_172 Java HotSpot(TM) 64-Bit Server VM
```

**Comment by furkan3ayraktar** [comment]
Hi @Cameron-C-Chapman 

Did you try to run command ```lein ring server-headless``` under root folder of the project? This command needs to be run under ```environments/development``` folder.

Let me know if this makes it work.

**Comment by Cameron-C-Chapman** [comment]
That worked like a charm 😄 

I would suggest adding that information to the getting started instructions just so people who aren't familiar with the setup don't get tripped up. This looks like an awesome implementation with really thorough documentation, nice work!

#282 will add it to our list of backend implementations and it should show up in the README within the next couple of days (we have some automation that updates the README overnight).

If you don't see it show up soon just ping us and we'll force it through.

**Comment by Misophistful** [comment]
Thank you for adding this project to the list! 

Is there any chance of renaming it to "Clojure / Polylith"? Then it will match the naming pattern of the other projects.

**Comment by anishkny** [comment]
Sure. Done!
