### ISSUE TITLE
CircularJS

### ISSUE THREAD

**Issue by PitPik** [gothinkster/realworld#279]
Hi guys,
I created an [implementation](https://github.com/PitPik/circularjs/tree/master/conduit) of conduit with my framework called [CircularJS](https://github.com/PitPik/circularjs).
You can see [a demo](https://pitpik.github.io/circularjs/conduit/src).

This implementation is quite small and fast (~535 sloc implementation, 25KB including the framework and [marked.js](https://github.com/markedjs/marked)).

If I understood correctly, writing this issue should be the first step I have to make in order to get this project inspected by you guys. Is that correct?

Have fun checking it out =)
Cheers

**Comment by Cameron-C-Chapman** [comment]
Hi @PitPik 😄 

You're correct, this issue is how you get the process going. We'll take a look and work on getting it added to the README. 

Thanks for putting this together!

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
