### ISSUE TITLE
react-native (using rxjs)

### ISSUE THREAD

**Issue by pvinis** [gothinkster/realworld#280]
i noticed that the react native fork didnt finish, and i wanted to do one with rxjs anyway, so ill just do it here.
repo is here: https://github.com/pvinis/realworld-react-native-rxjs

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
