### ISSUE TITLE
Badges for completed repos?

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#281]
What does the community think about README badges for completed repos. Say:

[![RealWorld Backend](https://img.shields.io/badge/realworld-backend-%23783578.svg)](http://realworld.io)
[![RealWorld Frontend](https://img.shields.io/badge/realworld-frontend-%23783578.svg)](http://realworld.io)
[![RealWorld Mobile](https://img.shields.io/badge/realworld-mobile-%23783578.svg)](http://realworld.io)
[![RealWorld Fullstack](https://img.shields.io/badge/realworld-fullstack-%23783578.svg)](http://realworld.io)

The color is `#783578` which comes from the main README logo:

![media/realworld.png](https://raw.githubusercontent.com/gothinkster/realworld/master/media/realworld.png)

**Comment by Cameron-C-Chapman** [comment]
I think it looks awesome 👍

**Comment by dnikolovv** [comment]
Yep, looks great.

**Comment by anishkny** [comment]
Added badges to many completed repos.
