### ISSUE TITLE
It should be noticed that Postman(chorme webapp) may not work for test

### ISSUE THREAD

**Issue by Allianzcortex** [gothinkster/realworld#286]
When I run Postman collection manually, there was an error called **"pm is not defined"**

After searching the solution, I think  [/postman-scripts-pm-is-not-defined](https://stackoverflow.com/questions/46243745/postman-scripts-pm-is-not-defined) is reasonable. After using the postman standalone version, it actually works.

So it will be proper if we add a hint. And if you think we should do it, I will publish a PR soon. looking forward to your reply ~~

**Comment by Allianzcortex** [comment]
@anishkny How do you think 😭

**Comment by Cameron-C-Chapman** [comment]
Thanks for the info @Allianzcortex 😄 

I think Postman itself suggests that you update to the latest version so I think that general suggestion from Postman should be enough, not sure we need to add a specific note to the instructions.

I'm not necessarily against it though, just not sure it's really needed. Whatever @anishkny thinks works for me though 😄

**Comment by anishkny** [comment]
We could add a note recommending standalone Postman. @Allianzcortex do you have a fix to make it work in both standalone and webapp mode?

**Comment by Allianzcortex** [comment]
@anishkny actually no. the global variable is a problem. I can't find one way to distinguish between the standalone app and web extension app. based on [official announcement](http://blog.getpostman.com/2017/11/01/goodbye-postman-chrome-app/), they don't support chrome app one year ago. So I will close this issue and reopen it once someone meets the same problem.
