### ISSUE TITLE
Workshop FYI

### ISSUE THREAD

**Issue by kentcdodds** [gothinkster/realworld#3]
Just want to leave an FYI here that I've created a workshop based on the work in the node and react implementations. I've left "thanks" in several places. Just thought you'd like to know :)

Thank you!

https://git.io/testing-workshop

**Comment by EricSimons** [comment]
Thanks for doing that man, we really appreciate the shoutouts — you're more than welcome & I'm glad you found the project useful!

Btw I included a link to your repo [in our README](https://github.com/gothinkster/realworld#community-created-resources) so others can explore how you implemented TDD for the React/Node stack :)
