### ISSUE TITLE
Add PureScript + Halogen implementation

### ISSUE THREAD

**Issue by thomashoneyman** [gothinkster/realworld#303]
Hey folks,

I've put together [a RealWorld implementation using PureScript and its most popular UI library, Halogen](https://github.com/thomashoneyman/purescript-halogen-realworld). It includes an in-depth guide describing how to build production-quality applications with PureScript and the Halogen framework.

As you can see from the repository there's some enthusiasm around this implementation and we'd love to have it as an official part of the RealWorld project.

At this moment the application is a WIP, but I aim to wrap up the implementation in the next week or two and get additional technical reviews from the community completed by the end of December.

## More about PureScript & Halogen

[PureScript](http://www.purescript.org/) is a lovely purely-functional language that compiles to JavaScript and is used in production at several companies including Conde Nast, Awake Security, Lumi, SlamData, CitizenNet, Habito, CollegeVine, etc. [Halogen](https://github.com/slamdata/purescript-halogen) is a functional UI library for PureScript which uses a component-oriented architecture (similar to React).

**Comment by thomashoneyman** [comment]
This implementation has been completed and added to the official list of repositories in #317. Please let me know what else is necessary to get this merged. Thanks!

**Comment by anishkny** [comment]
I tried it out locally looks good! :tada:

It would be nice to add some CI (Travis/Circle/Azure/GH Actions). Also would be nice to add this badge to your README linking back to RW: [![RealWorld Frontend](https://img.shields.io/badge/realworld-frontend-%23783578.svg)](http://realworld.io)

**Comment by thomashoneyman** [comment]
Sure! I can take care of that. I've received feedback on a few different types of tests that folks would find illustrative and I plan to add those as well.

Thanks for taking a look!
