### ISSUE TITLE
Masonite

### ISSUE THREAD

**Issue by vaibhavmule** [gothinkster/realworld#304]
Hey,

I will be implementing the backend with [Masonite](https://github.com/MasoniteFramework/masonite). Masonite is the Modern And Developer Centric Python Web Framework.

Repo: https://github.com/vaibhavmule/masonite-realworld-example-app

**Comment by vaibhavmule** [comment]
@Cameron-C-Chapman just want to clarify for labels that it will be [backend](https://github.com/gothinkster/realworld/labels/backend) implementation not [frontend](https://github.com/gothinkster/realworld/labels/frontend).

**Comment by vaibhavmule** [comment]
@Cameron-C-Chapman I have worked on repo and ready and passed all the tests.

**Comment by anishkny** [comment]
@vaibhavmule could you add CI (Travis/Circle/Azure)?

**Comment by vaibhavmule** [comment]
Yes just updated the travis.yml.

**Comment by vaibhavmule** [comment]
@anishkny @Cameron-C-Chapman Just wanted to know, what can be done approved?

**Comment by anishkny** [comment]
@vaibhavmule this looks great! Could you run API tests against your backend to ensure it is compliant? preferably in Travis CI

https://github.com/gothinkster/realworld/tree/master/api

**Comment by vaibhavmule** [comment]
Yeah I could do that. Thanks.

**Comment by anishkny** [comment]
Basically you would need to spin up your backend, and then execute:

```
APIURL=http://localhost:8000/ run-api-tests.sh
```

(assuming port 8000)

See: https://github.com/gothinkster/realworld/blob/master/api/run-api-tests.sh
