### ISSUE TITLE
🗄🔧 Dotnet Core (C#)

### ISSUE THREAD

**Issue by abauzac** [gothinkster/realworld#31]
# Current Status

- ### Codebase in progress:<br /> [abauzac/realworld-netcore-kit](https://github.com/abauzac/realworld-netcore-kit)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/dotnet-core](https://gitter.im/realworld-dev/dotnet-core)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

Hello

If anyone's interested, I'm trying out a dotnet core backend fork. 
Can find it here : https://github.com/abauzac/realworld-netcore-kit

The architecture is based on a colleague's work ( https://github.com/renaudcalmont/aspnetcore-mongodb-sandbox ) but if anyone wants to give a hand, you're welcome :)

Thanks to the admin's project btw

**Comment by EricSimons** [comment]
@abauzac woot! 🎉

I just set up [the Gitter room](https://gitter.im/realworld-dev/dotnet-core) where we can do collaborator coordination and created a logo that you can use for the repo's readme:

![dotnet-logo](https://cloud.githubusercontent.com/assets/556934/25317095/c428e28a-2826-11e7-93bc-69f02fa284e3.png)

**Comment by abauzac** [comment]
Thanks, I think you mixed up the links to the github repos ;)

**Comment by EricSimons** [comment]
Oops! Just fixed it :)

**Comment by lilred** [comment]
As in #70, this probably deserves a mention of C# since there are other languages available on .NET Core (VB.NET, F#).

**Comment by adamhathcock** [comment]
I've started a more ASP.NET Core standard fork here: https://github.com/adamhathcock/realworld-aspnetcore-kit

I realize having competing fork isn't optimal but the deviations in the current one from the guidelines and direction of ASP.NET Core are too much to not show a different way.

**Comment by EricSimons** [comment]
@adamhathcock can you create a new issue for it as well then? :)


@lilred done :)

**Comment by Cameron-C-Chapman** [comment]
Hi @adamhathcock 😄Are you still working on this at all? We're trying to clean up some of our open issues. We could keep this open, close it out, or change the label from WIP to Seeking Engineers.

Any thoughts?

**Comment by lastlink** [comment]
Isn't this the repo? https://github.com/gothinkster/aspnetcore-realworld-example-app

**Comment by Cameron-C-Chapman** [comment]
Ya, @lastlink I think you're right. Thanks for pointing that out. I'll close this out then since it looks complete.

**Comment by adamhathcock** [comment]
Oops, sorry.   I didn't see this earlier.  I've been working and maintaining the repo :)
