### ISSUE TITLE
User impersonation?

### ISSUE THREAD

**Issue by cliffordh** [gothinkster/realworld#311]
Does the implementation of the Realworld backend prevent user impersonation? Meaning, does the application prevent an authenticated user from updating information in the system that belongs to a different user? If so, what is the mechanism behind this authorization?

**Comment by anishkny** [comment]
Yes. A RealWorld backend is expected to only allow updates to an authenticated user's own information (its kinda implicit in the API [here](https://github.com/gothinkster/realworld/tree/master/api#update-user)).

The specific mechanism is up to each individual backend implementation.

**Comment by cliffordh** [comment]
The Django implementation does not appear to implement object level permissions and is subject to a user impersonation on the API. I've opened an issue on the Django backend implementation:
https://github.com/gothinkster/django-realworld-example-app/issues/21

**Comment by anishkny** [comment]
@cliffordh good catch! Thanks for opening the issue on the Django repo.
