### ISSUE TITLE
Flutter

### ISSUE THREAD

**Issue by UkonnRa** [gothinkster/realworld#312]
I know #250 is already talk about flutter, but he doesn't give us a project to work with, so I wrote my version of Flutter App: https://github.com/CasterKKK/flutter_realworld_app, and I have finished all the features in the spec (I think)

Any PR or advice is great!

**Comment by meritonferati** [comment]
> I know #250 is already talk about flutter, but he doesn't give us a project to work with, so I wrote my version of Flutter App: https://github.com/CasterKKK/flutter_realworld_app, and I have finished all the features in the spec (I think)
> 
> Any PR or advice is great!

Thank you for your work. It looks great..

**Comment by lastlink** [comment]
I've done some pull requests to the repo, what is remaining for this to be closed? Great work btw @CasterKKK

**Comment by CasterKKK** [comment]
@anishkny well, in fact I don't know how to use CI very well, so it well take a very long time to add CI to this project, sorry

**Comment by CasterKKK** [comment]
@lastlink I merged your PRs so it your PRs and branchs closed. Did I do anything wrong? The wierd thing is why are not you on the contribution list...

**Comment by lastlink** [comment]
@CasterKKK you have to add users manually to have them on the contributor list. The way open-sourced projects work is that people can fork and do a pull request to the repository forked from. If I or someone else is a contributor then I can do direct pushes to the main repository. I do show up under [insights > contributors](https://github.com/CasterKKK/flutter_realworld_app/graphs/contributors) though.

**Comment by JankoLancer** [comment]
@CasterKKK I would like to contribute to this project.
Can you tell me what job is left to be done?

**Comment by CasterKKK** [comment]
@JankoLancer Thanks for helping, you can find anything you are interested in. For example, the comment part is missing, and testing is prefered

**Comment by satvikpendem** [comment]
Can this be put on the main page instead of as a work in progress as it seems to be finished? Or am I mistaken and there's still work to be done?

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
