### ISSUE TITLE
Imba

### ISSUE THREAD

**Issue by cartonalexandre** [gothinkster/realworld#314]
I am going to start building the Realworld application using [Imba](http://imba.io/).

`Imba treats DOM elements as a first-class citizens. These elements are compiled to an inline dom, which is an `[order of magnitude faster](https://somebee.github.io/dom-reconciler-bench/index.html)` than todays virtual dom implementations.`

The project repository : [imba-realworld-example-app](https://github.com/cartonalexandre/imba-realworld-example-app)

### Work in progress

- fork the realworld repository
- create README
- develop the application

Feel free to help me 😃

**Comment by cartonalexandre** [comment]
@anishkny Hi Anish, I just finish implementation.
I don't know how can I host it to have an online demo

**Comment by anishkny** [comment]
Looks great. Couple of notes:

1. I noticed that the profile pic in top navbar is too big when logged in. Could you fix that?
1. Also, you can probably exclude `dist` folder from the repo as a best practice (just add it to `.gitignore` file).

For a demo, you have a few options:

1. [Netlify](https://www.netlify.com/docs/continuous-deployment/)
1. [GitHub Pages](https://pages.github.com)

We can discuss over at your repo...

Great work! 🎉🎉🎉

**Comment by cartonalexandre** [comment]
Thanks for your feedback, issue is fixed.
I think I can't ignore dist because dist/index.html isn't generated from another folder.
I added demo link on readme

**Comment by anishkny** [comment]
Thanks for adding! Please send a PR adding your project to [`etc/frontend-repos.yaml`](https://github.com/gothinkster/realworld/blob/master/etc/frontend-repos.yaml)

One more thing that is very useful to people who want to learn is adding a CI build for your repo - it also ensures high quality going forward. Would you be able to setup say TravisCI for building your project?
