### ISSUE TITLE
demo.realworld.io is down

### ISSUE THREAD

**Issue by segmentationfaulter** [gothinkster/realworld#315]

**Comment by anishkny** [comment]
Working for me. Any details you can provide? Screenshot, console, network traffic?

**Comment by gagarine** [comment]
![screenshot 2018-12-27 at 16 40 45](https://user-images.githubusercontent.com/164074/50485585-2fcbc900-09f6-11e9-86d4-0f9021982c89.png)

**Comment by cllns** [comment]
I, too, am seeing this for `demo.realworld.io`:
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/632942/50603586-3a63e380-0e78-11e9-985f-7cd8635aacd7.png">

**Comment by anishkny** [comment]
My observation just now:

* http://demo.realworld.io/ - Works fine
* https://react-redux.realworld.io - **Error 522** 

@EricSimons @apai4 could someone take a look please? Thanks!

**Comment by cllns** [comment]
@anishkny @EricSimons @apai4 Ah, so HTTPS is causing a timeout with both links and HTTP works fine for both links.

**Comment by Cronan** [comment]
Me too, for https://demo.realworld.io

![image](https://user-images.githubusercontent.com/777435/50962876-1715e580-14c3-11e9-84b7-4f1b3578462f.png)

**Comment by apai4** [comment]
Sorry about this! HTTPS access should be restored now.

**Comment by anishkny** [comment]
Verified. Thanks @apai4!
