### ISSUE TITLE
Kotlin + http4k + exposed

### ISSUE THREAD

**Issue by alisabzevari** [gothinkster/realworld#326]
Hi all,

I've implemented the [realworld backend](https://github.com/alisabzevari/kotlin-http4k-realworld-example-app) in [http4k framework](https://github.com/http4k/http4k). At the time of creating this issue, it passes the postman collection tests but there are some cleanup tasks left for me (or anyone who like to jump and improve it) in the project.

Some facts about this implementation:

* Written in kotlin language and using a pure kotlin framework.
* Http4k authors have reviewed the project in early stages of implementation.
* It has unit tests AND integration tests. Though the coverage is not 100%.

---

- [x] Fork the starter repo & post the link in this issue
- [x] Create logo for repo & update issue status (@EricSimons)
- [x] Implement all of Conduit's functionality per the spec & API
- [ ] Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] Tag v1 release and officially list it on the README!

**Comment by Cameron-C-Chapman** [comment]
Awesome @alisabzevari! Let us know when it's ready for review 😄

**Comment by alisabzevari** [comment]
Hey @Cameron-C-Chapman,

The Repository is ready for review.

**Comment by anishkny** [comment]
@alisabzevari great! It looks like you have an `azure-pipelines.yml` file - can you link to the Build page on Pipelines? That would be helpful to look at.

**Comment by alisabzevari** [comment]
I added the pipeline badge to the readme.

**Comment by alisabzevari** [comment]
Hey, any news regarding this?

**Comment by anishkny** [comment]
Hey sorry for the delay. Looks like no builds were found for the pipeline, have you run it in CI?

[![Build Status](https://dev.azure.com/alisabzevari/kotlin-http4k-realworld-example-app/_apis/build/status/alisabzevari.kotlin-http4k-realworld-example-app?branchName=master)](https://dev.azure.com/alisabzevari/kotlin-http4k-realworld-example-app/_build/latest?definitionId=1&branchName=master)

**Comment by alisabzevari** [comment]
I think Azure Pipelines does not keep the history of builds for a long time. Since the project didn't have activity recently, the history is deleted.
I triggered the build so you can see the results now.

**Comment by alisabzevari** [comment]
Hi, any news regarding the review of this? Is there something blocking this project to be added to the list?

**Comment by anishkny** [comment]
Sorry for the delay - should be added soon.
