### ISSUE TITLE
Kotlin + Javalin + Exposed

### ISSUE THREAD

**Issue by Rudge** [gothinkster/realworld#332]
Hi guys, I finished the real world example with [Javalin framework](https://github.com/Rudge/kotlin-javalin-realworld-example-app).

Could you review and tell me if it's ok to put in your repo, please?

**Comment by anishkny** [comment]
Sweet. I see that you added TravisCI and all API level tests [pass](https://travis-ci.org/Rudge/kotlin-javalin-realworld-example-app/jobs/482159480#L488)!

@Cameron-C-Chapman want to take a look at this one?

**Comment by Cameron-C-Chapman** [comment]
This looks awesome @Rudge!

Everything looked good but I did notice that the tests run on build and without the context you supply in the run-api-tests.sh script all the tests during the build fail.

**Comment by Rudge** [comment]
@Cameron-C-Chapman What do you suggest to update? I didn't find other solution.

**Comment by Cameron-C-Chapman** [comment]
@Rudge your project has been added to the readme, it looks great!

I assume there's a way to set the integration tests to not run on every build. I don't have any kotlin experience so I'm not sure but there should be a way to tell the build to not run those tests.

**Comment by Rudge** [comment]
@Cameron-C-Chapman Thanks! Yes, I Know. I just didn't understand the context of execute tests in build. Now I understood, I will split the steps on the Travis.
