### ISSUE TITLE
React + NextJS

### ISSUE THREAD

**Issue by vincentntang** [gothinkster/realworld#336]
This would be nice to have. I can work on it if necessary.

Let me know your thoughts here

**Comment by anishkny** [comment]
@vincentntang go for it! Please follow instructions [here](https://github.com/gothinkster/realworld#create-a-new-stack) and link back your repo in this thread. 

FWIW, I have been working on a [Nuxt](https://github.com/gothinkster/realworld/issues/218) FE implementation - which I need to get back to. Nuxt is to Vue what Next is to React.

**Comment by vincentntang** [comment]
Would it matter if I used a state management library? Or just pure react+nextjS?

**Comment by anishkny** [comment]
Whatever is the "best practice" recommendation of the Next.js community + what makes sense for RealWorld I suppose. No hard & fast rules. e.g. our #1 FE repo is React+Redux so no worries.

**Comment by vincentntang** [comment]
NextJS recommends either GraphQL or Redux implementation according to FAQ. https://nextjs.org/docs#faq

I am going to do a react/redux/nextJS implementation.

Repo in progress
https://github.com/vincentntang/realworld-react-redux-nextJS

**Comment by danichim** [comment]
This is done already ?

**Comment by danichim** [comment]
This is done already @vincentntang  @anishkny  ?

**Comment by reck1ess** [comment]
@anishkny  @danichim 

The issue doesn't seem to close for about a year, I have implemented the Next.js project.

I made a pull request #469 (Adding Next.js front end repo)

Thank you for checking.. 🙏

**Comment by vincentntang** [comment]
My priorities have shifted and I am no longer working on this react + nextJs + redux implementation

**Comment by anishkny** [comment]
Resurrected by @reck1ess 

Demo: https://next-realworld-example-app.now.sh/
Repo https://github.com/reck1ess/next-realworld-example-app
