### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by jho406** [gothinkster/realworld#337]
Hey all,
I'm interested in adding an implementation for PJAX, for example: [Turbolinks](https://github.com/turbolinks/turbolinks). However, the conduit specs expect the implementation to be a stereotypical SPA stack consisting of a backend providing an API to a frontend. Also, the requirement for JWT may not apply for PJAX apps, they're usually all just simple sessions. 

I think it's valuable to add PJAX apps (intercoolerjs, turbolinks, pjax etc) to the mix. Does anyone have any recommendations or thoughts on this?

**Comment by anishkny** [comment]
Hi @jho406, we do have a section called [Fullstack](https://github.com/gothinkster/realworld#fullstack) which may be relevant for this - even though we don't yet have a full implementation - hey you could be the first!.

I don't think we would need to enforce JWT for fullstack implementations.

**Comment by jho406** [comment]
Hey, that's great! thanks @anishkny

**Comment by jacobstern** [comment]
FYI I've implemented Turbolinks for GET requests in my server-rendered app here: https://github.com/jacobstern/typescript-handlebars-realworld. However the Turbolinks feature is mostly incidental and you could definitely go further with it in a Turbolinks-focused implementation, e.g. enabling Turbolinks for forms, page transitions, Rails integration. Nice to see I'm not alone in "rediscovering" server-rendered app techniques in 2019 (FWIW I was mostly inspired by work by the Phoenix framework team).

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
