### ISSUE TITLE
Feathers

### ISSUE THREAD

**Issue by randyscotsmithey** [gothinkster/realworld#339]
Hi,

I've created a [Feathers](https://feathersjs.com/) backend implementation at: https://github.com/randyscotsmithey/feathers-realworld-example-app.git.
This implementation depends on Node, Express, and MongoDB.

Everything works with the Postman collection and I've tested with the Elm frontend as well.

Includes a test suite with some tests implemented and others just stubbed out.

**Comment by anishkny** [comment]
This looks awesome @randyscotsmithey I tried it out locally but having some issues:

```
npm i
docker run -p 27017:27017 mongo &
export MONGODB_FEATHERS_REALWORLD=mongodb://mongo:27017
npm start


info: mongodb://mongo:27017
info: Feathers application started on http://localhost:3030
error: Unhandled Rejection at: Promise  {"meta":[{},{"name":"MongoNetworkError","errorLabels":["TransientTransactionError"]}]}
```

And the API does not return (e.g. http://localhost:3030/api/articles), any ideas how to make this work?

Also, it would be great if you could setup some cloud CI service (Travis/Circle/Azure)!

**Comment by randyscotsmithey** [comment]
Hi @anishkny, 
Thanks for looking at this.
Try changing the export to:
export MONGODB_FEATHERS_REALWORLD=mongodb://127.0.0.1:27017/testdb
(where 'testdb' will be the database name and can actually be anything you want)
That seems to do the trick for connecting to the docker mongoDB.
Also, I added  a .travis.yml file and that seems to be working now, but Travis is new to me.

**Comment by anishkny** [comment]
Yup worked for me. Sent a PR with new logo and some badges. Great work!

LGTM @Cameron-C-Chapman

**Comment by Cameron-C-Chapman** [comment]
This has been added to the README. Nice work @randyscotsmithey!
