### ISSUE TITLE
Are there some validation specs somewhere?

### ISSUE THREAD

**Issue by electrotype** [gothinkster/realworld#340]
For example, I see some implementations that validate that a password must be at least 8 characters... Is it defined somewhere?

What about "this username/email is already taken" during a registration request: are there some tests for those kind of stuff?

**Comment by anishkny** [comment]
@electrotype we have some Postman collection based backend API tests [here](https://github.com/gothinkster/realworld/tree/master/api) which cover most of the basic "P0" scenarios.

We did not want to go too deep into these validations - ideally an implementation should be what a Minimum Viable Product (MVP) would look like using any particular stack.
