### ISSUE TITLE
Spincast Framework

### ISSUE THREAD

**Issue by spincast** [gothinkster/realworld#341]
Hello!

Here's a backend implementation using [Spincast](https://www.spincast.org), a Java framework:

https://github.com/spincast/spincast-realworld

The implementation is completed.

**Comment by anishkny** [comment]
Awesome! I was able to get it working locally and Postman tests pass.

I noticed that `varia/run-api-tests.sh` adds the `--insecure` option to `newman`. Any idea why this is required.

Also it would be great if some cloud CI could be setup e.g. TravisCI/CircleCI/Azure Pipelines. It really helps everyone get a reference run of the stack - although not strictly required.

LGTM @Cameron-C-Chapman

**Comment by anishkny** [comment]
PS: Feel free to tweak the default RealWorld logo to include the Spincast logo - something like [this](https://raw.githubusercontent.com/gothinkster/node-express-realworld-example-app/master/project-logo.png).

**Comment by electrotype** [comment]
> Awesome! I was able to get it working locally and Postman tests pass.
All right!

> I noticed that `varia/run-api-tests.sh` adds the `--insecure` option to `newman`. Any idea why this is required.

It is required because the API is HTTP**S** using a self-signed certificate! Of course in production this would be a Let's Encrypt certificate or another real one.

> Also it would be great if some cloud CI could be setup e.g. TravisCI/CircleCI/Azure Pipelines. It really helps everyone get a reference run of the stack - although not strictly required.

I'll see what I can do, thanks for the suggestion.

**Comment by electrotype** [comment]
("spincast" and "electrotype" accounts are both mine)

**Comment by electrotype** [comment]
> 
> 
> PS: Feel free to tweak the default RealWorld logo to include the Spincast logo - something like [this](https://raw.githubusercontent.com/gothinkster/node-express-realworld-example-app/master/project-logo.png).

Done!

**Comment by electrotype** [comment]
> Also it would be great if some cloud CI could be setup e.g. TravisCI/CircleCI/Azure Pipelines. It really helps everyone get a reference run of the stack - although not strictly required.

Also done!

**Comment by Cameron-C-Chapman** [comment]
Spincast has been added and is on the README. Awesome job @spincast 😄
