### ISSUE TITLE
Real-World Comparison of Front-End Frameworks with Benchmarks 2019

### ISSUE THREAD

**Issue by jacekschae** [gothinkster/realworld#342]
Hey @anishkny
I'm working on a 2019 updae of the [Real-World Comparison of Front-End Frameworks with Benchmarks](https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-2018-update-e5760fb4a962) article and was wondering if there are any frameworks that should be added to the home page? 

Currently there is 17 so if you have anything else in the backlog would be great to include as much as we can.

Thanks, Jacek

**Comment by anishkny** [comment]
Sweet! I am aware of only one FE framework in review (finished, but not added):

* Stencil ([Repo](https://github.com/hcavalieri/stencil-realworld-app), Issue #325)

Query for future reference: https://github.com/gothinkster/realworld/issues?utf8=✓&q=is%3Aissue+is%3Aopen+label%3A%22ready+to+be+added%22+label%3Afrontend

Do you want to leave this issue open for tracking or okay to close out?

**Comment by jacekschae** [comment]
Great, thanks for letting me know. Will do PR when the articles is published.
