### ISSUE TITLE
Akka HTTP

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#345]
Repo in progress: https://github.com/1984weed/akka-http-realworld-example

**Comment by anishkny** [comment]
@ 1984weed lets use this issue to track progress. Also, sent out a logo for Akka HTTP impl to your repo. Good luck!

**Comment by 1984weed** [comment]
I left only some refactorings

**Comment by 1984weed** [comment]
@anishkny 
I just completed the functionality. 
https://github.com/1984weed/akka-http-realworld-example
How should I do next?

**Comment by anishkny** [comment]
Looks great! Could you fix failing build: [![Build Status](https://travis-ci.org/1984weed/akka-http-realworld-example.svg?branch=master)](https://travis-ci.org/1984weed/akka-http-realworld-example)

**Comment by 1984weed** [comment]
Oh. Sorry. I made a mistake. 

I fixed it. @anishkny 

Thanks 🙇

**Comment by 1984weed** [comment]
How do I have to do to go to the next step?

**Comment by anishkny** [comment]
@1984weed to ensure API correctness, could you run tests defined here against your backend in CI: https://github.com/gothinkster/realworld/tree/master/api

**Comment by 1984weed** [comment]
Thanks. I just added the API test to CI !! 
https://github.com/1984weed/akka-http-realworld-example/blob/9824fc701d1476eae2b389d2410881af1577b147/.travis.yml

Is it OK?

**Comment by anishkny** [comment]
Great work. LGTM PTAL @Cameron-C-Chapman
