### ISSUE TITLE
Actix

### ISSUE THREAD

**Issue by fairingrey** [gothinkster/realworld#352]
Hey all. I'm currently working on an Actix implementation for the realworld backend API spec. It's located [here](https://github.com/fairingrey/actix-realworld-example-app).

You can find more information about actix at their website [here](https://actix.rs/). It's one of the fastest frameworks available right now as shown on [TechEmpower benchmarks](https://www.techempower.com/benchmarks/#section=data-r17&hw=ph&test=update), and it benefits from being relatively high-level and extensible with a number of other crates.

I also believe it would be much easier to grok and extend than the [current Rust implementation provided](https://github.com/gothinkster/rust-realworld-example-app).

This Actix implementation doesn't solely use actix, of course. In my [Cargo.toml](https://github.com/fairingrey/actix-realworld-example-app/blob/master/Cargo.toml) file I'm using a number of robust and community-trusted crates to provide more features and functionality.

Posting it here for exposure. If anyone would like to take a look and/or help out, that'd be great, as currently it needs to be reviewed. I think it'd also make pretty decent reference material for someone unfamiliar with the actix framework or Rust in general.

Thanks!

**Comment by fairingrey** [comment]
I've finally finished all the logic for this application and all the endpoints should work as intended, so I suppose the next step now is to put it in front of other Rust developers and get a sense of where things could be improved.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
