### ISSUE TITLE
Lucky

### ISSUE THREAD

**Issue by HarrisonB** [gothinkster/realworld#353]
Hi! Posting this from mobile so apologies if this isn’t the correct formatting.

I’m currently working on a backend implementation of the spec for the [Lucky framework](https://luckyframework.org). It’s quite early-stage, but I thought I might as well post an issue here to share.

The repo is located here: https://github.com/HarrisonB/lucky-realworld.

**Comment by Cameron-C-Chapman** [comment]
Hi @HarrisonB 👋 Will this be a front-end or back-end implementation?

**Comment by HarrisonB** [comment]
Hi @Cameron-C-Chapman 😄 This will be a back-end implementation.

**Comment by Cameron-C-Chapman** [comment]
Perfect, can't wait to take a look!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
