### ISSUE TITLE
Symfony 4 with API Platform

### ISSUE THREAD

**Issue by mpiotrowski97** [gothinkster/realworld#354]
Hi! I know that there is the symfony repository created but I would like to make the symfony realworld example in more classy way. I will use API platform package which makes api building more fun and easy. My repo: https://github.com/MakeleAndzelo/symfony-realworld-example-app

**Comment by MakeleAndzelo** [comment]
Can I use logo from the old symfony repo?

**Comment by parijke** [comment]
Still in development?

**Comment by MakeleAndzelo** [comment]
Yes, it is. For now i don't have enough time for this.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
