### ISSUE TITLE
Backend implementation in JEE and Thorntail

### ISSUE THREAD

**Issue by nikospara** [gothinkster/realworld#356]
Hello,

This is an implementation of the Realworld backend in JEE (Java EE, Jakarta EE these days) and [Thorntail](https://thorntail.io/).

Implementation is done I guess:
- Passes the API tests
- Works with the React frontend

Repo: https://github.com/nikospara/jee-thorntail-realworld-example-app

**Comment by anishkny** [comment]
Wow that's great. Do you think you could add TravisCI or similar cloud CI for build/test?

**Comment by nikospara** [comment]
@anishkny Sure!

**Comment by nikospara** [comment]
@anishkny Done, Travis+SonarCloud

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
