### ISSUE TITLE
What do the columns in the Readme with 🥇 🥈 and 🥉 mean? 

### ISSUE THREAD

**Issue by mansona** [gothinkster/realworld#358]
Hi folks 👋 

I'm looking at the readme and I don't fully understand the meaning of the "gold silver and bronze" columns in the table of frontends 🤔 

![Screenshot 2019-03-27 at 13 52 14](https://user-images.githubusercontent.com/594890/55081711-48508b80-5098-11e9-8052-7b430e5ef093.png)

I guess my question is: why are React and Vue in the 🥇gold column and Angular in the second column? 

I know it says "Sorted by popularity on Thu Mar 14 2019" but then why is Angular not in the 🥇 gold column?

**Comment by Guttz** [comment]
The medals are only for the first three positions and to show the order/arrangement. So actually, in the image Vue is the 4th, React/MobX is the 5th, AngularJS 6th and so on. 

Angular is second most stared repo from all of them after React.

**Comment by Alonski** [comment]
@Guttz That is pretty confusing 😅 I am with @mansona here. Maybe this 3 should have some margin between them and the rest?

**Comment by Cameron-C-Chapman** [comment]
We're just leveraging Github flavored markdown tables here, not sure how much style customization we can do.

Maybe we could separate that first row out, or maybe someone wants to tackle a static gh-pages site?

**Comment by Alonski** [comment]
@Cameron-C-Chapman Maybe we can create RealWorld Static Sites to showcase the RealWorld Readme 😅

**Comment by Guttz** [comment]
Yes, I also agree with you and got confused for some days @Alonski @mansona.

I actually think the best option is just to remove them, by default people would understand that it's sorted by popularity as it's also written on top of the table. 

Ps: One more idea that the medals can give is that some repos are better built than others, which is also not really the goal of RealWorld

**Comment by mansona** [comment]
Oh wow, yea that is very confusing 😂 we should change that pretty quickly! Is there any particular reason why it needs to be a table? I think it will always be confusing unless it's literally numbered in each cell 🙈 

On another note, I think it is 100% possible to come up with some sort of scoring system for the RealWorld apps 🤔 even something basic. We have a whole ecosystem of this in the Ember world for Ember addons on [Ember Observer](https://www.emberobserver.com/). And you can see more information on [this 5 mins talk from Katie Gengler](https://www.youtube.com/watch?v=f_44WXjQ9CI)

I don't even mean anything crazy but something like accessibility might be a great metric to include in a scoring system 👍

**Comment by camaulay** [comment]
The medal headers were confusing for me too, this makes more sense:

![realworld-app-ranking](https://user-images.githubusercontent.com/8944214/63661750-f48acf80-c7fa-11e9-92b9-9985dc508e8c.jpg)

**Comment by Alonski** [comment]
Can this be thought through again? People are still getting confused by this 😕

**Comment by joskoanicic** [comment]
Could site loading (performance) metrics be added to the info? Something like https://hnpwa.com/ does but without the progressive web app part. 

So that it wouldn't just be a popularity contest.

**Comment by mansona** [comment]
@joskoanicic I think that's a great idea. If there was agreement that this was something that realworld was open to I would be happy to help set it up 👍

**Comment by Alonski** [comment]
That's a great idea @joskoanicic !

**Comment by joskoanicic** [comment]
For start we have this:

https://www.freecodecamp.org/news/a-realworld-comparison-of-front-end-frameworks-with-benchmarks-2019-update-4be0d3c78075/

and 

https://medium.com/dailyjs/a-realworld-comparison-of-front-end-frameworks-2020-4e50655fe4c1

Looking at the responses, I think adding performance metrics would incentivize the authors and/or community to optimize certain aspects of the submitted solutions And I think that is a net benefit in the end, as new developers that will be looking at code to learn something will not just look at something that is written to pass the specification but had performance in mind also.

**Comment by geromegrignon** [comment]
As we plan to remove the list of implementations from the current Readme to an external website (https://codebase.show/projects/realworld) which sorts implementations based on Github Stars, this issue is not relevant anymore.

**Comment by mansona** [comment]
I opened a "feature request" in the new project to discuss the other aspects that were brought up in this thread 👍

**Comment by MikaMalloc** [comment]
Can you stop sending md this  please ??
