### ISSUE TITLE
Angular Universal

### ISSUE THREAD

**Issue by sanketmaru** [gothinkster/realworld#359]
Is there a real world example for Angular Universal In Progress or available ? 
My thought is to make Sign in, Sign up, Homepage routes render server side. 

With this example it would make understanding clear of client side vs server side with the routes implementation. 
If it is not available i can start on this. 
Thoughts ?

**Comment by sanketmaru** [comment]
Any thoughts on this if this can be helpful ? I have started here by converting existing angular example https://github.com/sanketmaru/angular-realworld-universal-example-app

**Comment by Cameron-C-Chapman** [comment]
Hi @sanketmaru 👋 I don't see any Angular Universal implementations in progress. I'll tag this repo as a WIP in case anyone wants to join you.

**Comment by sanketmaru** [comment]
Hi @Cameron-C-Chapman ,
The work for creating Universal app is complete. I have converted the existing Angular 7 app to Universal. Its functional. 

Comparison of the changes can be seen here. 
https://github.com/gothinkster/angular-realworld-example-app/compare/master...sanketmaru:master

Let me know if i would need to make any changes to this repo to include the Universal in the documentation.

**Comment by anishkny** [comment]
@sanketmaru great work! Could you update the `README.md` and update/remove all references to gothinkster's angular. The ones I see are:

* Live edit, Learn to recrete, Demo, Travis build badge, How it works, Getting started

Thanks!

**Comment by sanketmaru** [comment]
@anishkny I have updated the README.md. 
Thanks.

**Comment by anishkny** [comment]
Works great on my end! Kudos. Some (optional) suggested next steps:

1. Add CI (Travis/Circle/Azure)
1. Deploy demo (Netlify/Surge.sh)

cc: @Cameron-C-Chapman

**Comment by FabiK97** [comment]
@sanketmaru What happened with the repo?

**Comment by sanketmaru** [comment]
@FabiK97 I accidentally deleted the repository it seems. Unfortunately locally also got deleted.
I have contacted Github Support if my repository can be restored.

**Comment by sanketmaru** [comment]
Somehow, repository cant be recovered. Need to re-write the Universal Example i guess.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
