### ISSUE TITLE
Vue + TypeScript

### ISSUE THREAD

**Issue by Vallista** [gothinkster/realworld#360]
Front-end Real World Demo implementation using Vue + TypeScript https://github.com/Vallista/realworld-vue-typescript

please add realworld markdown

**Comment by anishkny** [comment]
Great job so far! Do you think you could look at a few things:

1. Could not add comments when I tried it out, also it shows the wrong comment author profile pic in comment box
1. Could you try making a logo staring from [this one](https://github.com/gothinkster/realworld/blob/master/media/realworld-logo.png)
1. Add some CI (Travis/Circle/Azure) for builds

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
