### ISSUE TITLE
Scala + Finch

### ISSUE THREAD

**Issue by doriancodes** [gothinkster/realworld#364]
Backend Real World Demo implementation using [Scala](https://scala-lang.org/) and [Finch](http://finagle.github.io/finch/): https://github.com/alodavi/scala-finch-realworld-app

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
