### ISSUE TITLE
Flutter(BLoC)

### ISSUE THREAD

**Issue by daniel-lucas-silva** [gothinkster/realworld#365]
Codebase (in progress):
https://github.com/daniel-lucas-silva/flutter_realworld_example_app

Todo:
 - [x] 🏁Fork the starter repo & post the link in this issue
 - [x] 🎨 Create logo for repo & update issue status (@EricSimons, @Cameron-C-Chapman)
 - [ ] 🔨 Implement all of Conduit's functionality per the spec & API
 - [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
 - [ ] 🎉 Tag v1 release and officially list it on the README!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
