### ISSUE TITLE
Fullstack TypeScript + Express + Handlebars app

### ISSUE THREAD

**Issue by jacobstern** [gothinkster/realworld#367]
Hi RealWorld maintainers,

I made [a fullstack RealWorld implementation](https://github.com/jacobstern/typescript-handlebars-realworld) and thought I would try and get it featured in the main repo. It's an "old school" server-rendered app with minimal client-side JavaScript, augmented with [Turbolinks](https://github.com/turbolinks/turbolinks) for faster page loads. The app is up to spec as far as I can tell, and you can try it out here: https://handlebars-realworld.herokuapp.com/.

I've also got a logo ready (see repository README).

Please let me know what the next steps are or if you have any questions!

https://github.com/jacobstern/typescript-handlebars-realworld

Thanks!

**Comment by bbbooo313** [comment]
你可以在这里试试：[oubopingtai.com](oubopingtai.com)

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
