### ISSUE TITLE
🗄 🔧 Erlang + Cowboy

### ISSUE THREAD

**Issue by Argonus** [gothinkster/realworld#368]
**Notes**
- No SQL database layer, instead of this I'm going to use Erlang ETS or Mnesia [What Is?](http://erlang.org/doc/efficiency_guide/tablesDatabases.html#mnesia-specific)
- Only Backend Part
- Current deadline: End of October 2019
- There is Issue https://github.com/gothinkster/realworld/issues/119 with the same topic but both account & repo are deleted;/ 

**Progress / ToDo**

- [x]  🏁 Fork the starter repo & post the link in this issue
- [x]  🎨 Create logo for repo & update issue status
- [ ]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

**Current Status**
Forked: [Argonus/reladworld](https://github.com/Argonus/realworld-starter-kit)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !

**Comment by ZkHaider** [comment]
You are mass spamming our inboxing 🙂

![2E1395C9-17C0-46F0-A40B-8491FA573556](https://user-images.githubusercontent.com/7844550/114901045-449c1880-9dc9-11eb-9dd5-1b5392ffcff9.png)

**Comment by geromegrignon** [comment]
Sorry for that.

We are clearing inactive issues in order to able able to focus on recent activity (bugs/feature requests).

**Comment by ZkHaider** [comment]
I modified settings @geromegrignon so should be good.

However doesn’t solve problem for others... 

![2AC9D50B-D2DD-47DA-9738-60E5B1218F22](https://user-images.githubusercontent.com/7844550/114902386-a01ad600-9dca-11eb-9b4e-9a908edd9731.jpeg)
