### ISSUE TITLE
LitElement - Typescript - Redux

### ISSUE THREAD

**Issue by Erikvdv** [gothinkster/realworld#369]
I have started a version of the app in LitElement.

It is using LitElement, Redux and Typescript.
 
[https://github.com/Erikvdv/litelement-realworld](https://github.com/Erikvdv/litelement-realworld)

**Comment by filipbech** [comment]
Looking forward to getting this in... do you need help?

**Comment by Erikvdv** [comment]
I am planning to finish the functionality part in the coming two weeks. That should be good enough for putting it on the realword.io repo. I want to finish it asap as I would like to experiment with rxjs based redux and fetch asap.To speed the remainder up, some support with setting up unit and e2e test could be helpful.

**Comment by filipbech** [comment]
I'm honestly not to familiar with the testing side of litElement... I guess its like the good old polymer webcomponents testing... I don't think I can be of much help with that :-/ 
Looking forward to seeing the results though...

**Comment by justinfagnani** [comment]
There are lot more options for testing with Polymer 3 and LitElement because they don't use HTML imports. I'd probably go with the open-wc.org testing reccomendations for now.

**Comment by Erikvdv** [comment]
I was thinking of using Jest for the unit tests and cypress for the e2e tests. With respect to the e2e tests I am curious to see if that approach will work given the encapsulation of the web components. The semantic-dom-diff library looks interesting as well, will give it a try when I have time.

**Comment by justinfagnani** [comment]
Jest has terrible web components support, and possibly bad modules support. I really would follow the open-wc.org reccomendations.

**Comment by Erikvdv** [comment]
Ok, will follow your advice and start with the open-wc setup. Seems quite straight forward in terms of setup anyway.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
