### ISSUE TITLE
Nestjs + MongoDB

### ISSUE THREAD

**Issue by ruslanguns** [gothinkster/realworld#370]

**Comment by RafaRochaS91** [comment]
Is this being followed? 
I'm interested of opening a PR for this, maybe using NestJS + TypeORM to be more DB driver agnostic

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
