### ISSUE TITLE
Micronaut Framework

### ISSUE THREAD

**Issue by mirjahal** [gothinkster/realworld#371]
Hi guys, I started the real world backend example implementation using Micronaut framework: https://github.com/mirjahal/micronaut-realworld-example-app

Coming soon i update the README.md file with more information about the project.

@Cameron-C-Chapman @anishkny please, could set the labels backend and wip?

Thanks!

**Comment by akamanocha** [comment]
Hey @mirjahal 

I was writing the same in the parallel universe. Can collaborate!

https://github.com/akamanocha/micronaut-realworld-example-app
