### ISSUE TITLE
Nuxt.js +Typescript

### ISSUE THREAD

**Issue by dj0nny** [gothinkster/realworld#372]
Hello guys :smile:, I started a realworld app implementation using Nuxt.js and Typescript

https://github.com/dj0nny/nuxt-typescript-realworld

**Comment by anishkny** [comment]
FYI there is already a Nuxt.js (JS) in progress in #218 - but go for it!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
