### ISSUE TITLE
Create a wordpress backend

### ISSUE THREAD

**Issue by shubhra14** [gothinkster/realworld#378]
Hi,

I am a student/beginner and am familiar with php/wordpress. I have just started learning js/vue. I wanted to make the [Vue RealWorld Example App](https://github.com/gothinkster/vue-realworld-example-app) to work with the wordpress rest api. I was adviced by the app's developer to ask here how to make wordpress api work with RealWorld/Vue frontend.

I am familiar with how to make Vue+WP work but I am not very well versed with Vuex yet. I'm in need of a bit of guidance. Thank you for your time.

**Comment by anishkny** [comment]
Unfortunately, the frontend and backend implementations follow the same [API](https://github.com/gothinkster/realworld/tree/master/api) and can only work with each other. You can't really run a RealWorld frontend against another backend.
