### ISSUE TITLE
create a rust/yew frontend

### ISSUE THREAD

**Issue by khimaros** [gothinkster/realworld#382]
https://github.com/DenisKolodin/yew

**Comment by bbbooo313** [comment]
[oubo234.com](oubo234.com)

**Comment by jetli** [comment]
Yew frontend is available now 🎉

Source: https://github.com/jetli/rust-yew-realworld-example-app
Live demo: https://jetli.github.io/rust-yew-realworld-example-app/
Issue: https://github.com/gothinkster/realworld/issues/453
