### ISSUE TITLE
React Hooks + Typescript

### ISSUE THREAD

**Issue by chagweyh** [gothinkster/realworld#385]
Hello folks, I started a new realworld app implementation using react hooks and typescript.
https://github.com/haythemchagwey/react-hooks-typescript-realworld/

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
