### ISSUE TITLE
Typescene front-end (new TypeScript framework)

### ISSUE THREAD

**Issue by jcormont** [gothinkster/realworld#388]
Hey everyone, I recently launched the [Typescene](https://typescene.dev) framework and some people asked for a RealWorld implementation.

https://github.com/typescene/typescene-realworld-example-app

WIP:
- Unit Tests (planning how to do this at the moment)
- Better responsive resizing closer to the original CSS

Looking forward to your feedback. Please follow [@typescene](https://twitter.com/typescene) on Twitter to show your support if you like what you see.

**Note**: this issue thread is NOT a forum for feedback on Typescene in general, please keep this issue on-topic, thanks!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
