### ISSUE TITLE
Haskell / Miso Frontend

### ISSUE THREAD

**Issue by Lermex** [gothinkster/realworld#389]
I'm working on implementing the frontend spec in [Miso](https://haskell-miso.org), an Elm-like frontend library for [Haskell](http://haskell.org) that uses [GHCJS](https://github.com/ghcjs/ghcjs), the Haskell-to-JS compiler.

The repository is https://github.com/Lermex/haskell-miso-realworld

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
