### ISSUE TITLE
Fullstack Elixir/Phoneix 

### ISSUE THREAD

**Issue by colonelrascals** [gothinkster/realworld#392]
Would there be any interest in a Fullstack Elixir/Phoneix app using liveview?

**Comment by anishkny** [comment]
Sure go for it! In fact we don't have a single fullstack impl.

**Comment by sunndeath** [comment]
> Would there be any interest in a Fullstack Elixir/Phoneix app using liveview?

Do you want to implement this example of app?
Or maybe I can do it...

**Comment by sunndeath** [comment]
> Sure go for it! In fact we don't have a single fullstack impl.

@anishkny hi!
Do you want to implement this example of app?
Or maybe I can help you for the implementation? Or I can try do it...

**Comment by geromegrignon** [comment]
Feel free to open a dicussion [here](https://github.com/gothinkster/realworld/discussions/categories/ideas)
