### ISSUE TITLE
Haskell/SnapFramework

### ISSUE THREAD

**Issue by kigsmtua** [gothinkster/realworld#399]
Implementing the Conduit API using Haskell's snap framework

[Link to repo](https://github.com/kigsmtua/haskell-snap-realworld-example-app)

**Current Status**

Todo: 

- [x]  🏁 Fork the starter repo & post the link in this issue

- [ ] 🔨 Implement all of Conduit's functionality per the spec & API

- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
