### ISSUE TITLE
Postman collection URL in article 404s

### ISSUE THREAD

**Issue by jonnykates** [gothinkster/realworld#4]
On [this article](https://thinkster.io/tutorials/testing-backend-apis-with-postman/using-collections-in-postman), the link to import the Postman Conduit collection is specified as:

https://raw.githubusercontent.com/gothinkster/productionready/master/Conduit.json.postman_collection

But this 404s. The collection can be properly found at this location:

https://raw.githubusercontent.com/gothinkster/realworld/master/api/Conduit.json.postman_collection

**Comment by EricSimons** [comment]
Thanks for this -- fixed!
