### ISSUE TITLE
🗄🔧 HapiJS

### ISSUE THREAD

**Issue by antony** [gothinkster/realworld#40]
Hapi is the server-side node framework which powers Walmart's mobile site, among others. If it can handle black friday, it's a prime candidate for realworld!

With Joi for seamless validation, and Boom for consitent API errors, Hapi makes API creation a breeze, and a refreshing change from the raw-edges of express.

I'll request this here, and if nobody picks it up I'd be more than happy to start building it.

**Comment by EricSimons** [comment]
I love it! @hueniverse is there anyone in the Hapi community that might be want take this on and/or provide feedback to @antony while he builds it out?

**Comment by hueniverse** [comment]
You can try posting about it at https://github.com/hapijs/discuss

**Comment by battila7** [comment]
I'm just experiencing with Hapi but will definitely keep my eye on this implementation once it's started.

**Comment by EricSimons** [comment]
@antony go ahead and take lead on this! Fork the starter kit and then post the link back here, and I'll update the issue status 👍

**Comment by EricSimons** [comment]
@antony just created a logo that you can use for the repo's readme:

![hapi](https://cloud.githubusercontent.com/assets/556934/25451743/c8973c5e-2a88-11e7-9042-5acfab0a19e4.png)

**Comment by thesbros** [comment]
Is anyone currently working on this? If not I'd like to try. :)

**Comment by EricSimons** [comment]
@thesbros I think @antony was planning on starting it (see his comments in [this thread](https://github.com/hapijs/discuss/issues/482)), but it doesn't look like he's pushed any code to his fork of the starter repo.

I'd say go ahead and fork the starter repo + post link back here, add @antony to the repo, heed the recommendations that the Hapi folks shared in that other thread, and then get started!

**Comment by thesbros** [comment]
@EricSimons Great :) Is there any spec on databases or is it just go with whatever you know?

**Comment by EricSimons** [comment]
@thesbros try and use the most mainstream DB's, especially ones that are commonly used with that framework (i.e. for Node/Express we chose Mongo, because of MEAN/MERN/etc stacks)

Not super in-tune with the Hapi community, but I'd imagine that either Postgres or Mongo are solid choices? Would love for any Hapi experts to share their opinion!

**Comment by antony** [comment]
Yep sorry have parents down for the long weekend and a busy week ahead so I'm not going to be able to make a start just yet - happy for @thesbros to make some headway if they have time!

**Comment by sirgallifrey** [comment]
I have much interest in this tread! It will be great for hapi community to have this RealWorld example! As for the database, hapi don't have a say in it! You should use whatever your project demands. Feel free to ping me, I'll be glad to help

**Comment by EricSimons** [comment]
@sirgallifrey awesome, your help is much appreciated!! @antony what's the status of the Hapi backend atm? Anything that @sirgallifrey can help out with?

**Comment by guillaumemaka** [comment]
@EricSimons here is my contribution [https://github.com/guillaumemaka/realworld-starter-kit-hapijs](https://github.com/guillaumemaka/realworld-starter-kit-hapijs)

**Comment by EricSimons** [comment]
@guillaumemaka so sorry about my delay here, I'm just seeing this now! Does this adhere to the API spec completely? If so, I'd love to list it on the readme! Excellent work!!

**Comment by EricSimons** [comment]
@guillaumemaka just checking in on this! Would love to get it added to the main README if it's ready :)

**Comment by guillaumemaka** [comment]
@EricSimons yes I think its ready I implemented all the Specs ! Maybe it need an experience HapiJS developer to look at it.

**Comment by EricSimons** [comment]
@guillaumemaka no worries! I just added you to the new repo and listed it on the readme :) Thanks so much for your awesome work on this!! 🎉
