### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by ahmedabdailla** [gothinkster/realworld#400]
I wanted to participate and create a FastAPI Based Backend. 
https://fastapi.tiangolo.com/
Repo URL : https://github.com/ahmedabdailla/FastAPI-realword

**Comment by renodesper** [comment]
@ahmedabdailla Any update for this? I'm actually looking for a real-world example for FastAPI.

**Comment by ahmedabdailla** [comment]
it took me a while to start the programming. I'm gonna start working now it's approx 2 weeks to finish.

**Comment by mandarvaze** [comment]
@ahmedabdailla is there an update to this ?

While I was looking for FastAPI implementation, I came across #520 - which seems to be complete.

**Comment by abdusabri** [comment]
Closing in favor of https://github.com/gothinkster/realworld/issues/520, which is complete and has been added to the README
