### ISSUE TITLE
Riot.js v3

### ISSUE THREAD

**Issue by iq3addLi** [gothinkster/realworld#401]
Hi
Implemented RealWorld with Riot.js v3.

Sorry for the reverse order. Since PullReqesut has been issued first, please see [here](https://github.com/gothinkster/realworld/pull/398) for description.

Thank you for your reviewing.

**Comment by iq3addLi** [comment]
@anishkny 
May I ask you to merge like [this issue](https://github.com/gothinkster/realworld/issues/314)?
Thanks😃.

**Comment by anishkny** [comment]
Tried it out locally. Looks good!

Good to go! @Cameron-C-Chapman

**Comment by iq3addLi** [comment]
@anishkny @Cameron-C-Chapman
What are you checking now?
Please let me know if you have any problems. 😁
