### ISSUE TITLE
Swift Vapor with Layered Architecture

### ISSUE THREAD

**Issue by iq3addLi** [gothinkster/realworld#404]
I develop RealWorld backend under the following conditions. ⚒

content | description
:---|:---
repository| https://github.com/iq3addLi/swift-vapor-layered-realworld-example-app 
language| Swift
framework| Vapor
architecture| Layered Architecture
Database| MySQL

Sorry, it will be a private project until the product matures to some extent.🙇‍♂️

### Other ongoing Swift projects
* https://github.com/gothinkster/realworld/issues/175

**Comment by bbbooo313** [comment]
[oubo234.com](oubo234.com)  老哥换个友链吗？
联系QQ：1297532431

**Comment by iq3addLi** [comment]
@anishkny @Cameron-C-Chapman
Thank you for [the last time](https://github.com/gothinkster/realworld/issues/402).
I'd like to ask you to check again. OK? 😊
Thx.
https://github.com/iq3addLi/swift-vapor-layered-realworld-example-app

**Comment by anishkny** [comment]
@iq3addLi can you add CI to your project to show how to build and test it against [API tests](https://github.com/gothinkster/realworld/tree/master/api).

**Comment by iq3addLi** [comment]
@anishkny OK. I will be do.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
