### ISSUE TITLE
AWS Lambda + DynamoDB + Go

### ISSUE THREAD

**Issue by chrisxue815** [gothinkster/realworld#408]
Hi,

Thank you for continuously improving this project. Great work!

I just implemented a backend using AWS Lambda + DynamoDB + Go + Serverless:
https://github.com/chrisxue815/realworld-aws-lambda-dynamodb-go

Demo:
https://chrisxue815.github.io/realworld/build/#/

Please feel free to reference it in README.md!

Related issue: #30 

Thanks,
Chris

**Comment by anishkny** [comment]
Great work @chrisxue815 ! Could you add CI/CD (e.g. TravisCI) to show how to build/test this code. And also show running the [API tests](https://github.com/gothinkster/realworld/tree/master/api) against your backend?

**Comment by chrisxue815** [comment]
Thank you for your reply @anishkny ! All done.
* [TravisCI build status](https://travis-ci.org/chrisxue815/realworld-aws-lambda-dynamodb-go) added to readme.md.
* [API test result](https://gist.github.com/chrisxue815/07aa20b42bacced8f38aa8352c0f7c60)
