### ISSUE TITLE
Flask + Celery

### ISSUE THREAD

**Issue by danigoland** [gothinkster/realworld#409]
Since its a pretty popular stack and it's not on the list if people are interested I can prepare it pretty fast from my own templates.

Thumbs Up if you are interested :)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
