### ISSUE TITLE
GraphQL Implementation of the Django Api

### ISSUE THREAD

**Issue by MainaKamau92** [gothinkster/realworld#412]
**Description**
Following issue #412 raised on the implementation of GraphQL using Django graphene. I have created a repository that contains the code of a working API that has been implemented using the above requirements.

**Repository Link**
[Conduit Django GraphQL](https://github.com/MainaKamau92/conduit_django_graphene.git)

**Feedback would be appreciated**
@anishkny @Cameron-C-Chapman @sandeesh @brwr

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
