### ISSUE TITLE
Quarkus Framework with Java

### ISSUE THREAD

**Issue by diegocamara** [gothinkster/realworld#414]
Hello guys, i'm working on a realword app implementation using Quarkus Framework with Java.
[https://github.com/diegocamara/realworld-api-quarkus](https://github.com/diegocamara/realworld-api-quarkus)

**Comment by diegocamara** [comment]
Hello @Cameron-C-Chapman   @anishkny Could you please check the repository? The project is functional and meeting the tests performed by postman collection.

Thank's

**Comment by lordofthejars** [comment]
@diegocamara Thank you very much for this. @Cameron-C-Chapman @anishkny anything else is required to merge this PR?

**Comment by maxandersen** [comment]
Yes, how are new entries added ? would be cool to get Quarkus listed/included.

**Comment by maxandersen** [comment]
I guess a PR to add it to the yaml like https://github.com/gothinkster/realworld/pull/375/files is needed - but  I see several PR's more than 6+ months old. Is this repo/project dormant ?

**Comment by anishkny** [comment]
Hey this looks great. Could you add CI to the project (eg TravisCI) to show how to build it and also run API tests against it? Thanks!

**Comment by diegocamara** [comment]
@lordofthejars, @maxandersen, @anishkny thanks for the support; I integrated the repository with travis ci today, let me know if something is missing.
