### ISSUE TITLE
react-redux-realworld-example-app has long-outstanding pull-requests...

### ISSUE THREAD

**Issue by shanebdavis** [gothinkster/realworld#415]
Could someone take a look at the outstanding pull-requests for react-redux-realworld-example-app? That app desperately needs updating. @khaledosman did some excellent work, and I've also contributed a hooks-update (though I should probably merge my work with his before it's accepted).

https://github.com/gothinkster/react-redux-realworld-example-app/pulls

Thanks!

**Comment by QuantumInformation** [comment]
Probably should be left there instead of posting here. Otherwise, this place is gonna get way too noisy. Are there not contributors there that have Push permissions?

**Comment by khaledosman** [comment]
It seems like no one is really maintaining these repos anymore..

Same for the Angular one, these have been lying around since April 
https://github.com/gothinkster/angular-realworld-example-app/pull/145
https://github.com/gothinkster/react-redux-realworld-example-app/pull/135

**Comment by QuantumInformation** [comment]
IMOP these repos would be better sourced under different users accounts or more perms given, ie the Svelte model: https://github.com/sveltejs/realworld

**Comment by geromegrignon** [comment]
We are now opened to community implementations to make maintenance more reliable.
For now, closing this issue related to an implementation.
