### ISSUE TITLE
Server side rendering react with nextjs

### ISSUE THREAD

**Issue by arrlancore** [gothinkster/realworld#423]
I have seen another project using nextjs and redux, but it seem still client rendering. So I create one for SSR version. here is the repo https://github.com/arrlancore/nextjs-ssr-real-world-app-example

Please give a review and feedback.

**Comment by tranlehaiquan** [comment]
I can't go to direct link like:
https://nextjs-real-world-example-ssr.netlify.com/post/44-id1npi
It will go to error page.

**Comment by arrlancore** [comment]
> I can't go to direct link like:
> [nextjs-real-world-example-ssr.netlify.com/post/44-id1npi](https://nextjs-real-world-example-ssr.netlify.com/post/44-id1npi)
> It will go to error page.

thanks @tranlehaiquan for testing. It has some issue with netlify hosting so ssr for dynamic page not working, I just changed it to heroku. And ssr working properly, you can test it on https://nextjs-ssr-real-world-example.herokuapp.com

**Comment by tranlehaiquan** [comment]
👍 it good now

**Comment by tranlehaiquan** [comment]
For pagination, you should reflect it in URL. Like:
Page 1
https://nextjs-ssr-real-world-example.herokuapp.com?page=1

**Comment by tranlehaiquan** [comment]
Improve pagination component
![image](https://user-images.githubusercontent.com/17347993/67656481-82fc0880-f986-11e9-80d5-6c42c8946e31.png)

**Comment by arrlancore** [comment]
Thanks @tranlehaiquan for the input, added to next todo feature on this issue:
https://github.com/arrlancore/nextjs-ssr-real-world-app-example/issues/7

Anyone want to make a PR will be appreciate.

**Comment by qiwang97** [comment]
> For pagination, you should reflect it in URL. Like:
> Page 1
> https://nextjs-ssr-real-world-example.herokuapp.com?page=1
> Page 1, tag reactjs
> https://nextjs-ssr-real-world-example.herokuapp.com?page=1&tag=reactjs

I have a table component with pagination. If i want to use ssr in this page, should i replace all the table section with content from server?
Url like `router.push('/books?page=2&size=10')`  may cause nested route and i just want to show table pagination. How did you handle this?

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
