### ISSUE TITLE
Appcelerator Titanium

### ISSUE THREAD

**Issue by m1ga** [gothinkster/realworld#425]
**Current Status:** Work in progress

* Codebase in progress: https://github.com/m1ga/realworld-appcelerator-titanium

It's a start and displays a basic list and has a article detail page:
<img src="https://raw.githubusercontent.com/m1ga/realworld-appcelerator-titanium/master/demo_1.jpg"/>
Still a lot to do :smile: 

Features:
* [x] Basic article list
* [x] Basic article detail page
* [ ] Add more information to the list
* [ ] Add more information to the article
* [ ] UI work
* [ ] Login
* [ ] Profile
* [ ] Splashscreen / Logo
* [ ] Tests
* [ ] Documentation

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
