### ISSUE TITLE
Holochain

### ISSUE THREAD

**Issue by freesig** [gothinkster/realworld#428]
Hi everyone.
I'm going to be working on an implementation of the backend using [Holochain](https://developer.holochain.org/).
I think it will be a cool experiment to see if I can get this working as Holochain is peer to peer and doesn't require any servers (well that's true atleast for data storage).
The repo is here: https://github.com/freesig/holochain-realworld-example-app

**Comment by freesig** [comment]
I can't seem to assign labels to this issue.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
