### ISSUE TITLE
Frontend with Angular + angular-redux

### ISSUE THREAD

**Issue by nhaancs** [gothinkster/realworld#429]
Hi everyone,
I'm going to be working on an implementation of the frontend using Angular + angular-redux.
The repo is here: https://github.com/nhaancs/angular-redux-realworld-example-app

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
