### ISSUE TITLE
RiotJS + Universal + Effector + Hot Reload

### ISSUE THREAD

**Issue by apapacy** [gothinkster/realworld#433]
Codebase (complete): 

https://github.com/apapacy/realworld-riotjs-effector-universal-hot

Demo:

https://realworld-riot-effector-universal-hot-pnujtmugam.now.sh

**Comment by anishkny** [comment]
Great @apapacy ! could you please add CI/CD (e.g. Travis/Circle) to your repo to ensure it builds? Thanks

**Comment by apapacy** [comment]
@anishkny 
Thank. I added integration with a Travis CI to the project
