### ISSUE TITLE
api/user VS api/profiles/{slug}

### ISSUE THREAD

**Issue by tobiu** [gothinkster/realworld#442]
![Screenshot 2019-11-22 at 15 50 47](https://user-images.githubusercontent.com/1177434/69435565-16371c80-0d40-11ea-9d30-f649488f60e6.png)

![Screenshot 2019-11-22 at 15 51 01](https://user-images.githubusercontent.com/1177434/69435571-19320d00-0d40-11ea-8485-56e6abc61315.png)

the first one contains null in case the current user has no custom image, the second api provides the default image url.

would be nice if this was consistent.

**Comment by geromegrignon** [comment]
Fixed with the new API
