### ISSUE TITLE
Mix and Match is not true

### ISSUE THREAD

**Issue by luicrispo** [gothinkster/realworld#444]
I have implemented the front end using Angular [https://github.com/gothinkster/angular-realworld-example-app](url) and the back end using Functional ASP.NET Core [https://github.com/dnikolovv/dev-adventures-realworld](url) and while the front end works fine if the api endpoint is set to **https://conduit.productionready.io/api** and on the opposite is not working when pointing to the Functional ASP.NET Core. After spending quite a lot of time on finding the root cause I've notice running some tests with Postman that the API contracts differ.
For example submitting the post request to register a new user using the endpoint https://conduit.productionready.io/api return this sort of Json 
{
    "user": {
        "id": 76187,
        "email": "pippo33@pippo.com",
        "createdAt": "2019-11-23T02:52:34.179Z",
        "updatedAt": "2019-11-23T02:52:34.188Z",
        "username": "pluto33",
        "bio": null,
        "image": null,
        "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzYxODcsInVzZXJuYW1lIjoicGx1dG8zMyIsImV4cCI6MTU3OTY2MTU1NH0.4W4vPC3QajI9-vG4qQHCIwUWBfyE4eFpNwv2e3vpPDc"
    }
}

the response from the Functional ASP.NET Core return this sort of Json:
{
    "user": {
        "bio": null,
        "image": null,
        "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OWI3ODFkZS01OTNlLTQ1MWUtOWEzNy01OThhN2QwNzgxYmEiLCJlbWFpbCI6InBpcHBvMzNAcGlwcG8uY29tIiwianRpIjoiMGU0OTQ1ZDAtMWM5YS00NmU1LTllNTctZDgyZWY4MWY0NDc5IiwiaWF0IjoxNTc0NDUxNzQzLCJuYmYiOjE1NzQ0NTA0NzksImV4cCI6MTU3NDQ1ODk0MywiaXNzIjoid2ViLWFwaSIsImF1ZCI6IioifQ.gJKHxC94zled-e6Nzc78KXtby1eyKF6Vc0SMid0F0X0",
        "email": "pippo33@pippo.com",
        "username": "pluto33"
    }
}
As you can see there are attributes like "id" "createdAt" "updatedAt" not returned as in the case of using https://conduit.productionready.io/api end point.

What is surprising me is that looking at the documentation of the API specs it appears that these attributes are not specified. 
Please before committing backends and front end ensure they all works fine as expected and update the API specs otherwise we waste time to identify issues for nothing

**Comment by anishkny** [comment]
Opened issue on the Functional ASP.NET repo.
