### ISSUE TITLE
neo.mjs frontend

### ISSUE THREAD

**Issue by tobiu** [gothinkster/realworld#446]
Hello everyone,

I moved the neo.mjs implementation into a separate repo now (forking the starter kit).
https://github.com/neomjs/neomjs-realworld-example-app

The implementation is already feature complete and ready for your review.

Thx & best regards
Tobi

- [x]  🏁 Fork the starter repo & post the link in this issue
- [ ]  🎨 Create logo for repo & update issue status (@EricSimons)
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ]  🎉 Tag v1 release and officially list it on the README!

**Comment by tobiu** [comment]
online examples are now available here:

https://neomjs.github.io/neomjs-realworld-example-app/

**Comment by tobiu** [comment]
@anishkny @EricSimons is this project still alive?

I created another thread for the neo.mjs frontend, when it was not inside a starter kit fork yet and did not get a response for 2 weeks. Now the starter kit fork is feature complete and still no response for 7 days.

A quick heads up if and when someone will look into it would be greatly appreciated!

After all, I invested quite some time to create a new version where the app runs within a web worker and in dev mode, the real ES8 JS modules will get directly consumed by the browser.

Thanks for your feedback,
Tobias

**Comment by anishkny** [comment]
@tobiu sorry for the delay - this looks awesome. Could you build/test this project on TravisCI (or similar) as a how to?

**Comment by tobiu** [comment]
Hi @anishkny,

good to hear from you. In theory this is possible, it might need some time though.
Please keep in mind that i released neo.mjs to the public on November 23rd. Before this point, there was no npm package of the framework, so the build processes only work inside the root folder of the framework repo at this point.

It should be possible though to use a CI to build the app inside the framework repo folder and copy the dist folder to the app repo root.

Regarding testing via a CI it does get even more complicated. neo.mjs is using Siesta (Bryntum) which can run inside a nodejs env. However, getting neo.mjs running in node as well is definitely an Epic. For pure unit testing it is possible (in case we import the modules we do want to test into the main thread). Getting the full worker setup running in node is non trivial for sure.

As a first step I will update the neo.mjs RealWorld app repo to the latest framework version tomorrow and add a small guide on how to do a build manually (just a couple of npm run script calls).

It is definitely already possible to launch the Siesta testing harness locally for this repo.

Regarding neo.mjs itself: It already got 420 npm downloads since the release and is starting to gain traction.

![Screenshot 2019-12-11 at 23 53 21](https://user-images.githubusercontent.com/1177434/70668133-fd50c580-1c72-11ea-9aec-4782fc4fa031.png)

**Comment by anishkny** [comment]
When do you expect neo.mjs to be available for wider use? Maybe we should hold off until there is a clearer path for users to consume it.

**Comment by tobiu** [comment]
If I may add a spoiler here: I already started to work on a second version of the RealWorld app. It will stick to the API, but not to the UI specs at all. V2 will not use the bootstrap based theme, since neo.mjs has an own component styling engine in place which would create conflicts.

It probably can not get added here, but is meant to be a starting point for new devs who want to get up to speed on how to create a bit more complex neo.mjs apps. It is also meant for making a point why a multi-threading performance based ui framework is needed.

The following examples are DOM based (no webGL, canvas or SVG):

![conduit-v2-helix](https://user-images.githubusercontent.com/1177434/70668385-c29b5d00-1c73-11ea-96a7-6d5f375e931a.png)

![conduit-v2-gallery](https://user-images.githubusercontent.com/1177434/70668392-c929d480-1c73-11ea-8041-33025e56a615.png)

Best regards
Tobias

**Comment by tobiu** [comment]
> When do you expect neo.mjs to be available for wider use? Maybe we should hold off until there is a clearer path for users to consume it.

It is already available now :) I will keep you posted after upgrading the app tomorrow.

**Comment by tobiu** [comment]
spoiler2 on the gallery & helix: https://www.facebook.com/neo.mjs/videos/476943849598009/

**Comment by mrsunshine** [comment]
@anishkny 
> When do you expect neo.mjs to be available for wider use? Maybe we should hold off until there is a clearer path for users to consume it.
Good start for new users to consume it are the neo.mjs pages with docs and examples (including realworld app)
https://neomjs.github.io/pages/

and the tutorials inside of the docs 

https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/docs/index.html

**Comment by tobiu** [comment]
a quick heads up on my end: i was pretty busy today getting the neo.mjs 1.0.10 npm release published. the gh-pages are updated as well and the v2 "spoiler app" prototype is now online.

will work on the app for which this ticket is about tomorrow.

**Comment by tobiu** [comment]
Hi @anishkny,

I am pleased to announce that the demo app repo is ready for your review now.
The repo is upgraded to neo.mjs v1.0.11 and does provide build processes (this was a rather big sprint).

In general: you can change the app source files and just reload the page for the non dist versions (no build required).

To get the changes into dist/development or dist/production, 2 new build scripts are in place:

> npm run dev-build-my-apps

> npm run prod-build-my-apps

Looking forward to your feedback!

Best regards,
Tobias

**Comment by anishkny** [comment]
Can you build/test this repo on TravisCI/CircleCI or similar to show how to set it up?

**Comment by tobiu** [comment]
I can take a look into it. It is trivial though at this point (see the updated readme):

1. Clone the repo
2. npm install
3. npm run server-start (or use a local webserver of your choice, configured for JS modules)

**Comment by tobiu** [comment]
Hi @anishkny,

I added a couple more test into the siesta harness (navigating from home to login to signup + checks if we end up on the correct page).

I also polished the starting point for:
> npm run server-start

Running the script will open a new browser tab with this content:
![Screenshot 2019-12-16 at 22 27 07](https://user-images.githubusercontent.com/1177434/70944429-5645a280-2053-11ea-99fe-2ec589d6abe2.png)

So, to open the testing harness you just need to click on the link there.

I read the specs once more very carefully:
https://github.com/gothinkster/realworld/tree/master/spec

And they don't mention that using a CI is a requirement.

With a quick look at the codebase I assume that your self made top1 app does not even have tests at all: https://github.com/gothinkster/react-redux-realworld-example-app

So is it really necessary to add a CI?

I am asking this since I am not familiar with using them plus never tried to use Siesta in an automated way (although it should be possible).

My time is sadly very limited at this point. We had a big marketing event for neo.mjs this weekend:
![HN](https://user-images.githubusercontent.com/1177434/70944842-2ba81980-2054-11ea-8270-e4be7cfb72d1.png)

![3168](https://user-images.githubusercontent.com/1177434/70944855-32cf2780-2054-11ea-9c27-3c3ab4619fa4.png)

![fb-stats](https://user-images.githubusercontent.com/1177434/70944869-39f63580-2054-11ea-9a54-480ca6304f11.png)

and now users are pinging us why we are not listed yet with a fully functional app. I need to jump back into a client project for quite a while, so no chance to look into it on my end.

Please give me a heads up, if the current status is fine or not. If not I can try to ask Bryntum to help out on this.

Thanks and best regards
Tobias

**Comment by mrsunshine** [comment]
Hi @anishkny,

we dedicated a lot of time (especially @tobiu ) to build the realworld app with neo.mjs because we think it is a great showcase. Thanks to your feedback we even improved the hole build process.

Now like you can see in the posts above everything is prepared and up and running.

We really would appreciated to see the app and framework get listed. It means a lot to us.

Thanks
Nils

**Comment by shabbirulhasan** [comment]
Hello,
I hope all is good.first of all, I love the work that you have done it's lovely.
 I clone your repo the COVID 19 is working fine on localhost I but want to publish it without localhost:8080. I want to publish with some name rather then localhost.can you please help out me?

**Comment by tobiu** [comment]
Hi @shabbirulhasan,

this topic here is messing with my emotions. The neo.mjs RealWorld App is feature complete for more than 4 months now and it never got reviewed. It did not even get listed on the repo page as in progress.

I have rarely encountered this unsupportive people than the Gothinkster guys here.
Especially @anishkny and @EricSimons. They simply don't care and would rather let a new promising framework die in the void of being unknown than doing their part.

Regarding your question: please use the issue tracker inside the neo repo you are using (there is more than 1 neo covid repo inside the https://github.com/neomjs/ namespace). In short: if you got a neo app running on localhost you are almost there. Just deploy it to your webserver (or into the cloud) and specify which files should get mapped to which urls inside your webserver settings.

**Comment by EricSimons** [comment]
@tobiu FYI RealWorld is a sideproject we maintain. We have families to feed, mortgages to pay, etc and RealWorld doesn't pay those bills. RealWorld is an incredibly large OSS learning project, and as such, has a ton of issues/PRs that I honestly have no how  @anishkny makes the time to even look at much less comment on or review.

If you want to make someone the "bad guy" here, have it be me, not Anish. The dude is a beast and has single handedly scaled this project into what it is today.

I will not tolerate slander against any of the admins/maintainers. If you do this again, you will be banned.

That said, lets talk about the fun things!

If I had to guess why this hasn't been merged in yet, I'd wager it's because the answers given weren't super straightforward. I took some time to review what you've made, and it LGTM, but the only thing I'd request is that the link at the top of your realworld app repo points at the actual running Conduit app itself instead of your bare GH pages URL.

Once you've got that taken care of I'll merge this PR. Thanks

**Comment by tobiu** [comment]
Hi @EricSimons,

thank you for looking into this. I changed the link on top of the repo page to point to the dist/prod version directly (same for the "demo" link on the top part of the readme).

The reason for pointing to the main examples page was simply that there are 3 different versions of the neo RW app out there (dev mode, dist/dev, dist/prod). Added all 3 direct links to the very bottom of the readme now.

I also took the time to update the repo to the latest neo version, adjusted the build processes & the docs app (the repo was created before the unified npx build scripts were in place).

**So, ready for a merge on my end!**

Regarding your comment: Of course I do appreciate your work as well as @anishkny's with this Conduit repository. If I would not like it, I would not have invested around 1 month to create this RW app to share it with you.

I am also very well aware of the OSS limitations. I spent 1.5 years of my full and unpaid working time to get neo to a first public release & this was 4 months ago. Literally burned all all of my personal savings and this was only possible since I did work on some very high profile JS projects before. I felt that it was time to give back and share my knowledge with everyone who is interested in scaling UIs via multithreading. Now, without creating an awareness that this framework even exists all the effort would be pointless. This is why it feels important to me to get listed here.

Best regards,
Tobias

[Off topic] In case you got a couple of minutes of spare time I would love your input on the Covid19 in numbers neo app. It needed less code than the RW app to create it (pictures and links inside the main repo readme => https://github.com/neomjs/neo). Thx!

**Comment by EricSimons** [comment]
Awesome- can you open a PR on this repo to add this to our `frontend-repos.yaml`?

**Comment by tobiu** [comment]
"here" as in "https://github.com/gothinkster/realworld-starter-kit"?

if so, done.

**Comment by EricSimons** [comment]
No, see this PR as an example: https://github.com/gothinkster/realworld/pull/483/files

**Comment by tobiu** [comment]
ok... again.

like this: https://github.com/gothinkster/realworld/pull/488 ?

**Comment by mrsunshine** [comment]
@EricSimons @tobiu great work. Who has the rights and can merge this? looking forward to see this in the list. Thanks guys

**Comment by tobiu** [comment]
@EricSimons The PR is open for 21 days now. Anything missing on my end?

Thanks, Tobias

**Comment by tobiu** [comment]
@EricSimons Another 16 days. A comment would be appreciated.

Thanks, Tobias

**Comment by tobiu** [comment]
updated the neo RW implementation to use the latest framework version (v1.1.57).

**Comment by EricSimons** [comment]
Merged!  Sorry about the delay! Closing this out- thanks for contributing to RealWorld 🙏

**Comment by tobiu** [comment]
Thx! v1.1.57 made the neo implementation a lot more lightweight, since main thread addons are now in place. Here is a small blog post about it: 

https://medium.com/@tobiasuhlig/using-js-libraries-inside-a-multithreading-environment-835cd8cbc30b?source=friends_link&sk=39450bea5b2c1812a9adb741d7f9e3af

**Comment by tobiu** [comment]
updated the repo to use neo v1.1.74 which includes the new build programs.

![Screenshot 2020-05-26 at 16 05 29](https://user-images.githubusercontent.com/1177434/82911029-acf0ca00-9f6b-11ea-9d1d-001987e237f6.png)

https://medium.com/p/bundling-your-webpack-based-build-processes-performance-improvements-dd7d0ffdd788?source=email-121c20a934c6--writer.postDistributed&sk=6b7ae4abdf227ecee6c046b5bc9b14b6

**Comment by tobiu** [comment]
Hi @EricSimons,

how often do you update the main repo-readme? The last listed update was on May 2nd.
Still got users complaining that neo is not yet listed here.

Thanks for looking into it!

Best regards,
Tobias
