### ISSUE TITLE
🖥 🔧 Ember Octane

### ISSUE THREAD

**Issue by patocallaghan** [gothinkster/realworld#449]
The "classic" Ember Real World app was shipped in https://github.com/gothinkster/ember-realworld. ~~This version here will take this "classic" app and update it to use [Ember Octane](https://emberjs.com/editions/octane/) conventions.~~ It ended up being a rewrite for the most part.

# Current Status

* ### Codebase in progress: [github.com/patocallaghan/ember-octane-realworld](https://www.github.com/patocallaghan/ember-octane-realworld)
* ### Help wanted: [Items to work on](https://github.com/patocallaghan/ember-octane-realworld/projects/1)

Todo:
* [x] 🏁 Fork the starter repo & post the link in this issue
* [x] 🎨 Create logo for repo & update issue status (@EricSimons)
* [x] 🔨 Implement all of Conduit's functionality per the spec & API 
* [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
* [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by Alonski** [comment]
Awesome work!

**Comment by patocallaghan** [comment]
@EricSimons what's the process for making a repo official? I've implemented all the required functionality per the spec.

Ember Octane repo: https://github.com/patocallaghan/ember-octane-realworld
Netlify preview: https://mystifying-curran-3bcc82.netlify.com/

**Comment by patocallaghan** [comment]
@anishkny does anything need to happen next? should my repo be transferred to the main org?

**Comment by anishkny** [comment]
@patocallaghan these days we have stopped transferring repos to the main org - although you are now listed on the main README - congrats! 🎊 

<img width="987" alt="image" src="https://user-images.githubusercontent.com/357499/76440623-5831b000-637b-11ea-8991-9c0b1de800c5.png">

**Comment by patocallaghan** [comment]
@anishkny okay, thank you!
