### ISSUE TITLE
🗄🔧  Go + net/http

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#45]
# Current Status

- ### Codebase in progress:<br /> [JackyChiu/realworld-starter-kit](https://github.com/JackyChiu/realworld-starter-kit)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/golang](https://gitter.im/realworld-dev/golang)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Will be built using only standard libraries, [per this discussion](https://github.com/gothinkster/realworld/issues/9#issuecomment-296823552).

**Comment by JackyChiu** [comment]
I'll jump on this as soon as I can! 😄

**Comment by JackyChiu** [comment]
Let's get this started 😎
👉🏻 https://github.com/JackyChiu/realworld-starter-kit

**Comment by EricSimons** [comment]
@JackyChiu just updated the issue status (w/ link to this implementation's gitter room)! Also, feel free to swap the logo in your readme with this one: https://github.com/chrislewispac/realworld-starter-kit/blob/master/go-realworld-logo.png

**Comment by JackyChiu** [comment]
> Will be built using only standard libraries

A little side note that the web framework will be from the standard library but the database driver will not be (since there are no database drivers in the standard library, only a driver interface defined in the `database/sql` package)

**Comment by EricSimons** [comment]
Hey Go folks! @JackyChiu is looking for a quick peer review of [his wip codebase](https://github.com/JackyChiu/realworld-starter-kit) to make sure he's on the right track — is there anyone here/in the Go community that could provide some expert feedback?

**Comment by Kartikkh** [comment]
Did someone started with net/http package ?

**Comment by JackyChiu** [comment]
@Kartikkh it was started here: https://github.com/JackyChiu/realworld-starter-kit but hasn't been active. I can pass the torch down to someone else if they want to finish it

**Comment by Kartikkh** [comment]
@JackyChiu  Hi Jacky, I am learning GoLang these days so will try to work on that, and I'll let u know about any issue I would face

**Comment by Kartikkh** [comment]
@JackyChiu  Hi I have tried a bit pls have a look at this and I am using MongoDB as Database is it Okay?
Or should I use Any ORM?
https://github.com/Kartikkh/Medium

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
