### ISSUE TITLE
Pure Go Backend

### ISSUE THREAD

**Issue by nasermirzaei89** [gothinkster/realworld#451]
Hi Everyone,

I'm writing **realworld** backend in [Golang](https://golang.org/) without any external library.

It's going to be a simple and clean code.

[nasermirzaei89/realworld-go](https://github.com/nasermirzaei89/realworld-go)

It maybe has some bugs. but it tested with postman script.

It's open to any feedback, suggestion and pull requests.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
