### ISSUE TITLE
Rust + Yew + WebAssembly frontend

### ISSUE THREAD

**Issue by jetli** [gothinkster/realworld#453]
I'm working on a [Yew](https://github.com/yewstack/yew) version of realworld frontend app, utilizing [Rust](https://www.rust-lang.org/) and [WebAssembly](https://webassembly.org/).  It's full-functional right now.

**Source**: https://github.com/jetli/rust-yew-realworld-example-app
**Live demo**:  https://jetli.github.io/rust-yew-realworld-example-app/

Todos:

- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [x] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

Possible further improvements:

- [x] CI/CD integration
- [x] Reduce .wasm size
- [ ] Model/form client-side validations
- [ ] Unit tests/benchmarks

**Comment by jetli** [comment]
@anishkny @EricSimons  Welcome to review, thanks.

**Comment by anishkny** [comment]
@jetli great! Could you please add CI (e.g Travis/Circle) to show how to build/test it.

**Comment by jetli** [comment]
Thanks, I will investigate github actions or Circle soon.

**Comment by jetli** [comment]
@anishkny  CI by github actions is added here: https://github.com/jetli/rust-yew-realworld-example-app/blob/master/.github/workflows/rust.yml and a build is passed here: https://github.com/jetli/rust-yew-realworld-example-app/commit/91cba5b4e94492569f6e0cca3daa535280000e14/checks?check_suite_id=364119451

**Comment by jetli** [comment]
@anishkny  CD by GitHub actions is also added here: https://github.com/jetli/rust-yew-realworld-example-app/blob/master/.github/workflows/cd.yml and a build is passed here: https://github.com/jetli/rust-yew-realworld-example-app/runs/354126919

**Comment by anishkny** [comment]
Great stuff! Will get this added soon!

**Comment by jetli** [comment]
Standalone desktop app support is added by this new crate: https://github.com/jetli/rust-yew-realworld-example-app/tree/master/crates/conduit-webview, now yew app can be run as a desktop app 🎉 , it looks like a slim Electron app in just ~3MB size,  Electron apps are normally in 100+MB size.
<img width="800" alt="desktop" src="https://user-images.githubusercontent.com/1142758/71204316-d16cba00-22da-11ea-887d-17a1fd6aa157.png">

**Comment by khimaros** [comment]
This is awesome @jetli -- thank you for putting this together!
