### ISSUE TITLE
Hasura GraphQL Backend

### ISSUE THREAD

**Issue by praveenweb** [gothinkster/realworld#455]
Would love to see a version of backend with Hasura GraphQL. The frontend integration can be done with React + Apollo Client.

**Comment by semenovDL** [comment]
@praveenweb I plan to do it in the near future.

**Comment by geromegrignon** [comment]
Hello, as we are moving most of current discussion to Github Dicussions, feel free to open a discussion there : https://github.com/gothinkster/realworld/discussions/categories/ideas
