### ISSUE TITLE
How is the ranking decided?

### ISSUE THREAD

**Issue by hmmhmmhm** [gothinkster/realworld#457]
Before the #448 update, Svelte was placed third on the Gold Rank.
https://github.com/gothinkster/realworld/tree/d5d69bb24c9e4ebd97f530c382229bee09388763

But now, Svelte is now located in the second position of the Bronze Rank.
I wonder how such a severe fluctuation occurs.

Can I see the causes or statistics of these changes?

**Comment by Alonski** [comment]
Hey @hmmhmmhm Unfortunately this is very confusing. There is an issue on this with an explanation #358

**Comment by hmmhmmhm** [comment]
I see... It very confusing... I hope that this problem will improve.

**Comment by Kijacode** [comment]
@hmmhmmhm I think the ranking depends on the rating start of a project repo itself , I try to follow the sequence of stars it seems as it works like that

**Comment by hmmhmmhm** [comment]
@Kijacode 

It's really really easy to get confused.
For example, this like misunderstanding is possible,

"Wow, the gold medal is attached! All the skills under this golden medal must be top-notch!"
"Well... the skills below the silver medal must be worth it... It's a second-rate technology, but it's good, right?
"Oh, the skills under the bronze medal must be the worst, they must be avoided."

We don't think there's anyone like this, but there are definitely people like this.
Because the medal was separated by a separate row instead of each item.

**Comment by geromegrignon** [comment]
Hello,

As a new maintainer i have no valid answer to this question.
However as we are moving the list of implementations to [here](https://codebase.show/projects/realworld) and sorting projects based on Github stars, i'll close this issue as we'll remove the current list showcased into the Readme.
