### ISSUE TITLE
Angular + xstate

### ISSUE THREAD

**Issue by stefanoslig** [gothinkster/realworld#459]
## **Current Status**

**Codebase - WIP:**
[https://github.com/stefanoslig/angular-xstate](https://github.com/stefanoslig/angular-xstate)

**Demo**
WIP

Todo:
- [ ] 🏁Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo
- [ ] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
