### ISSUE TITLE
GraphQL, Typescript and Node.js

### ISSUE THREAD

**Issue by huczk** [gothinkster/realworld#463]
I've created backend repo with graphql and typescript in node.

# Current Status 

- **Codebase WIP** - https://github.com/huczk/realworld-ts-gql
- **Demo** - https://realworld-ts-gql.herokuapp.com/graphql

Todo:
- [x] 🏁Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by huczk** [comment]
I have also made example frontend app than uses graphql api.

[Fronted](https://github.com/huczk/reasonml-graphql) was made with reasonML and apollo client.

But I assume that firstly we must agreed upon graphql schema for all future graphql implementations then add backend apps.  Only then frontends can be added.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
