### ISSUE TITLE
Python + aiohttp

### ISSUE THREAD

**Issue by Alveona** [gothinkster/realworld#464]
I'm considering switching to async Python from Flask/Django stack, so probably would do a realworld project as a training one using aiohttp framework

Thumbs up if interested c:

**Comment by nomhoi** [comment]
Hi, I will try to build it with Tortoise ORM.

**Comment by nomhoi** [comment]
I started the project.
https://github.com/nomhoi/aiohttp-realworld-example-app
Only authentication is completed so far.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
