### ISSUE TITLE
Laravel 6 with passport

### ISSUE THREAD

**Issue by alteredorange** [gothinkster/realworld#468]
It would be great to see an updated Laravel 6 backend with Passport (instead of third-party jwt tokens). I'm just getting into Laravel and it would be nice to see an up to date example. I'd be happy to help, but wouldn't be much help implementing Passport...

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress/propositions to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
