### ISSUE TITLE
SolidJS

### ISSUE THREAD

**Issue by ryansolid** [gothinkster/realworld#471]
I've put together a Realworld Demo for Solid(https://github.com/ryansolid/solid), the top-performing reactive library on from the [JS Framework Benchmark](https://github.com/krausest/js-framework-benchmark).

This demo includes a modern implementation is clientside only using code-splitting and Suspense with data-fetching.

You can find the repo here: https://github.com/ryansolid/solid-realworld.

I look forward to this being added.

**Comment by ryansolid** [comment]
In case anyone wants something to read while they wait. [A Solid RealWorld Demo Comparison of JavaScript Framework Performance](https://levelup.gitconnected.com/a-solid-realworld-demo-comparison-8c3363448fd8?source=friends_link&sk=2f2c00e315dd126d7e28836aec532e91).

**Comment by funcelotwork** [comment]
> In case anyone wants something to read while they wait. [A Solid RealWorld Demo Comparison of JavaScript Framework Performance](https://levelup.gitconnected.com/a-solid-realworld-demo-comparison-8c3363448fd8?source=friends_link&sk=2f2c00e315dd126d7e28836aec532e91).

very good article. and i want to solidify my js knowledge, if you know what i mean) solidjs is the next framework in my wishlist to learn right behind React, Angilar and even Preact! Keep it goint, cross god damn fingers to have this new fw a green light in MIcrosoft or Google (or Alibaba, to be honest)!

**Comment by leeoniya** [comment]
> So I started looking at the Chrome performance timeline and I found a very different story. After seeing how that differed, I decided to see how these libraries stacked.

@ryansolid every lighthouse update seems to stray farther from what i'm seeing in the perf recording timeline, too. it's gotten to the point where i don't trust it anymore. things that used to score 75 in perf are now scoring 95, but the timeline still clearly shows a large difference.

**Comment by anishkny** [comment]
This is great @ryansolid! Would you be willing to add CI (e.g Travis/Circle) to demonstrate building the repo? That would be super.

**Comment by ryansolid** [comment]
@anishkny Cool I set it up to build with travis and deploy to the github pages. Had to configure rollup differently to make it clean, and now seem to be stuck with an entry js file that just imports the actual entry but it's only a 200byte weight so I will live for now until I figure it out. In any case CI now fully working.

**Comment by ryansolid** [comment]
Ended up not mattering much new version of Solid shrinks the bundle more. We now are at 11.1kb on initial load. Yeah that's 25% smaller than Svelte so I think the size is at a reasonable place.

Look forward to your review.

**Comment by ryansolid** [comment]
@anishkny @EricSimons  I don't want to be that guy because I can only imagine the overhead of maintaining a repo of this size. But it's been a few months and I was wondering if there was anything more I could do to help push push this along.

**Comment by bikeshedder** [comment]
Please add SolidJS. I'm really looking forward to the 2020 update of `A RealWorld Comparison of Front-End Frameworks with Benchmarks` and see `Solid` included. It is a very strong contender and worth mentioning.

**Comment by whatisaphone** [comment]
I think this would be a solid addition to the list

**Comment by Dan-Do** [comment]
I am now ready to learn this Solid frontend framework. Though it's now behind mikado in the bechmark but it's more active.

**Comment by ryansolid** [comment]
@Dan-Do Glad to hear your interest. Solid and Mikado differ in a few ways other than performance as Solid offers more higher level features, and the approach Solid uses in the benchmark scales beyond tying data to a single template.

I do think Mikado has really pushed the envelope though so I look forward to competing with it again when their benchmark implementation is fixed to be properly keyed.

**Comment by ryansolid** [comment]
@anishkny @EricSimons I will ask again if there is something I can do to help this along. I do understand this is just a matter of not really having time to review any implementations and I'm not in any real rush. But I'd love to get in before the comparison article goes out next year. I just missed the cycle of merges that got in this years article. But I'd love to be able to have Solid in next years.

**Comment by steve8708** [comment]
would really love to see this in as well

**Comment by bencun** [comment]
Looking forward to seeing Solid implementation here, so much potential in that lib.

**Comment by ryansolid** [comment]
Well looks like I got us added to the new website. So I will see how this plays out as it is released and close the issue here if appropriate. But it's something. See it here: https://realworld.mvila.me/

**Comment by redbar0n** [comment]
Maybe creating a PR with it (referencing this issue) would make it easier for them?

Also, remember: _"we require a minimum of one unit test with every repo"_ https://github.com/gothinkster/realworld/tree/master/spec

**Comment by jcuenod** [comment]
+1 for adding Solid here...

**Comment by mvila** [comment]
Hi, @ryansolid!

Apologies for the delay in reviewing your implementation, the maintenance team had very limited availability and we've recruited new members to help with the project.

I've added your implementation to the list of frontends (#601). The README should be autogenerated within 24 hours.
