### ISSUE TITLE
Hoplon frontend

### ISSUE THREAD

**Issue by rlander** [gothinkster/realworld#475]
I've implemented RealWorld with Clojurescript + Hoplon. Feature wise it is complete, just needs your review.

Repo: https://github.com/rlander/conduit
Live demo: https://hoplon-realworld.netlify.com/

Todo:

- [x] :checkered_flag: Fork the starter repo & post the link in this issue.
- [x] :art: Create logo for repo & update issue status.
- [x] :hammer:  Implement all of Conduit's functionality per the spec & API
- [x] :eyes: Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] :tada: Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by anishkny** [comment]
This is great @rlander !!!

Would you be able to add CI (e.g. Travis/Circle) to show how to build this repo - that would be awesome!

Waiting for: https://github.com/rlander/conduit/issues/1

**Comment by rlander** [comment]
@anishkny thanks for spending the time and effort to review it! I'll add the CI asap.

**Comment by rlander** [comment]
@anishkny CircleCI added! here: https://github.com/rlander/conduit/pull/2 :rocket:

**Comment by rlander** [comment]
@anishkny what's the process for making a repo official? Does anything need to happen next? Thanks!

**Comment by mvila** [comment]
Hi, @rlander!

Apologies for the delay in reviewing your implementation. The maintenance team had very limited availability, and we've recruited new members to help with the project.

I've added your implementation to the list of frontends (#602). The README should be autogenerated within 24 hours.
