### ISSUE TITLE
Framework-X

### ISSUE THREAD

**Issue by alex-dixon** [gothinkster/realworld#478]
Hello! 

Framework-X is a new front end Javascript framework leveraging algebraic effects. We've created a RealWorld example for it here: https://github.com/CoNarrative/framework-x/blob/master/examples/realworld

Logo: 

![image](https://raw.githubusercontent.com/CoNarrative/framework-x/master/examples/realworld/project-logo.png)

https://raw.githubusercontent.com/CoNarrative/framework-x/master/examples/realworld/project-logo.png

Let me know if there's anything else required. 

Thanks!

**Comment by anishkny** [comment]
Awesome! Looks like when you click on a user profile from global feed, you get error:

```
undefined is not an object (evaluating 'user2.username')
```

Also, hover pointer for links should be finger but its the text selection icon right now. Please see this for reference:

https://react-redux.realworld.io/

**Comment by alex-dixon** [comment]
@anishkny Thanks! Both issues should be fixed now.

**Comment by alex-dixon** [comment]
Hello! Just checking in on this issue and what else is required to include Framework-X in the repo.

**Comment by mvila** [comment]
Hi @alex-dixon!

Apologies for the delay in reviewing your implementation. The maintenance team had very limited availability, and we've recruited new members to help with the project.

It seems that the development of the Framework-X framework is stopped. If it's the case, I'm sorry, but I don't think we can list your implementation.

**Comment by alex-dixon** [comment]
No problem. It hasn’t stop just have had delays getting it out there. Any chance of a review? I’m available for whatever I can do on my end.

**Comment by mvila** [comment]
I think you should continue working on your framework until you are able to release a final version (the current version is 1.0.0-alpha.3). Then, it would be nice to battle test it a bit with some production applications. I close this PR for now. Feel free to create a new PR when you want to submit your implementation again.

**Comment by alex-dixon** [comment]
It’s been battle tested in many production applications. We’ve also had prior non alpha releases. The alpha is just showing as the latest because of semver I think.

**Comment by mvila** [comment]
Nope. It is not related to semver. It is because this version is published with the npm distribution tag 'latest'.

**Comment by alex-dixon** [comment]
Well the alpha is the latest. 😊

If a latest published version number without “alpha” in it is required to put a link to our example here I can see what I can do. Is that what you’re saying?

**Comment by mvila** [comment]
What I am saying is that we cannot list an implementation using a framework that doesn't provide a final/stable version.

Another issue is that your implementation is currently in the same repo as your framework. It would be better to move it to a dedicated repo so that people can clone/fork it and post issues about it more easily.
