### ISSUE TITLE
GraphQL Ruby + Next.js + Apollo Client

### ISSUE THREAD

**Issue by lifeiscontent** [gothinkster/realworld#482]
https://github.com/lifeiscontent/realworld

**Comment by lifeiscontent** [comment]
CC: @EricSimons

**Comment by lifeiscontent** [comment]
CC: @anishkny

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
