### ISSUE TITLE
404 error if username contains a dot

### ISSUE THREAD

**Issue by NWylynko** [gothinkster/realworld#484]
if a user sets there username so it contains a dot, the api will return a 404 error when requesting the user data. i set my username to nick14.4 but when i send a request to [http://conduit.productionready.io/api/profiles/nick14.4](http://conduit.productionready.io/api/profiles/nick14.4)  it returns a 404. on the demo website going to a users page that has a dot in the username just kicks you back to the home page. for example if u go to my profile [https://demo.realworld.io/#/@nick14.4](https://demo.realworld.io/#/@nick14.4) it just redirects to https://demo.realworld.io/#/

**Comment by ambrt** [comment]
There something slightly different going on. Basically the api is cutting the name of user after dot.
so for example "asdf.asdf" is retrieved as "asdf".

If someone will happen to be named "asdf.asdf" he will get profile of different user named just "asdf"

**Comment by geromegrignon** [comment]
Closing this issue as the new temporary server (https://realworld-temp-api.herokuapp.com/api) doesn't include this bug.
