### ISSUE TITLE
React (on hooks) + Typescript + mobx-state-tree 

### ISSUE THREAD

**Issue by airyboy** [gothinkster/realworld#485]
Hi guys, I'm developing another frontend implementation here https://github.com/airyboy/react-mobx-state-tree-typescript-realworld-example-app. Well, I've almost finished, but it needs some polishing.

**Comment by sunndeath** [comment]
Is it relevant?

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
