### ISSUE TITLE
Kotlin + Spring Boot + WebMvc/WebFlux

### ISSUE THREAD

**Issue by Anddd7** [gothinkster/realworld#486]
Hi guys, 

I usually work on backend service development, I feel great to use Kotlin + Spring Boot in the backend to instead of Java. So I create some templates of Kotlin/Spring in last few weeks. :bowtie:

**What I use**
- Java 11
- Kotlin 1.3.70
- Spring Boot 2.2.4.RELEASE
- Dockerfile, docker-compose of postgres for local development
- unit test and integration test demo
- DDD and architecture test

**Templates**
- [Kotlin + SpringBoot/WebMvc](https://github.com/Anddd7/kotlin-spring-template)
- [Kotlin + SpringBoot/WebMvc + DDD](https://github.com/Anddd7/kotlin-spring-ddd-template), using "adapter-port architecture"
- [Kotlin + SpringBoot/WebFlux](https://github.com/Anddd7/kotlin-spring-webflux-template), using WebFlux and Kotlin Coroutine to build backend
- [Kotlin + SpringBoot/WebFlux + DDD](https://github.com/Anddd7/kotlin-spring-webflux-ddd-template)

> This is the [“incubator”](https://github.com/Anddd7/backend-skeleton) of my templates :)

I have already seen a demo here [Kotlin/Spring](https://github.com/gothinkster/kotlin-spring-realworld-example-app), but it seems out-of-date.
If someone is interested in these template, I can migrate they as a "realworld" or raise a PR to extend the existing kotlin-spring-realworld-example-app. :beers::beers:

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
