### ISSUE TITLE
Wesib

### ISSUE THREAD

**Issue by surol** [gothinkster/realworld#487]
I have created a frontend implementation using Wesib: https://github.com/wesib/realworld-app
Demo is here: https://wesib.github.io/realworld-app/

Wesib utilizes web components.

Wesib is in beta stage now. RealWorld implementation is a good practical exercise of the framework usage, and lead to several improvements to it.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
