### ISSUE TITLE
Drogon(C++) + postgres

### ISSUE THREAD

**Issue by arslan2012** [gothinkster/realworld#489]
[WIP project](https://github.com/arslan2012/drogon-realworld-example-app)
I'm a little rusty on C++ tests, might need some help with lt later

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
