### ISSUE TITLE
🗄🔧 Koa.js(Node.js) + knex(SQL)

### ISSUE THREAD

**Issue by dimonnwc3** [gothinkster/realworld#49]
# Current Status

- ### Codebase in progress:<br /> [dimonnwc3/node-koa-realworld-starter-kit](https://github.com/dimonnwc3/node-koa-realworld-starter-kit)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/koa](https://gitter.im/realworld-dev/koa)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Awesome! Just updated the issue status, created [a gitter room](https://gitter.im/realworld-dev/koa) for us to manage collaborator coordination, and created the logo for your repo's readme 👍:

![koa2](https://cloud.githubusercontent.com/assets/556934/25393827/572420f2-2991-11e7-93a7-d1751d59b6f4.png)

**Comment by dimonnwc3** [comment]
@EricSimons first version is here, could you check it, please?

**Comment by EricSimons** [comment]
@dimonnwc3 awesome!! Checking it out now 👍

**Comment by EricSimons** [comment]
@apai4 can you take a peek at this too?

**Comment by EricSimons** [comment]
@dimonnwc3 what version of node are you using for it? I'm getting errors due to async/await not being supported :(

**Comment by dimonnwc3** [comment]
@EricSimons I use latest stable version 7.10
you can follow this guide to run the app: https://github.com/dimonnwc3/node-koa-realworld-starter-kit#getting-started

**Comment by EricSimons** [comment]
Got it working! Found a bug — when adding a new comment, the server response upon creation attaches the article's author instead of the comment author. I'm thinking that maybe it's this line? https://github.com/dimonnwc3/node-koa-realworld-starter-kit/blob/master/src/controllers/comments-controller.js#L73

**Comment by dimonnwc3** [comment]
thanks, you are right. I fixed it

**Comment by EricSimons** [comment]
Looks good! 

@tj @jonathanong would either of you (or someone else in the Koa community) be able to provide a quick 👍  or 👎  on this codebase before we mark it 1.0? 🙏

**Comment by EricSimons** [comment]
Status update: Still trying to get a hold of _anyone_ in the Koa community who can look this codebase over. I posted [an issue](https://github.com/koajs/koa/issues/979) over in the Koa repo as well.

@dimonnwc3 any chance you know some folks in the Koa community who could help review here? :)

**Comment by dimonnwc3** [comment]
@EricSimons  it's very similar to `express/connect` but uses promises out of the box to building simple middleware

actually, I switched from express to koa for a long time and can do a review, but not for himself :-)

so people from the express world could do it as well, but they need good knowledge about new ES features like promises and async-await

Another point is working with a database. Knex is a just query builder and there is no ORM or some relation management, so I have to write queries manually.

For the first version, I implemented functionality with logical joins on the application level.
In future, I will try to do some optimizations and move possible joins to DB level to increasing the performance.

So review, some suggestions, and contributions for this part would be great as well :)

**Comment by EricSimons** [comment]
@dimonnwc3 awesome! If no one from the Koa community jumps in here within the next day or two, I'm just going to approve it & list on the readme :)

**Comment by blacksonic** [comment]
@EricSimons Is there space for koa + mongo next to this example?

**Comment by dimonnwc3** [comment]
@EricSimons ping you to don't forget about this repo :)

**Comment by EricSimons** [comment]
@blacksonic of course! Perhaps you could fork this repo and swap out knex for mongo?

@dimonnwc3 I didn't! :) Spinning up a repo now under the main org

**Comment by EricSimons** [comment]
@dimonnwc3 just added you to https://github.com/gothinkster/koa-knex-realworld-example — going to list this on the main readme in a few minutes, awesome work!! 💪🎉

**Comment by dimonnwc3** [comment]
@EricSimons great 👍

**Comment by EricSimons** [comment]
Added! Closing this issue; future bugs/questions/etc should be posted in the repo itself: https://github.com/gothinkster/koa-knex-realworld-example

**Comment by blacksonic** [comment]
@EricSimons I would rather start from scratch, narrow it down and copy parts, this Koa + Knex example feels bit too complicated for me as a learning repository.

**Comment by EricSimons** [comment]
That's totally fine as well — go ahead and create a new issue for Koa + Mongo, fork the starter kit, and I'll update the issue's status :)

**Comment by ppot** [comment]
Thanks! That's what I needed to understand `async/await` with Koa and Knex!
