### ISSUE TITLE
Micronaut backend implementation

### ISSUE THREAD

**Issue by alexey-lapin** [gothinkster/realworld#491]
Hi,

There is an implementation of the realworld backend with Micronaut, it is ready and passed all tests. 
The repository is here: https://github.com/alexey-lapin/realworld-backend-micronaut

Thanks

**Comment by tamershahin** [comment]
Hi @alexey-lapin ,
I immediately though of Micronaut when I stumbled on this project! glad that you worked on it.. do you know why your PR is not being merged?

**Comment by alexey-lapin** [comment]
Hi @tamershahin! No, I don't know. I assume that real-world repo is in low activity mode as there are lots of PRs which are not being merged.

**Comment by tamershahin** [comment]
it's sad!
