### ISSUE TITLE
Dropwizard 2

### ISSUE THREAD

**Issue by srbe** [gothinkster/realworld#494]
Hello guys, 

In the last period I started learning Dropwizard and as an exercise I tried to implement the RealWorld backend specifications.

The project is in this repository: https://github.com/srbe/dropwizard-realworld-example-app

I decided to open this new issue because the existing Dropwizard issue (https://github.com/gothinkster/realworld/issues/95) seems to be inactive for a long time and the associated repo is based on Dropwizard 1.1.0 & Hibernate (while the new implementation is Dropwizard 2.0.8 & JDBI3).

@EricSimons

Please let me know if i missed anything.
Thanks

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
