### ISSUE TITLE
Meteor fullstack

### ISSUE THREAD

**Issue by peernohell** [gothinkster/realworld#497]
This will be a fullstack implementation of real world app with Meteor

# Current Status

Codebase in progress:
https://github.com/peernohell/meteor-realworld-example-app

Todo:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

**Comment by peernohell** [comment]
Hello,

I just release a first version on [heroku](https://conduit-meteor.herokuapp.com/) (with free version so it may be off when you will go to it)
As it's a fullstack and it use DDP with pubsub to manage data, their is no API.

**Comment by peernohell** [comment]
@EricSimons , I create a log (base on others) Here it is https://github.com/peernohell/meteor-realworld-example-app/blob/master/logo.png

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
