### ISSUE TITLE
🗄🔧 Slim

### ISSUE THREAD

**Issue by silentworks** [gothinkster/realworld#50]
# Current Status

- ### Codebase in progress:<br /> [alhoqbani/realworld-slim](https://github.com/alhoqbani/slim-php-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/php-slim](https://gitter.im/realworld-dev/php-slim)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by EricSimons** [comment]
Awesome! Just updated the issue status, created [a gitter room](https://gitter.im/realworld-dev/php-slim) for us to manage collaborator coordination, and created the logo for your repo's readme 👍:

![slim](https://cloud.githubusercontent.com/assets/556934/25393250/d935af54-298f-11e7-8dd9-b17a71f8698f.png)

**Comment by EricSimons** [comment]
@silentworks FYI some folks in the Gitter channel (https://gitter.im/realworld-dev/php-slim) are asking q's regarding what the DB layer will be, etc

**Comment by silentworks** [comment]
As I won't have the time, I am transferring this project over to @railto, will change the codebase link above to match this also.

**Comment by alhoqbani** [comment]
Hi guys, are you are still working on this? I would like to build the app.

**Comment by silentworks** [comment]
@alhoqbani yes this is something we will be working on

**Comment by alhoqbani** [comment]
Can I participate with you ? I already built something.  check [my repo](https://github.com/alhoqbani/slim-php-realworld-example-app)

**Comment by alhoqbani** [comment]
I finished the app. Here is a live demo: [https://slim-realworld.herokuapp.com/api/articles](https://slim-realworld.herokuapp.com/api/articles)

And here is another demo with angular as a frontend linked with the slim as backend [https://angular-realworld.herokuapp.com](https://angular-realworld.herokuapp.com)


Should I make a separate issue proposing my codebase? @EricSimons

**Comment by Cameron-C-Chapman** [comment]
@SandeeshS would have time to take a look at this from a code review point of view? I glanced through it and it looked fine but it's been a while since I did any php.

@alhoqbani My only feedback would be to add some more info to the README. Assume someone has never used the Slim framework. Other than composer install are there any relevant notes? How do you run tests, what is significance of the architecture and directory structure, etc. I think @SandeeshS  [Laravel repo ](https://github.com/gothinkster/laravel-realworld-example-app) is a great example of adding plenty of information to the README.

Other than that I think this is ready for listing on the README. 🎉

**Comment by alhoqbani** [comment]
I decided to wait for the peer-review before writing the README, just in case there is any comments on the structure of the code. 

However, I will prepare more detailed on the architecture and directory structure in the README soon.

**Comment by silentworks** [comment]
I have reviewed the code @alhoqbani and it is definitely the approach I would have taken. I think it shows off quite a few of the features that Slim provide.

**Comment by silentworks** [comment]
I have changed the codebase link above to match @alhoqbani repo as I think it should be used as the official submission. Thanks for deciding to this @alhoqbani, I am happy that someone else was able to complete this as most of us on the team have gotten real busy lately.

Hat tip to you @alhoqbani

**Comment by alhoqbani** [comment]
Thanks @silentworks, glad to hear that from you.

**Comment by EricSimons** [comment]
Excellent, excellent work @alhoqbani. That readme especially is so thorough & incredibly well done! Also, @silentworks thanks so much for chiming in here with your expertise and insight! It's seriously such an honor to have amazing folks like y'all helping push the RealWorld project forward. Thanks so much. ❤️

I've gone ahead and spun up the official repo (https://github.com/gothinkster/slim-php-realworld-example-app) and will be listing it on the homepage shortly! 🎉 

Again, amazing work y'all!!

**Comment by alhoqbani** [comment]
Thanks @EricSimons, although I'm not done with the README yet. It still needs some editing, and I was hoping someone from the Slim community could review it as well.

**Comment by EricSimons** [comment]
@alhoqbani no sweat! We can just push any updates req'd to the new repo :) Btw, do you know anyone in the Slim community I could ping about coming in to help review? Or perhaps @silentworks could review the new stuff in the readme? Lmk!

**Comment by alhoqbani** [comment]
unfortunately, I 'don't know any one :(

**Comment by silentworks** [comment]
Yes I will review it. I am from the Slim community.
