### ISSUE TITLE
The actual "mother of all demos"

### ISSUE THREAD

**Issue by gabssnake** [gothinkster/realworld#501]
Hi, thanks for the great work !

Was wondering if you knew about the actual [Mother of all demos](https://en.wikipedia.org/wiki/The_Mother_of_All_Demos) in computer science.

It would be great if the readme could reference or otherwise honor the work.

Best,

**Comment by sunndeath** [comment]
done: https://github.com/gothinkster/realworld/pull/512
Could you please approve it?

@EricSimons 
@gabssnake

**Comment by gabssnake** [comment]
Awesome !
