### ISSUE TITLE
Go + gRPC

### ISSUE THREAD

**Issue by raahii** [gothinkster/realworld#503]
Hi Everyone :smile:

I implemented realworld backend using Go + gRPC. The repository is [here](https://github.com/raahii/golang-grpc-realworld-example).

Of course, this server provides a RESTful JSON API by using [grpc-gateway](https://github.com/grpc-ecosystem/grpc-gateway)! There may be room for improvement in performance, but for now it passes all [tests](https://github.com/gothinkster/realworld/blob/master/api/run-api-tests.sh) and satisfies the API spec. 🍺

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
