### ISSUE TITLE
crank.js

### ISSUE THREAD

**Issue by ryhinchey** [gothinkster/realworld#504]
I'm creating a realworld app for a new ui library [crank.js](https://crank.js.org/).

The repo is [here](https://github.com/ryhinchey/crank-realworld-example-app)

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
