### ISSUE TITLE
Completed KVision (Kotlin/JS)

### ISSUE THREAD

**Issue by rjaros** [gothinkster/realworld#505]
Hi everyone,

I've created a RealWorld application (frontend part) with [KVision](https://github.com/rjaros/kvision). It's now complete and needs your review. TravisCI deployment to GitHub Pages is configured and tested.

Sources: https://github.com/rjaros/kvision-realworld-example-app
Demo: https://rjaros.github.io/kvision-realworld-example-app

Todo:
- [x] :checkered_flag: Fork the starter repo & post the link in this issue
- [x] :art: Create logo for repo & update issue status (@EricSimons)
- [x] :hammer: Implement all of Conduit's functionality per the spec & API
- [ ] :eyes: Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] :tada: Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by rjaros** [comment]
@abdusabri This version should be labelled "frontend".

**Comment by abdusabri** [comment]
> @abdusabri This version should be labelled "frontend".

Thanks for the correction @rjaro!, I've fixed it  😊

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
