### ISSUE TITLE
Completed Koa + Typescript + TypeORM Backend

### ISSUE THREAD

**Issue by eflem00** [gothinkster/realworld#507]
Hey there, I've fully implemented a RealWorld Backend to spec using Koa + Typescript + TypeORM. The API tests are currently passing and the UI appears to work with my implementation locally.

Source: https://github.com/eflem00/koa-boilerplate

I never forked the starter as I found out about RealWorld in the middle of building this. Hopefully that's okay

Todos:
- [ ] 🏁 Fork the starter repo & post the link in this issue
- [ ] 🎨 Create logo for repo & update issue status (@EricSimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by eflem00** [comment]
@anishkny Feel free to review as well

**Comment by mvila** [comment]
Hi, @eflem00!

Apologies for the delay in reviewing your implementation. The maintenance team had very limited availability, and we've recruited new members to help with the project.

I've added your implementation to the list of backends (#603). The README should be autogenerated within 24 hours.
