### ISSUE TITLE
Deno js + oak framework

### ISSUE THREAD

**Issue by mohidkazi** [gothinkster/realworld#508]
Hi there every one , i am really happy to start this project.
this project will consist of deno as a backend server and oak as the middleware framework and as for database i am using mysql.

i have not started project yet, as this is the first day of this issue, in few days i will update this thread and add all the necessary information regarding the repository.
[Note- this project may take a while to complete, as i am a full time employee and i hardly get any spare time to work on side project(s) except for sundays :/ ].

I would love any contributions, especially in the unit testing department.
https://github.com/mohidkazi/deno-oak

**Comment by Julien-Broyard** [comment]
Yeah sure, I'll try to help you when the repo will be out !

**Comment by webpreneur** [comment]
@mohidkazi, is there any repo yet?

**Comment by mohidkazi** [comment]
@webpreneur , yes
[here](https://github.com/mohidkazi/deno-oak) you go
but the repo is still incomplete as i do not get enough time to spend on it

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
