### ISSUE TITLE
GraphQL, Phoenix and React fullstack app

### ISSUE THREAD

**Issue by sunndeath** [gothinkster/realworld#509]
Could you please assign this example on me?

**Comment by sunndeath** [comment]
@EricSimons

**Comment by barnabasJ** [comment]
hi @sunndeath, I'm also working on a phoenix/graphql version. If you'd like to share/discuss something let me know.

**Comment by sunndeath** [comment]
> hi @sunndeath, I'm also working on a phoenix/graphql version. If you'd like to share/discuss something let me know.

hi, @barnabasJ,
ok.
I've configured the project for running Phoenix with "Create react app": https://github.com/sunndeath/elixir-phoenix-graphql-react-realworld-example-app. I'm going to continue my version of implementation, because this is very interesting for me and I did not receive answers about the possibility of making an implementation based on another stack.
