### ISSUE TITLE
Crank.js & Parcel

### ISSUE THREAD

**Issue by waynebaylor** [gothinkster/realworld#511]
Crank.js implementation of the RealWorld Frontend spec.

**Repo:** https://github.com/waynebaylor/realworld-starter-kit
**Demo:** https://waynebaylor.github.io/realworld-starter-kit/

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
