### ISSUE TITLE
OpenLiberty + JPA + (MicroProfile)

### ISSUE THREAD

**Issue by dshimo** [gothinkster/realworld#513]
Hello there,

Submitting a backend request for OpenLiberty. 
Fork: https://github.com/dshimo/realworld-starter-kit

The test suite is run in Travis. Would love a review!

Todos:
- [x] 🏁 Fork the starter repo & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@EricSimons)
- [x] 🔨 Implement all of Conduit's functionality per the spec & API
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by dshimo** [comment]
@anishkny 
Review is open for anyone. Would appreciate any comments or responses.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
