### ISSUE TITLE
FastAPI

### ISSUE THREAD

**Issue by nsidnev** [gothinkster/realworld#520]
Hi!

I've an implementation of the realworld backend with [`FastAPI`](https://fastapi.tiangolo.com/) and `PostgreSQL` [here](https://github.com/nsidnev/fastapi-realworld-example-app). There are 2 CIs for tests (one for the spec from postman and one for tests from pytest), and both pass. Also, as far as I know, it works with [React Frontend](https://github.com/gothinkster/react-redux-realworld-example-app) (at least [this](https://github.com/nsidnev/fastapi-realworld-example-app/issues/3) is closed, but I did not check it myself).

Repo: https://github.com/nsidnev/fastapi-realworld-example-app
Deploy: https://frw.nsidnev.dev
Swagger: https://frw.nsidnev.dev/docs

Thanks!

**Comment by cmrd-a** [comment]
I think there is no point in waiting FastAPI #400 for and it is worth adding this example.

**Comment by abdusabri** [comment]
Hi @nsidnev,

Apologies for the delay in getting back to you, the maintenance team had very limited availability and we've recruited new members to help with the project. 

Could you please add it here https://github.com/gothinkster/realworld/blob/master/etc/backend-repos.yaml, open a PR, and mention me? And I will review it and take care of merging it and making sure that the README is updated accordingly (as it is auto-generated) 🙂
