### ISSUE TITLE
Would you like to get a neo.mjs multi Browser Window version of the RealWorld App?

### ISSUE THREAD

**Issue by tobiu** [gothinkster/realworld#523]
Hello everyone,

this would slightly leave the scope of the original definition.

We could expand the Single Page RealWorld App into multiple Browser Windows very easily, e.g. the articles details view & the settings view.

Meaning:
1. Only load the framework & app once for all Windows
2. Moving Component trees around Windows while keeping the same JS instances
3. Dom events will still work inside the new Window

I just did the same with the Covid App:

![sw_covid](https://user-images.githubusercontent.com/1177434/85075488-93375100-b1be-11ea-84dd-a1abc1ee5a2f.png)

More background infos here (friends link):

https://medium.com/swlh/expanding-single-page-apps-into-multiple-browser-windows-e6d9bd155d59?source=friends_link&sk=bbfe1dada95c5674669e463f93360822

Just give me a heads up, in case this is interesting for you. I could probably get it done within one hour.

Best regards,
Tobias

**Comment by YukiSakuraVN** [comment]
That sounds great :)

**Comment by geromegrignon** [comment]
Hello,

Thanks for the suggestion.

As the goal of the specs is to create a simple MVP product, such feature is out of our scope.
So we won't include it.
