### ISSUE TITLE
Golang + Gokit

### ISSUE THREAD

**Issue by xesina** [gothinkster/realworld#534]
Hello,
I'm working on a new implementation using Golang and [gokit](https://github.com/go-kit/kit) 

Work in progress at https://github.com/xesina/gokit-realworld

Also, here's my previous completed work on the [echo](https://github.com/labstack/echo) implementation if you're interested 😉 
https://github.com/xesina/golang-echo-realworld-example-app

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
