### ISSUE TITLE
Any stack can join?

### ISSUE THREAD

**Issue by leocavalcante** [gothinkster/realworld#54]
There are any constraints about the submitted stacks? They should be popular, widely used or obey any restrictions?
I'm willing to submit some work using https://siler.leocavalcante.com/
Thanks!

**Comment by EricSimons** [comment]
@leocavalcante Nope, no constraints 🙌 We'll accept _any_ stack implementation (as long as it passes the community's quality assurance review :)

**Comment by leocavalcante** [comment]
Awesome :smiley:
