### ISSUE TITLE
Typical time needed for a front-end port

### ISSUE THREAD

**Issue by kashifimran** [gothinkster/realworld#542]
I am considering a port of realworld front-end. I went over the list of issues and also used web search but could not find out what a typical timeline for a port is. Can anyone please shed light how many man-hours typically it takes to build the front-end of this app using the provided starter-kit?

Thanks in advance.

**Comment by anishkny** [comment]
It depends on framework complexity, your expertise in it etc. The starter kit is pretty barebones. You can look at the commit histories of some of the popular implementations to get an idea how long one would take: [React](https://github.com/gothinkster/react-redux-realworld-example-app/commits/master) | [Angular](https://github.com/gothinkster/angular-realworld-example-app/commits/master) | [Vue.js](https://github.com/gothinkster/vue-realworld-example-app/commits/master)

**Comment by kashifimran** [comment]
@anishkny Thanks for the kind reply. I think it's quite hard to estimate time by looking at the history. 1 commit can be after 10 days. or a single hour may see 10 commits. 

Would you say 10 hours is a good estimate for someone who knows what they are doing?
