### ISSUE TITLE
[FrontEnd] PureScript + React

### ISSUE THREAD

**Issue by jonasbuntinx** [gothinkster/realworld#544]
Hi,

I was inspired by @thomashoneyman 's [implementation](https://github.com/thomashoneyman/purescript-halogen-realworld) of the Real World spec using [Halogen](https://github.com/slamdata/purescript-halogen). 

I work professionally in [PureScript](https://www.purescript.org/), but we're using [React](https://reactjs.org/) instead of Halogen. So I wanted to create a PureScript+React version of the RealWorld spec.

I have finished the implementation of the spec, but so far it has not been reviewed by anyone besides myself.

You can find the repository here: https://github.com/jonasbuntinx/purescript-react-realworld

**Comment by thomashoneyman** [comment]
This looks good! I haven't done a thorough review, but I've looked through the source and it looks like a competent, realistic implementation of the spec for PureScript + React.

**Comment by jonasbuntinx** [comment]
Quick update.
I have set up a hosted demo: https://purescript-react-realworld.netlify.app/
