### ISSUE TITLE
[Frontend] Vanilla PHP

### ISSUE THREAD

**Issue by Qclanton** [gothinkster/realworld#548]
Work in progress here:

Repo: https://github.com/concise-studio/real-world-frontend-php
Demo: https://real-world-frontend-php.concise-studio.com/

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
