### ISSUE TITLE
[FrontEnd] Elixir Phoenix LiveView

### ISSUE THREAD

**Issue by razuf** [gothinkster/realworld#552]
Hey folks!
I just created a RealWorld example application and wanted to share it here!

Elixir Phoenix LiveView is really awesome! Please have a look at it.
[More about LiveView here.](https://www.phoenixframework.org)

I'm writing a blog post inside Conduit. ;-) You can read it [here](https://realworld.gigalixirapp.com/article/frontend-with-elixir-phoenix-liveview-c9s0oh).

Or in any other Demo with the original realworld backend: ```https://conduit.productionready.io/api```

Please let me know if there's anything you need from me.

Thanks and have fun with Elixir! 😄

Current Status
Codebase: https://github.com/razuf/elixir-phoenix-liveview-realworld
Demo: https://realworld.gigalixirapp.com/

Todo:
- [x]  🏁 Fork the starter repo & post the link in this issue
- [x]  🎨 Create logo for repo
- [x]  🔨 Implement all of Conduit's functionality per the spec & API
- [ ]  👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ]  🎉 Tag v1 release, move repo to main org, and officially list it on the README!

**Comment by aton-py** [comment]
The demo is not working ;?

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there once the demo is fixed.
