### ISSUE TITLE
Raku / Cro / PostgreSQL - Backend Application

### ISSUE THREAD

**Issue by camstuart** [gothinkster/realworld#554]
Hi,

I'm putting together a real world api app here:
https://github.com/camstuart/raku-cro-realworld-example-api-app

Raku (formerly known as Perl6) is a member of the Perl family.
The library `Cro` I am using (ok, so kind-of a framework) is fast becoming the de facto standard in the Raku community for distributed systems. So it can do HTTP rest API's very well, but also full stack (server rendered html) also.

This project will provide the rest interface only. Once completed, I will use it as a basis for a full stack demo app that responds with HTML.

**Comment by camstuart** [comment]
Please label `backend` & `wip`

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
