### ISSUE TITLE
[Frontend]: React + Effector + Typescript

### ISSUE THREAD

**Issue by mg901** [gothinkster/realworld#557]
Good time, at the moment I'm finishing an example on React + [Effector](https://effector.now.sh/).

[repo](https://github.com/mg901/effector-react-realworld-example-app)

## Todo:

- [x] example app

- [x] styles

- [x] unit tests

- [x] readme

**Comment by mg901** [comment]
@StephenFluin @toddwest @icebob @anishkny, Greetings to you guys. I made an app with Effector + React. Please tell me what else is needed in order for you to publish it at home?

**Comment by mg901** [comment]
@Alonski, @sandeesh, @Cameron-C-Chapman, @apai4 Hello guys. If any of you have enough time, please add my application. For me and the entire Effector community, this really matters.

**Comment by geromegrignon** [comment]
Closing the issue as the implementation has been added on the website.
Thanks for your contribution !
