### ISSUE TITLE
[Backend] Laravel repo is unmaintained

### ISSUE THREAD

**Issue by lhsazevedo** [gothinkster/realworld#564]
The original maintainer of the [laravel-realworld-example-app](https://github.com/gothinkster/laravel-realworld-example-app) repository (@sandeesh) appears to be inactive since 2017.

We already have a [Pull Request](https://github.com/gothinkster/laravel-realworld-example-app/pull/23) upgrading Laravel from version 5.4 to 5.5 (released on August 30th, 2017). I've suggested some changes but the creator (@hoseinz3) also seems to be inactive.

Laravel is on version 8 at the moment. I've created [one Issue](https://github.com/gothinkster/laravel-realworld-example-app/issues) for every necessary upgrade step with a link to the respective guide. I'm also willing to contribute with some or all of those steps, just need to make sure that a maintainer will merge them :rocket:

**Comment by Dan-Do** [comment]
I guess this repo is also inactive :(

**Comment by sandeesh** [comment]
Hi there. I've been very busy taking up a big role in couple of startups and therefore wasn't able to keep the repo maintained. I'm going to spending the next week to keep this updated to the latest version of Laravel. I've merged the pending PRs for now.

I'm also open to transfer the repo ownership or add others as admin if someone would like to continue maintaining this. For now i'll get this updated to the latest Laravel version as this project is very helpful for newcomers who just start with the framework.

**Comment by lhsazevedo** [comment]
Hi @sandeesh, this is good news, thank you! If it's ok for you, I can contribute to the update process as well.

Regarding maintenance, I am willing and would like to apply to be one of the admins, how should I proceed?

**Comment by lhsazevedo** [comment]
Hi @geromegrignon and @mvila. Could you help us here?

**Comment by geromegrignon** [comment]
Hello @lhsazevedo, we aren't directly in charge of the implementations.

@sandeesh are you still open to onboard @lhsazevedo to maintain the implementation?

**Comment by lhsazevedo** [comment]
Oops, sorry @geromegrignon.

The Laravel implementation done by @sandeesh is really well done. But the repo dates back to 2017 when Laravel was at version 5 and now it's on version 8 already, on the way to 9 this year. This can be a bit frustating for newcomers :/

Unfortunally, he has been very busy with other roles (last commit was in 2017).

Let me also ping @EricSimons here as I have reached him back in December.

**Comment by lhsazevedo** [comment]
Ping @Cameron-C-Chapman

**Comment by geromegrignon** [comment]
@lhsazevedo If it's fine with you, i invite you to fork the project and to submit it as the new Laravel implementation.

**Comment by lhsazevedo** [comment]
Awesome, sure! I didn't do it before because I was afraid it wouldn't be merged.

I'll get back to you soon in an Pull Request. Thank you.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.

**Comment by lhsazevedo** [comment]
Thanks. I'm still working on the upgrade, will submit there when done.

**Comment by jhjvandenbroek** [comment]
Any news?

**Comment by mvila** [comment]
Hi @jhjvandenbroek and @jhjvandenbroek,

The [repo you are talking about](https://github.com/gothinkster/laravel-realworld-example-app) is marked as unmaintained on CodebaseShow (see at the bottom of the [backend page](https://codebase.show/projects/realworld?category=backend)).

If the other Laravel implementations are not satisfying, feel free to submit your own implementation. 😄
