### ISSUE TITLE
react/redux repo is unmaintained

### ISSUE THREAD

**Issue by ctrngk** [gothinkster/realworld#565]
Could you please update with hooks?

**Comment by saranshabd** [comment]
@anishkny I can take up this issue

**Comment by ahmadazizi** [comment]
I have experiences with Flask and react/redux repos, both code bases are outdated.
I don't recommend to try realworld anymore, you would be much more satisfied with more recent packages. In the react/redux world just create a project with:

`npx create-react-app my-app --template redux`

https://redux-toolkit.js.org/introduction/quick-start#using-create-react-app

**Comment by geromegrignon** [comment]
You should be able to find a newer implementation here : https://codebase.show/projects/realworld
