### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by loannaflip** [gothinkster/realworld#569]
- [realworld#sandeesh-s---admin](https://github.com/gothinkster/realworld#sandeesh-s---admin)
	- [github.com/SandeeshS](https://github.com/SandeeshS) - This page does not exist.

**Comment by iamdarshshah** [comment]
Hey @Uniminin 👋 

Thanks for pointing this out! This issue will get fixed by #516 😄 

The team will close this issue once the pending PR is reviewed/merged.
