### ISSUE TITLE
[Fullstack]: AskQL + Nodejs + Express + Web components

### ISSUE THREAD

**Issue by YonatanKra** [gothinkster/realworld#570]
Hi,
An amazing project is coming into fruition - [AskQL](https://github.com/xFAANG/askql/).
I've forked the beginning of the project and intend to work on it in the coming months.
https://github.com/YonatanKra/realworld-starter-kit

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
