### ISSUE TITLE
[Fullstack] Hasura + Elm

### ISSUE THREAD

**Issue by andrewMacmurray** [gothinkster/realworld#571]
I've put together a realworld 'inspired' version using Elm + Hasura - 'inspired' as it doesn't follow the official API spec or use the provided CSS, but wanted to try out graphql + Elm UI as alternatives

The repo is here: https://github.com/andrewMacmurray/realworld-hasura
And the app here: https://realworld-hasura.surge.sh

I had a lot of fun making it, the realworld app idea is brilliant!

Let me know if this would fit anywhere in this repo? Or any changes I could make to make it fit?

**Comment by geromegrignon** [comment]
Hello @andrewMacmurray,
We are currently onboarding a new team of maintainers for the project.
Our main focus is to add implementations following the specs.
As we may add a new version of the specs and the expectations, we'll then review your implementation.

**Comment by geromegrignon** [comment]
As we need to focus on standards based on the current specs, we can't include your implementation.
Great work though !
