### ISSUE TITLE
[Fullstack] Go + Buffalo

### ISSUE THREAD

**Issue by remast** [gothinkster/realworld#572]
Hi

I have implemented a version in [Go](https://golang.org/) using the [Buffalo](https://gobuffalo.io) framework:
https://github.com/remast/gobuff_realworld_example_app

It's a server side rendered go web application and therefore a fullstack implementation.

Cheers,
Jan

**Comment by geromegrignon** [comment]
Closing the issue as the implementation has been added on the website.
Thanks for your contribution !

**Comment by remast** [comment]
Thanks @geromegrignon! Does it need to be merged yet because I could not find it within the fullstack implementations.

**Comment by geromegrignon** [comment]
You can find it here : https://codebase.show/projects/realworld?category=fullstack
The current list being displayed into the Readme of the project will be removed soon so we don't update it anymore.
