### ISSUE TITLE
🗄🔧 F#

### ISSUE THREAD

**Issue by ALenfant** [gothinkster/realworld#58]
# Current Status

- ### Codebase in progress:<br /> [Korbin73/realworld-fsharp](https://github.com/Korbin73/realworld-fsharp)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/fsharp](https://gitter.im/realworld-dev/fsharp)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I've been trying to find a way to use F# to do a "real world" backend project and knowing Django already, I'd be very interested to compare the Realworld-Django project to one made in F#!

**Comment by EricSimons** [comment]
Great idea! Lets see if we can find some folks who know F# who'd be down to do this :)

**Comment by Korbin73** [comment]
I would like to work on something this!

**Comment by EricSimons** [comment]
Nope, you're the first @korbin73! Will update issue status after you post the repo link in here 👍

**Comment by Korbin73** [comment]
Done! [https://github.com/Korbin73/realworld-fsharp](Real world Fsharp)

I'll get started on the backend first :)

**Comment by ALenfant** [comment]
Thanks @Korbin73 that's really awesome of you. Can't wait to see the result! Take your time though :)

**Comment by EricSimons** [comment]
@Korbin73 just updated the issue status w/ gitter room we can use for collaborator coordination! Also, here's the logo you can use for your repo's readme:'

![fsharp](https://cloud.githubusercontent.com/assets/556934/25493539/3016f83e-2b3c-11e7-80b5-ff8dccf2ec4b.png)

**Comment by Korbin73** [comment]
Nice thanks. 😄

**Comment by lilred** [comment]
I'd love to help out, maybe we can start a Gitter for this repo?

**Comment by Korbin73** [comment]
There is one already set up: https://gitter.im/realworld-dev/fsharp

**Comment by Korbin73** [comment]
I'm currently finishing the core functionality of this project up. I have plenty of documentation and cleanup/robustness to add though.

**Comment by EricSimons** [comment]
@Korbin73 can't wait to see it!!

**Comment by Korbin73** [comment]
This should be good to go. I will be using this as my backed while working on the reasonml front end project so their may be some bug fixes through some that end to end testing.

**Comment by EricSimons** [comment]
@Korbin73 sorry about my delay here! I'm marking this as RFC and will get it moved over into the org's repo & main README tmrw morning :) Awesome work btw!!

**Comment by Korbin73** [comment]
Great. Thanks.

**Comment by EricSimons** [comment]
@Korbin73 just added you to the new repo and listed it on the readme! 🎉  Thanks so much!! I can't wait to see the reasonml frontend too :)
