### ISSUE TITLE
[Backend] Grape

### ISSUE THREAD

**Issue by jtrtj** [gothinkster/realworld#589]
![Logo](https://raw.githubusercontent.com/jtrtj/grape-realworld-example-app/master/logo.png)

@dtsehl and I are making a Grape/Ruby backend.

https://github.com/jtrtj/grape-realworld-example-app

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
