### ISSUE TITLE
Add RealWorld virtualization/containerization? (+ install CLI)

### ISSUE THREAD

**Issue by ppo** [gothinkster/realworld#590]
Wouldn't it be useful to include virtualization besides frontends and backends?  
And a CLI tool to install and configure everything?

For example:

- Run `npx realworld-install`
- Select a virtualization: `Kubernetes`
- Select a backend: `Elixir/Phoenix`
- Select a database: `PostgreSQL`
- Select a frontend: `Svelte/Sapper`
- Select a deployment platform: `local` (or `DigitalOcean`)
- _Some configuration questions…_
- Successfully created!
- To manage your app: _"commands cheat sheet…"_

__  
_Keywords: container docker_

**Comment by senorsmile** [comment]
I think this is exactly what we need.  This would be perfect to showcase "Real World DevOps". 

I could see different flavors: 
CICD tools - Jenkins, etc.
Build scripting - ...
Packaging formats - Helm, Apt, tar.gz etc.
Cloud Provisioning - Terraform, Cloud Formation etc.
Orchestration - Heroku, Kubernetes etc.
Deployment Methods - Ansible, Gitlab CI, Spinnaker etc.

We'd probably want to group them all as "devops options", with maybe CICD tooling being separate and distinct (i.e. the same way that front end and back end are unique and pluggable).

**Comment by geromegrignon** [comment]
Hello,

a CLI would be way too huge for us to maintain as it would require expertise not only on each option but on the way to configure them all together.

However extending current scopes (frontend/backend/fullstack) with orchestration, deployment methods... would make sense. We would need people to contribute to define related specs.

**Comment by geromegrignon** [comment]
We decided not how address these suggestions :

A CLI would be too big for us to maintain and somehow out of the scope of this project : the goal is to provide examples based on a given spec to be able to compare easily languages/frameworks. To provide a way to bootstrap quickly a full stack solution is different from the scope of the project.

About 'RealWorld DevOps', it's a great idea but we think it would worth to get a proper repository and people willing to create/maintain it.

Thanks for the ideas though.
