### ISSUE TITLE
Implement GraphQL + Apollo/Relay for the Node + React codebases

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#6]
Originally brought up by @kentcdodds [here](https://twitter.com/kentcdodds/status/851201827857199105); further discussion [here](https://twitter.com/ericsimons40/status/851214707654447104).

Opening this issue to get a discussion going!

**Comment by thebigredgeek** [comment]
I can help with this (eventually)

**Comment by EricSimons** [comment]
Awesome! Wanna [fork the starter kit](https://github.com/gothinkster/realworld-starter-kit) and post the link here so that others can watch/help?

**Comment by thebigredgeek** [comment]
I don't have time right now, but I will see if I can connect you with people in the Apollo community who have more time than I do

**Comment by thebigredgeek** [comment]
I've been talking a bit with mxstbr [here](https://github.com/apollographql/graphql-tools/issues/313).  He might be willing to help with it.  He was mentioned in the tweet that you linked to above

**Comment by sibelius** [comment]
I think this boilerplate https://github.com/entria/graphql-dataloader-boilerplate can be used as a start point

I have this one for React Native + React Navigation + Relay https://github.com/sibelius/ReactNavigationRelay.

It is almost migrated to Relay Modern as well: https://github.com/sibelius/ReactNavigationRelay/pull/5

**Comment by stubailo** [comment]
This is a great idea! Unfortunately I don't have time to work on this myself but would love to help if I can.

**Comment by EricSimons** [comment]
@sibelius awesome! Would you be interested in taking lead on GraphQL/Relay?

@stubailo no worries — would be ❤️ if you could give feedback on the final code once it's ready!

**Comment by thebigredgeek** [comment]
@EricSimons would definitely encourage use of Apollo over Relay.  It seems to be getting more traction these days

**Comment by sibelius** [comment]
We can do both, Apollo, Relay and Relay Modern.

I can help with any questions for sure.
I don't have time to work on this myself

**Comment by EricSimons** [comment]
@leebyron do you know of anyone in the GraphQL community who might be interested in this?

**Comment by thebergamo** [comment]
@ericSimons I can help with the GraphQL implementation in the server side.

**Comment by EricSimons** [comment]
@thebergamo awesome! I just spun up a new issue for it (https://github.com/gothinkster/realworld/issues/46) — can you fork the starter kit and post it in the issue? I'll update the status afterwards 👍

**Comment by steveluscher** [comment]
I can chip away at a Relay Modern implementation, @EricSimons, @thebergamo.

**Comment by thebergamo** [comment]
@EricSimons done!

**Comment by EricSimons** [comment]
@steveluscher awesome! Just spun up a [new issue](https://github.com/gothinkster/realworld/issues/48) for it — can you fork the starter kit and post it in the issue? I'll update the status afterwards 👍

Also, I created [a gitter room](https://gitter.im/realworld-dev/graphql-relay-apollo) so that all of the folks working on graphql/apollo/relay can chat and coordinate (since they rely on each other) cc/ @thebergamo

**Comment by brwr** [comment]
It looks like this issue has been split into multiple other issues. Do we still need this one or can we close it?

**Comment by thebigredgeek** [comment]
@EricSimons I can handle Apollo if you give me a few weeks haha

**Comment by thebergamo** [comment]
@thebigredgeek all help will be very welcomed! until the end of week we will have a version of the server side graphql implemented with Apollo

**Comment by EricSimons** [comment]
@thebergamo @thebigredgeek should I create a new issue for the Apollo part of this (right now we have GraphQL and Relay issues)?

**Comment by thebergamo** [comment]
I'm planning using Apollo as a graphql server. Probably isn't necessary create a new issue.

**Comment by thebigredgeek** [comment]
@thebergamo apollo has `graphql-server`, but their main focus is `apollo-client` which is the most popular client-side graphql implementation.

**Comment by thebigredgeek** [comment]
@EricSimons same issue is probably fine

**Comment by stubailo** [comment]
@thebergamo and anyone else here: If you want, you can join the #realworld channel in the [Apollo Slack](http://dev.apollodata.com/#slack) to help coordinate an example, both server and client!

**Comment by thebergamo** [comment]
@stubailo I'm in! Thanks for the option!

**Comment by ap-o** [comment]
Is there any progress happening on the apollo/graphql example? 

I could definitely help, i did put something together last year, but i reckon an example here would make a lot more impact.

https://github.com/ap-o/intro

**Comment by dostu** [comment]
I have done a GraphQL implementation with React + Apollo front-end and Ruby on Rails back-end. 
Front-end - https://github.com/dostu/react-apollo-realworld-example-app
Back-end - https://github.com/dostu/rails-graphql-realworld-example-app
Demo - http://realworld-react-apollo.herokuapp.com/

Would be great to see other implementations, and mix and match them like we can with the REST API. For that, we should first decide on a schema. So far I have come up with this: https://github.com/dostu/rails-graphql-realworld-example-app/blob/master/GRAPHQL_API_SPEC.md. Would love to hear any opinions about it.

**Comment by siddhant1** [comment]
Still looking for it? I can hop on this one now.

**Comment by Ericnr** [comment]
Found https://github.com/thebergamo/realworld-graphql by @thebergamo which is pretty nice, just wish it was in express instead.

**Comment by aisensiy** [comment]
I am working on a java version GraphQL implementation recently after releasing GraphQL ecosystem is quite sophisticated recently. The code base is also https://github.com/gothinkster/spring-boot-realworld-example-app, the same place of the REST implementation, which means it reuse lots of common codes (such as database access, input validation).

The GraphQL schema is firstly copy from https://github.com/thebergamo/realworld-graphql. But I changed some details about pagination, comments: 

https://github.com/gothinkster/spring-boot-realworld-example-app/blob/master/src/main/resources/schema/schema.graphqls

The GraphQL code is using [dgs-framework](https://github.com/Netflix/dgs-framework) just release recently by Netflix.

**Comment by sibelius** [comment]
I have a Relay Real World example here https://github.com/sibelius/relay-workshop

it also has 12 practical exercises to help learning Relay hooks

it is a tiny social network https://react-europe-relay-workshop.now.sh/

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
