### ISSUE TITLE
Update Riot.js repositories

### ISSUE THREAD

**Issue by iq3addLi** [gothinkster/realworld#606]
Hi guys
The Riot repository has been updated.
I want the readme to be updated as follows.

(1) Riot.js v3 -> remove
(2) Riot.js v4 -> rename -> Riot

title|content
:---|:---
Repository| https://github.com/iq3addLi/riot_realworld_example_app
Demo| https://riot-realworld.addli.co.jp

Thanks.

**Comment by abdusabri** [comment]
Hi @iq3addLi 👋 

Could you please make the changes here https://github.com/gothinkster/realworld/blob/master/etc/frontend-repos.yaml, open a PR, and mention me? And I will review it and take care of merging it and making sure that the README is updated accordingly (as it is aut-generated) 🙂

**Comment by iq3addLi** [comment]
Thanks for responding!
