### ISSUE TITLE
🖥 🔧  ClojureScript

### ISSUE THREAD

**Issue by roman01la** [gothinkster/realworld#61]
# Current Status

- ### Codebase in progress:<br /> [roman01la/cljs-rum-realworld-example-app](https://github.com/roman01la/cljs-rum-realworld-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/clojurescript](https://gitter.im/realworld-dev/clojurescript)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I am working on ClojureScript front-end with [Rum](https://github.com/tonsky/rum/) library.

**Comment by EricSimons** [comment]
@roman01la can you post the link to your repo here? I'll update the status of this issue afterwards 👍

**Comment by EricSimons** [comment]
Just created a logo you can use for the readme in your repo: 

![cjs](https://cloud.githubusercontent.com/assets/556934/25448267/85369fdc-2a7d-11e7-9613-ab5ce5e1800f.png)

**Comment by chencitrix** [comment]
Repurchase link? So what should i buy? Or can i buy what I need?

ChenCritix

2017/4/27 上午1:11，"Eric Simons" <notifications@github.com>寫道：

**Comment by roman01la** [comment]
@EricSimons Sure, here it is https://github.com/roman01la/cljs-rum-realworld-example-app
Nice logo! Thanks 🙂

**Comment by EricSimons** [comment]
@roman01la updated issue status! Also spun up a [gitter room](https://gitter.im/realworld-dev/clojurescript) that we can use for collaborator coordination 👍

**Comment by polymeris** [comment]
I started work on a re-frame version. Can I steal your logo @EricSimons ?

**Comment by EricSimons** [comment]
@polymeris of course! :) Want to create a new issue for the re-frame version?

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
