### ISSUE TITLE
conduit.productionready.io/api/ painfully slow

### ISSUE THREAD

**Issue by LUC18fknU7P** [gothinkster/realworld#613]
> `https://conduit.productionready.io/api/tags`
> ![image](https://user-images.githubusercontent.com/31454692/108547732-8c378400-72f3-11eb-8d39-127e7b2555ce.png)

and then 
> `https://conduit.productionready.io/api/articles?limit=10&offset=0`
> ![image](https://user-images.githubusercontent.com/31454692/108548380-6eb6ea00-72f4-11eb-8738-6a79b400dce6.png)

first of all requires a `OPTIONS` request which takes about 330ms and then the `GET` request which is around 780ms.
both request take over 1 second... this pretty much bottlenecks every single project that uses this dummy API. I mean this should be like cached or something, no?

**Comment by geromegrignon** [comment]
Hello,

Thanks for this issue.
However as our next focus is a new version of the specs and a related deployed API, we won't make changes on the current one.
