### ISSUE TITLE
[Backend] Microservices implementation with GraphQL gateway

### ISSUE THREAD

**Issue by jsBlackBelt** [gothinkster/realworld#621]
Hi,

I implemented a (WIP) micro-services approach to the RealWorld App, tech stack is:

* nx.dev monorepo
* feature services over nest.js
* gateway GraphQL over nest.js
* Redis queue and Bull.js for micro-services communication layer message bus
* Mongoose
* The repo can be found here: https://github.com/jsBlackBelt/microservices-realworld-app

Thanks

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
