### ISSUE TITLE
[Backend] Vert.x + MongoDb + Reactive Java

### ISSUE THREAD

**Issue by AndierZ** [gothinkster/realworld#625]
I worked on a version of the backend and I believe it's mostly done. Added unit tests and the test script also completes with no errors. I'd love to contribute this as one of the solutions. What's the next step? Thanks!

https://github.com/AndierZ/conduit

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
