### ISSUE TITLE
[Fullstack] Nx + Nestjs + Angular

### ISSUE THREAD

**Issue by nhaancs** [gothinkster/realworld#627]
Hi team,

I have implemented a fullstack version of this project with Nestjs, Angular, and Nx monorepo.
Please review my project repo at: https://github.com/nhaancs/realworld-nx-nestjs-angular

Thanks

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
