### ISSUE TITLE
[FullStack] KnockoutJS + Flask

### ISSUE THREAD

**Issue by mayanknimcet188** [gothinkster/realworld#629]
I am going to create a Full Stack Implementation of the RealWorld Application using Knockout JS for the frontend and Flask microframework for the backend.
The project repository can be accessed from [here](https://github.com/mayanknimcet188/knockoutjs-flask-realworld-example-application)
## Work in Progress Steps
-  Add the frontend templates from the starter-kit
- Add Tests according to the API Spec (TDD)
## Completed
- Basic Backend Project Structure 
- Flask Factory App Created
I hope to have fun and learn much more than I currently know from this experience of building the RealWorld Full Stack Application!

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !

**Comment by mayanknimcet188** [comment]
Sure, I will start a new discussion there. Thanks
