### ISSUE TITLE
[Backend] Golang + Fiber

### ISSUE THREAD

**Issue by alpody** [gothinkster/realworld#631]
Hi,

I implemented a [beta version]( https://github.com/alpody/golang-fiber-realworld-example-app) Conduit Backend API for Golang and Fiber.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
