### ISSUE TITLE
[Frontend] Remix

### ISSUE THREAD

**Issue by BenoitAverty** [gothinkster/realworld#632]
Hello,

Remix is a paid server-side rendering react framework that's currently in beta (https://remix.run/features).

I've started implementing the Conduit frontend using this technology as an example app, so that anyone can see how to code using this framework without buying a license.

The repo is here : https://github.com/BenoitAverty/realworld-remix.run

It isn't finished yet, some features are missing. But the architecture is stable and shouldn't change much.

Help is welcome to bring it over the finish line, and any feedback is appreciated.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
