### ISSUE TITLE
API returns 422 status

### ISSUE THREAD

**Issue by bdparrish** [gothinkster/realworld#64]
Request: `https://conduit.productionready.io/api/users`
Body: 
```
{
    "user": {
        "email": "core@core.net",
        "password": "coredotnet",
        "username": "DotNet"
    }
}
```

Status: 422 Unprocessable Entity
Response: 
```
{
    "errors": {
        "email": ["can't be blank"],
        "password": ["can't be blank"],
        "username": ["can't be blank"]
    }
}
```

**Comment by EricSimons** [comment]
Do you have the header for req/res type set to application/json? I think some other folks reported that those headers needed to be present. Lmk if that works for you and I'll make sure to put this in the docs 👍

**Comment by anishkny** [comment]
Yup, confirmed via Postman, works fine with header "Content-Type: application/json", and fails without header:


```JSON
{
  "errors": {
    "email": [
      "can't be blank"
    ],
    "password": [
      "can't be blank"
    ],
    "username": [
      "can't be blank"
    ]
  }
}
```

**Comment by EricSimons** [comment]
@apai4 should this be expected func? Or should we do a fix server side? I feel like requiring the headers on the frontends is a good idea regardless though, as that _should_ ensure they play nicely with any of the backend implementations.

**Comment by bdparrish** [comment]
Confirmed that `Content-Type` header works for the requests.
