### ISSUE TITLE
API design

### ISSUE THREAD

**Issue by err0r500** [gothinkster/realworld#659]
Hi,
I browsed the `v2` tagged issues and didn't find anything about redesigning the API.

Maybe it would be great to add a few good practices like : 
- idempotency on mutating endpoints (through CQRS or dedicated token in the request headers)
- security stuff like [Authentication in SPA the right way](https://jcbaey.com/authentication-in-spa-reactjs-and-vuejs-the-right-way)

Just my 2 cents, happy to discuss this ;)

**Comment by plusgut** [comment]
I would love it, if the api follows the guidelines of the jsonapi.org specification. I think that would advocate a clean approach of implementing things.

**Comment by geromegrignon** [comment]
> I would love it, if the api follows the guidelines of the jsonapi.org specification. I think that would advocate a clean approach of implementing things.

From my point of view, it feels like over-engineering for the project.
I personally never met it in usage, delegating API discoverability to proper API documentation and related specs.

**Comment by geromegrignon** [comment]
Hey @err0r500,

I would encourage dedicated issues for each of them and further explanation about details to add as candidates to the future changelog.
