### ISSUE TITLE
🗄🔧 Symfony

### ISSUE THREAD

**Issue by dakenf** [gothinkster/realworld#66]
# Current Status

- ### Codebase in progress:<br /> [https://github.com/matigda/gothinkster](https://github.com/matigda/gothinkster)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/symfony](https://gitter.im/realworld-dev/symfony)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Hi! I'd like to implement the backend with Symfony 3 framework. I've created a repo here https://github.com/dakenf/realword-symfony

**Comment by EricSimons** [comment]
Awesome! Just updated issue status w/ gitter room, etc :) Also, here's a logo that you can use for your repo's readme:

![symphony](https://cloud.githubusercontent.com/assets/556934/25510530/705d3846-2b86-11e7-9829-71869bf0349e.png)

**Comment by SandeeshS** [comment]
@dakenf Any progress on this? I might help out if there's no progress happening.

**Comment by linxlad** [comment]
Any word on this repo? @SandeeshS I'd be happy to join you :)

**Comment by SandeeshS** [comment]
@linxlad i guess this never got started. I'm planning to pick this up next weekend when i get time. If you'd like to then go ahead and create a new repo and start on it. I'll jump in when i get the time and continue in your repo.

I'll update the main comment with the new repo if you create one.

**Comment by linxlad** [comment]
@SandeeshS Sure, I have nearly finished the Phalcon repo, will create a new repo with config, migrations and models :)

**Comment by matigda** [comment]
So how does it look right now? Has anyone started it or nope? If I want to contribute then is this the repo I should use - https://github.com/dakenf/realword-symfony ?

**Comment by EricSimons** [comment]
@matigda sorry about my delay here! Would you want to take over this project? I think the other folks ended up not having enough time :(

**Comment by vesol** [comment]
I can help @matigda with it

**Comment by matigda** [comment]
We will start with vesol on that in here: https://github.com/matigda/gothinkster
any help appreciated :)

**Comment by matigda** [comment]
hey @EricSimons , is it possible to create symfony repo in gothinkster organization? Or can it stay as mine? I'm still in develop process and I will fix "README" soon ;)

**Comment by EricSimons** [comment]
@matigda feel free to keep it in your own account until it's feature complete! Once it's ready I'll spin up a new repo for it and add you to it :)

**Comment by guillaumemaka** [comment]
@matigda So how does it look right now?

**Comment by matigda** [comment]
@guillaumemaka I gave link to repository ;) step by step but moving forward. You're welcome to create PRs :)

**Comment by arrrni** [comment]
@matigda what is working by far?

**Comment by matigda** [comment]
@arrrni can you guys please take a look at the code before asking? There are functional tests in behat for what is working and there is also configured docker so you can easily run it.

**Comment by EricSimons** [comment]
@matigda I've gone ahead and made your repo the one linked in this issue — can't wait to see the final version!

**Comment by florentdestremau** [comment]
Hello ! Is this issue still relevant ? I could help out for the Symfony backend in order to promote the framework :)
It would be better to do it in Symfony 4. and possibly do it with API Platform (as it is a framework for symfony, frameworkception !), maybe on a separate issue

**Comment by matigda** [comment]
There is already some work done. Have you checked out the repo? IMO it would be best to NOT use any external libraries. It's very simple CRUD. Way better for other people to learn basics of framework and architecture if it's based on simplicity, not external dependencies.

**Comment by florentdestremau** [comment]
I've seen the repo and I gotta say, I really don't like the structure of the `src` file because I don't think it follows the Symfony best practices' way of naming and ordering things. 
Although I like the testing part a lot, I think that it doesn't reflect the "Symfony way":

```
src
 Controller
 Entity
 Repository
```

What I expect from this repository is to follow the docs with as much precision as possible so that any beginner can check out the docs and see clearly where are files located and what are they doing, and I think the Application / Domain / Infrastructure is not documented anywhere, It probably is a stable and durable file structure but as said in the specs, 

> The quality & architecture of Conduit implementations should reflect something similar to an early stage startup's MVP: functionally complete & stable, but not unnecessarily over-engineered.

And I think this is over-engineered. What do you think ?

**Comment by matigda** [comment]
Not sure if it is cause I got used to "screaming architecture". It may be, but it's just something natutal to me. If you are willing to change current code - go on with that. But then please make sure you make it from the beginning to the end. There were already few approaches from different people and every one canceled in the middle.

**Comment by florentdestremau** [comment]
I won't start anything if I'm not confident that I can do it completely. I'll think about this :)

**Comment by seyfer** [comment]
@florentdestremau `Application / Domain / Infrastructure` is a usual structure for DDD and Hexagonal Architecture apps, which is widely used with Symfony. Personally I think this is a better `Real World` example than just following the structure proposed by the framework.

**Comment by florentdestremau** [comment]
@seyfer if you want to show a "by the book" symfony web app, Hexagonal is not included. Because this is framework - agnostic, I don't think it should be reflected, or at least there should be 2 versions. 

Anyway, I am guilty of not having time to offer for this project, I'm just hoping someone will find the time to finish this :+1:

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
