### ISSUE TITLE
Cannot submit a new implementation to CodebaseShow

### ISSUE THREAD

**Issue by nhaancs** [gothinkster/realworld#660]
Hi, the error below occurs when I am trying to submit my implementation to CodebaseShow.

![submit-error](https://user-images.githubusercontent.com/15848072/116430532-1dd1ed80-a871-11eb-91c3-6a72f1165d75.png)

**Comment by mvila** [comment]
Thanks, @nhaancs for reporting this issue.

Normally, the following validation error should have been displayed:

> Sorry, you cannot submit an implementation with a repository that has the "Issues" feature disabled.

But unfortunately, for reasons that would take too long to explain, the error message could not be displayed correctly.

I fixed the issue, so if you refresh the page and try again, the correct error should be displayed.

And, if you activate the "Issues" feature in your repository, your submission should be successfully recorded.
