### ISSUE TITLE
Convert API spec to Swagger spec?

### ISSUE THREAD

**Issue by Cameron-C-Chapman** [gothinkster/realworld#67]
I'm a fan of the swagger api specification and I'm just thinking out loud wondering if converting the current realworld api spec to a swagger compliant spec would add some value? There is some nice tooling and testing support and most environments have swagger libraries. 

It could give the api spec a "common" documentation and contribution language as it grows and allow for integration with the existing swagger ecosystem.

http://swagger.io/
http://swagger.io/specification/

**Comment by anishkny** [comment]
+1 I was thinking about this the other day too.

**Comment by EricSimons** [comment]
I like this idea a lot! Would this require us to break our existing API spec?

**Comment by brwr** [comment]
Swagger is just a documentation tool. Shouldn't affect he API at all other than making it look nicer.

**Comment by anishkny** [comment]
Another option is [API Blueprint](https://apiblueprint.org) with a clean Markdown [syntax](https://apiblueprint.org/documentation/tutorial.html) and a good [ecosystem](https://apiblueprint.org/tools.html) of tools.

**Comment by Cameron-C-Chapman** [comment]
Like @brwr said it wouldn't affect the API. It would just make it easy to produce some pretty documentation and maybe leverage swagger-ui to let people start playing around with the API right away. Postman does a good job of that now but there could be a deployed swagger-ui instance for realworld that was something similar to this, http://petstore.swagger.io/. In that case we could update the spec, the docs would reflect that, and would be pretty easy to have an updated example out there before everyone implemented the new spec (or before having everyone implement the change and making it official, etc).

@anishkny API Blueprint could work too, but I think something like that could be nice since there is a hard API spec here.

**Comment by EricSimons** [comment]
Lets totally do this then!  I'm also a huge fan of having a canonical URL that we can send people to for testing out the endpoints — we should include links to it in the API spec, etc 👍

@Cameron-C-Chapman would you be down to take lead on this?

**Comment by Cameron-C-Chapman** [comment]
@EricSimons I'd be happy to get this going! I'll work on making some more progress on the Spring backend and get this going ASAP.

**Comment by devadvance** [comment]
@Cameron-C-Chapman happy to help where needed on the Swagger spec, since it's a great way to glue everything together 👍

**Comment by Cameron-C-Chapman** [comment]
@devadvance I haven't even had time to really get started yet so if you'd like to help I say go for it!

**Comment by devadvance** [comment]
@Cameron-C-Chapman Working on it now! Will have a rough version done in a day or two.

**Comment by devadvance** [comment]
Pull request #104 to address this

**Comment by EricSimons** [comment]
Thanks @devadvance for making this happen! 💥  Closing issue :)
