### ISSUE TITLE
Sign in with email or username

### ISSUE THREAD

**Issue by cirosantilli** [gothinkster/realworld#683]
# 🚀 feature request

### Relevant scope
What is the scope of this request?

- [X] Frontend specs
- [ ] Backend specs
- [ ] Other... Please describe:

### Description

Currently you can only sign in with email.

### Describe the solution you'd like

Allow signing in with either. Use same input text box currently used for email for either.

**Comment by geromegrignon** [comment]
What's the motivation?

**Comment by cirosantilli** [comment]
The email is generally longer to type, and accepting both is what most big websites do. No big deal of course.

**Comment by geromegrignon** [comment]
I'm reviewing issues.

I'll close this one:
- with a password manager, entering an email isn't that much a big deal
- it complexifies validation
- you can't use `inputmode="email"` to provide a good user experience on mobiles
