### ISSUE TITLE
Add a CODEOWNERS file

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#686]
# 🚀 feature request

### Relevant scope
What is the scope of this request?

- [ ] Frontend specs
- [ ] Backend specs
- [x] Other... Please describe:

### Description

[CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners) feature allows to automatically add a list of reviewers to each open pull request.

### Describe the solution you'd like

Here are the steps to follow for this task : 
- create a file named `CODEOWNERS` into the *.github* folder
- include the following content : 

```
@geromegrignon
```

### Describe alternatives you've considered

No other alternative has been considered.

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by geromegrignon** [comment]
Hello, thanks for your interest.
Feel free to open a pull request.

**Comment by geromegrignon** [comment]
Closed by #688
