### ISSUE TITLE
🖥 🔧 Mithril

### ISSUE THREAD

**Issue by barryels** [gothinkster/realworld#69]
# Current Status

- ### Codebase in progress:<br /> [barryels/realworld-mithril](https://github.com/barryels/realworld-mithril)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/mithril](https://gitter.im/realworld-dev/mithril)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

**Comment by anishkny** [comment]
@barryels this is great stuff! 🎉 

Do you maybe want to rename the repo to something like **realworld-mithril** for alignment with other efforts?

**Comment by barryels** [comment]
Cool! done :thumbsup:

**Comment by EricSimons** [comment]
@barryels can't wait to see this! Just updated the issue status + created a [gitter room](https://gitter.im/realworld-dev/mithril) where we can handle collaborator coordination 👍

**Comment by barryels** [comment]
Awesome! Thanks @anishkny and @EricSimons

**Comment by barryels** [comment]
hi @anishkny there are still a few outstanding functional bits (see "Ready for Dev" column [here](https://github.com/barryels/realworld-mithril/projects/1), unfortunately, I have not gotten an opportunity to work on this project in quite some time :/

Happy to use netlify and have merged your PR on that.

**Comment by anishkny** [comment]
@barryels great! I added you as an admin on netlify. Everything should just work (i.e. auto deploy from master on every commit) but if it doesn't, we can figure it out.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
