### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by chowdhury-akmnoor** [gothinkster/realworld#692]
I am using React/Redux for frontend and Flask for backend.

I am facing these CORS issues

![CORS error login](https://user-images.githubusercontent.com/62734388/123748355-18e5e600-d882-11eb-8291-c3c89e88c663.JPG)

![CORS error](https://user-images.githubusercontent.com/62734388/123748361-1a171300-d882-11eb-8195-54b98993de4f.JPG)

![CORS error2](https://user-images.githubusercontent.com/62734388/123748363-1aafa980-d882-11eb-9ce3-ec62f099320c.JPG)

![CORS error3](https://user-images.githubusercontent.com/62734388/123748365-1aafa980-d882-11eb-87aa-846fe48873d2.JPG)

![flask-backend](https://user-images.githubusercontent.com/62734388/123748366-1b484000-d882-11eb-9f40-18983a247c0b.JPG)

**Comment by geromegrignon** [comment]
Hello,
The cors security rules of the Flask app don't allow communication from a different origin. While it won't happen by deploying both front and back end applications on the same server, here locally the port used by the React app is different from the one used by the Flask app.
You need to update the cors rules into the Flask app if you want to run it locally with the React app.
