### ISSUE TITLE
Error 504 Gateway time-out

### ISSUE THREAD

**Issue by ZZC1206** [gothinkster/realworld#705]
![image](https://user-images.githubusercontent.com/56463454/128887495-03b9024b-7ae1-4a72-9b9b-3c2841a30f0d.png)

I want to register an account at this website(https://demo.realworld.io/#/)

and the api always requests Network Error

**Comment by geromegrignon** [comment]
Hello, I gave it a try and managed to create an account.
Can you retry, please?
