### ISSUE TITLE
[Feature Request][V2] List popular tags

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#709]
# 🚀 feature request

### Relevant scope
What is the scope of this request?

- [ ] Frontend specs
- [x] Backend specs
- [ ] Other... Please describe:

### Description
The current API specs are just about listing the full list of existing tags.
But the current deployed backend implementation on https://conduit.productionready.io/api only retrieves the most popular ones (explaining why we currently have mature content displayed after a massive attack).

It means that people trying out the deployed frontend implementations will only the most popular tags as it uses the official API. But people trying out backend implementations would have different behavior.

We can see the full list in action on the LayrJS fullstack implementation: https://react-layr-realworld-example-app.layrjs.com/all

### Describe the solution you'd like
Even with lower traffic than the official web app, the LayrJS implementation already displays a long list of tags.
We need to consider moving to a filtered and ordered list of tags (to get the most popular ones) for the v2.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by mvila** [comment]
I totally agree that the tags should be sorted by popularity (in descending order) and limited to a certain number. It should be included in the API specs.

**Comment by cirosantilli** [comment]
Another reasonable option would be to sort by last create or better, last applied to an article (current ordering appears undefined: https://github.com/gothinkster/realworld/issues/839 ) as that would lead to good experience for interactive exploration (you create article with tag, then go to index, and easily find your tag).

Sorting by most popular would however be ideal for autocomplete: https://github.com/gothinkster/realworld/discussions/784 so maybe the best is to have a `?sort=` URL parameter.
