### ISSUE TITLE
Cleanup RealWorld API database from NSFW content

### ISSUE THREAD

**Issue by RomanDavlyatshin** [gothinkster/realworld#711]
# 🚀 Cleanup RealWorld API database from NSFW content

### Relevant scope
What is the scope of this request?

- [ ] Frontend specs
- [ ] Backend specs
- [x] Other... Please describe:

### Description
Currently, RealWorld API is publicly available, which led to the creation of ⚠️ NSFW tags ⚠️ and articles😞 
This is **very unhandy** if one wishes to use RealWorld API in any sort of a demo.

### Describe the solution you'd like
I suggest two things:
1. cleanup the existing database
2. Implement a filter for NSFW content for tags and articles.

[There is a related issue](https://github.com/gothinkster/realworld/issues/642), so I guess some contributors are trying to solve that as well.

### Describe alternatives you've considered
Implementing the NSWF-content filter might be out of scope of the project, so the alternative solution is to wipe the database on a frequent and regular basis.
**p.s.** Yes, I could host RealWorld API backend on my own, but it kinda defeats the purpose of it being public, right? 😃

**Comment by geromegrignon** [comment]
Hello @RomanDavlyatshin,

I'm actively working on retrieving access to the productionready.io domain to link it to a new database.
I'm also working on deploying a temporary API meanwhile (tracked with #700)
This temporary API should be released in few days.

A cron whipping the articles data on a regular basis is planned.

**Comment by geromegrignon** [comment]
You can use this new temporary API URL: https://realworld-temp-api.herokuapp.com/api for your requests.

**Comment by RomanDavlyatshin** [comment]
@geromegrignon it looks like [backend API you've provided](https://realworld-temp-api.herokuapp.com/api) does not adhere to the [RealWorld API Spec for comments](https://github.com/gothinkster/realworld/tree/master/api#multiple-comments)

GET `api/articles/:slug/comments` (for article without comments)
Expected response:
```
  { "comments": [] }
```
Actual response:
```
  {"comments":{"comments":[]}}
```

[React Redux Frontend Implementation](https://github.com/khaledosman/react-redux-realworld-example-app.git) breaks when navigated to the article page

**Comment by geromegrignon** [comment]
Thanks for your feedback, It should be fixed by now.

**Comment by geromegrignon** [comment]
Resolved by the release of a new API with limitations
