### ISSUE TITLE
[V2][Backend] API endpoints changes

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#713]
The V2 is a great opportunity to review the specs.

Here is an RFC for URL and verbs used on the backend specs:

#### Login user
**POST** `/api/users/login`

#### Register user
**POST** `/api/users`

#### Get current user
**GET** `/api/user`
> Proposal: change the URL to `/api/users/me` (consistency on `users`)

#### Update user
**PUT** `/api/user`
> Proposal: change the URL to `/api/users` (consistency on `users`)

#### Get profile
**GET** `/api/profiles/:username`

#### Follow user
**POST** `/api/profiles/:username/follow`
> #582 Proposal: change the verb to **PUT** (as it creates a relation link)

#### Unfollow user
**DELETE** `/api/profiles/:username/follow`

#### Get articles
**GET** `/api/articles`

#### Get feed articles
**GET** `/api/articles/feed`
> #695 Proposal: change the URL to `/api/feed` (to avoid conflict with `/api/articles/:slug` with a *feed* param)

#### Get article
**GET** `/api/articles/:slug`

#### Create article
**POST** `/api/articles`

#### Update article
**PUT** `/api/articles/:slug`

#### Delete article
**DELETE** `/api/articles/:slug`

#### Add comments to an article
**POST** `/api/articles/:slug/comments`

#### Get comments from an article
**GET** `/api/articles/:slug/comments`

#### Delete Comment
**DELETE** `/api/articles/:slug/comments/:id`

#### Favorite article
**POST** `/api/articles/:slug/favorite`
> Proposal: change the verb to **PUT** (as it creates a relation link)

#### Unfavorite article
**DELETE** `/api/articles/:slug/favorite`

#### Get tags
**GET** `/api/tags`

**Comment by geromegrignon** [comment]
This task is now open for contributions to the API documentation ( I'll open contributions to the API itself soon).

Based on the [v2 branch](https://github.com/gothinkster/realworld/tree/v2) of this repository, changes have to be made upon the [OpenAPI file](https://github.com/gothinkster/realworld/blob/v2/api/openapi.yml).

You can preview changes by importing the yml file in [Swagger Editor](https://editor.swagger.io/).

**Comment by conradylx** [comment]
Is this task still available?

**Comment by geromegrignon** [comment]
> Is this task still available?

Hello, sorry for the delay.
Yes, it's still available (please note proposals related to 582 and 695 are already done on the v2 branch).

**Comment by Vikrant-Khedkar** [comment]
Is it still open

**Comment by safil-badarudeen** [comment]
can i solve this  issue in js  or only contribute if i have knowledge of ts. If i can do it in Js , assign me. thank you

**Comment by PradeeprajDhanasekaran** [comment]
Is this still open ??

**Comment by shreycmd** [comment]
Is it this issue resolved if not please assign it to me

**Comment by geromegrignon** [comment]
Hi @shreycmd, thanks for your interest in this project.
However I'm currently closing tasks related to the v2 as that's not a sustainable solution (https://github.com/gothinkster/realworld/issues/693#issuecomment-2278824574).
