### ISSUE TITLE
404 on Publish new article

### ISSUE THREAD

**Issue by bondar-artem** [gothinkster/realworld#729]
Hi @geromegrignon 
Thank you for the API update but it has some issues.

It's not possible to publish the article, 404 error from backend
<img width="406" alt="Conduit 2021-09-28 08-32-26" src="https://user-images.githubusercontent.com/21285622/135097303-eac63ecb-9b34-4e80-a919-392be75edabb.png">

Fixes required:

- [ ] the slug must be unique as being used to identify an article, the API needs to generate a unique one regardless of the uniqueness of the article title used to generate the slug
- [ ]  the API shouldn't return a 404 error in such a situation

**Comment by geromegrignon** [comment]
Hey @Postavshik,

I transferred the issue to the gothinkster/realworld repo as it's unrelated to the angular implementation.

I just gave it a try and it worked for me:
![image](https://user-images.githubusercontent.com/32737308/135098163-18b35f28-d989-493f-a420-60969a3993f9.png)

Can you provide the response from the request?

**Comment by geromegrignon** [comment]
@Postavshik 

I was able to reproduce the error: the name of the article must be unique but the API is currently returning a 404 error by providing a duplicate title. 

Thanks for reporting this issue.

**Comment by Postavshik** [comment]
Thank you for a quick response! 👍

**Comment by geromegrignon** [comment]
Fixes required:

- [ ] the slug must be unique as being used to identify an article, the API needs to generate a unique one regardless of the uniqueness of the article title used to generate the slug
- [ ] the API shouldn't return a 404 error in such a situation

**Comment by geromegrignon** [comment]
fixed
