### ISSUE TITLE
🗄🔧 Haskell / Servant

### ISSUE THREAD

**Issue by sotojuan** [gothinkster/realworld#73]
# Current Status

- ### Codebase in progress:<br /> [dorlowd/haskell-servant-realworld-example-app](https://github.com/dorlowd/haskell-servant-realworld-example-app)

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I'm not able to do this at the moment, but I'm putting it out there for exposure. I'd like to see a Haskell backend implementation (using Servant or something else)!

**Comment by EricSimons** [comment]
Just wanted to chime in and say that I'd love to see this as well — anyone out there know Haskell?

**Comment by zudov** [comment]
Sounds fun, I'll try to get something going tonight, but don't sign me up yet :)

**Comment by EricSimons** [comment]
@zudov def keep us posted! :)

**Comment by dorlowd** [comment]
I'm working on servant version of a backend [here](https://github.com/dorlowd/haskell-servant-realworld-example-app).

I'll let you know when I get all endpoints implemented.

**Comment by dorlowd** [comment]
I've got all endpoints implemented to a somewhat working state (code is a mess, though). I'll open issues on my repo about what is left to do.

I'm pretty sure I can pull this one off. Should I file a new issue about my project or will we lift this one to a WIP status?

**Comment by SandeeshS** [comment]
You can definitely take your time and get the code cleaned up and tested. There's no reason to wait for others to join :) If anyone wants to contribute then they can work with your repo via PR's.

**Comment by SandeeshS** [comment]
@EricSimons we need your logo magic for this one

**Comment by dorlowd** [comment]
I mean - issues to track project status. I don't need contributions atm. Feel free to remove "seeking engineers" tag.

**Comment by SandeeshS** [comment]
I've already updated the main comment of this issue with the repo info and status. We can track the project status and progress here. I'll remove the tag :+1:

**Comment by EricSimons** [comment]
🎤  Do you believe in [magic?](https://www.youtube.com/watch?v=mDYNuD4CwlI)

![haskell](https://cloud.githubusercontent.com/assets/556934/25763561/83f8bc50-3198-11e7-9ff2-cc7519f8a508.png)

**Comment by dorlowd** [comment]
Thanks!

**Comment by jonschoning** [comment]
Since Haskell has several FE and BE frameworks, it would be a good idea to make sure to tag this as `Haskell / Servant` rather than just `Haskell`

**Comment by SandeeshS** [comment]
@jonschoning done

**Comment by boxyoman** [comment]
I made an implementation in Haskell. I used servant for the API and Beam for the database. Not really sure what else I should do with it. 
https://github.com/boxyoman/haskell-realworld-example

**Comment by Rizary** [comment]
@boxyoman

> 
> 
> I made an implementation in Haskell. I used servant for the API and Beam for the database. Not really sure what else I should do with it.
> https://github.com/boxyoman/haskell-realworld-example

blog about it.

I think we need to make this real-world-app re haskell+servant to not in the "work-in-progress" status?

@sotojuan

**Comment by ibnuda** [comment]
looks like i've [done it](https://gitlab.com/ibnuda/real-world-conduit) and the write up can be read [here](https://siskam.link/2018-07-02-thinkster-s-realworld---backend.html).

**Comment by anishkny** [comment]
@boxyoman sorry this must have slipped thru the craks. Is your implementation API complete? Can you run the supplied Postman API tests against your backend.

Also would it be possible to provide a Dockerfile to try and spin up your backend? Might be easire for folks to try out than current setup steps. Oh and adding CI support also helps newbies figure out how to build/test (Travis/Circle/Azure Pipelines)

**Comment by boxyoman** [comment]
@anishkny  The API is complete. I had to modify the supplied Postman API tests because the test did things it the wrong order (ex. It would ask for something before creating it, log in then log out then ask for something, etc). After modifying, it passed the tests. Then I put the Elm frontend on it and found a few other bugs that the tests didn't catch.

I'll try adding docker-compose to it to launch a postgres database and the program. The current way I'm running it doesn't work on macOS anymore and never worked on windows. 

I don't currently have any tests which is something I know is needed.

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
