### ISSUE TITLE
Submissions on https://demo.realworld.io are sandboxed

### ISSUE THREAD

**Issue by fctorial** [gothinkster/realworld#731]
### Relevant scope

Deployed demo

### Description

```markup
The articles/comments I create on https://demo.realworld.io are not visible to anyone except me. The app displays just one welcome post when I open it in an incognito tab. Is this intended behaviour? If yes, what is the reason for that?
```

**Comment by geromegrignon** [comment]
Hey @fctorial,

The previous deployed API and used by demo.realworld.io hadn't such limitations.
However, some people used it to spam ads and Not Safe For Work content not aligned with our Code of Conduct.

After some failed attempts to clear the database on a regular basis, I had no choice but to add limitations not to expose user's content publicly.
Here are the limitations: https://github.com/gothinkster/realworld/tree/main/spec#limitations

I'll open an issue to track the addition of a banner on demo.realworld.io to warn everyone about those limitations.

**Comment by fctorial** [comment]
Ok, thanks.
