### ISSUE TITLE
[Docs] links review

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#736]
## Description

I moved the existing documentation by using Docusaurus #720
Some links might not work anymore.

## Solution

Explore the documentation on the hosted GitHub Pages: https://gothinkster.github.io/realworld/docs/intro
For every single broken link, update it inside the source code (the documentation files lie in the /documentation/docs folder).

#### external links

For external links, please provide the absolute path.

```
// valid
https://hacktoberfest.digitalocean.com/resources/eventorganizers

// invalid
/resources/eventorganizers
```

#### internal resources

For links in the documentation, the root is the /documentations/docs folder

```
// valid
/community/authors
/specs/frontend-specs/api

// invalid
/documentation/docs/community/authors
```

## Tests the changes

Build the documentation:

```
cd documentation
npm install
npm run build
```

Serve the documentation:

```
npm run serve
```

Once done, please submit a Pull Request to the main branch.

## How to contribute

Please ask for assignment before working on this issue
> PRs from people not being assigned won't be accepted to avoid duplicate effort.

Please take a look at our [Code of conduct](https://github.com/gothinkster/realworld/blob/main/CODE_OF_CONDUCT.md).  
You'll find our expectations for quality Pull Requests in your [Contributing Guidelines](https://github.com/gothinkster/realworld/blob/main/CONTRIBUTING.md)

**Comment by benjamin-tessem** [comment]
Can I take care of this one?

**Comment by geromegrignon** [comment]
> Can I take care of this one?

Sure, go ahead!
