### ISSUE TITLE
🖥 🔧 Clojurescript + re-frame

### ISSUE THREAD

**Issue by polymeris** [gothinkster/realworld#74]
# Current Status

- ### Codebase in progress:<br /> [polymeris/re-frame-realword-example-app](https://github.com/polymeris/re-frame-realword-example-app)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/clojurescript](https://gitter.im/realworld-dev/clojurescript)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

An alternative to issue #61

- Codebase in progress
https://github.com/polymeris/re-frame-realword-example-app

**Comment by polymeris** [comment]
Templates implemented: https://polymeris.github.io/re-frame-realword-example-app-demo/

**Comment by EricSimons** [comment]
Woah, that was fast! 💯  Btw I think you forgot to include the `nav-link` class on the `<a>` tags in the header links (ex: `<a class="nav-link" href="">Home</a>`)
