### ISSUE TITLE
[Bug]: API returns bio instead of image in the /profiles/{username} request

### ISSUE THREAD

**Issue by concise-studio** [gothinkster/realworld#789]
### Relevant scope

Deployed demo

### Description

I'm trying to fetch the profile information and do request: `https://api.realworld.io/api/profiles/Ya`. The response is 
```
{
    "profile": {
        "username": "Ya",
        "bio": "Desc",
        "image": "Desc",
        "following": false
    }
}
```
As you can see, the data in the field 'image' is the same as the data in the field 'bio'.
From the other hand, when I do request to url `https://api.realworld.io/api/user`, thee response is correct and contain proper link to the image.

And one more thing. In the Postman collection, url for getting profile information is `{{APIURL}}/profiles/celeb_{{USERNAME}}`. When I try to make request to `https://api.realworld.io/api/profiles/celeb_Ya`, I get 404 Not Found

**Comment by geromegrignon** [comment]
About the image, it's a bug to fix ;

```typescript
const profileMapper = (user: any, username: string | undefined): Profile => ({
  username: user.username,
  bio: user.bio,
  image: user.bio,
  following: username
    ? user?.followedBy.some((followingUser: Partial<User>) => followingUser.username === username)
    : false,
});
```

About the Postman collection, `celeb` is hardcoded part of the username for the benefit of the tests.
You shouldn't include it. I invite you to use our Swagger documentation as a reference: https://api.realworld.io/api-docs/

**Comment by geromegrignon** [comment]
Bug fixed.
