### ISSUE TITLE
Alexa, what's new on Conduit?

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#79]
It might be cool to see someone try and build an [Alexa Skill Set](https://developer.amazon.com/alexa-skills-kit) for part of the RealWorld [API Spec](https://github.com/gothinkster/realworld/tree/master/api). Some possible questions handled:

- What's new in my Conduit feed?
- What's new in Conduit global feed?
- Whats new in \<tag\>?
- Follow/unfollow \<username\>
- Favorite/unfavorite \<article slug\>

It could be instructive to others trying to write Alexa Skills. Thoughts?

**Comment by Alonski** [comment]
If I build it will you send me an Echo?

**Comment by EricSimons** [comment]
@Alonski @anishkny would one (or both) of you be down? A few friends of mine from Amazon are down to help provide a couple echo dots for dev :)

**Comment by anishkny** [comment]
@EricSimons I am spread out a bit too thin to take you up, but would love to follow along @Alonski or whoever takes this up, and maybe they can also put up a video demoing Alexa integration!

**Comment by Alonski** [comment]
If I had an Echo I would love to do something like this. Doesn't sound too hard also. :)

**Comment by EricSimons** [comment]
@Alonski shoot me a private message on gitter with an address where we can send an echo dot :)
