### ISSUE TITLE
Move API response format documentation to Swagger

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#794]
## Description

The format expected from API response is documented [here](https://gothinkster.github.io/realworld/docs/specs/backend-specs/api-response-format).
Such content can be included in the API documentation itself in the `openapi.yml` file, providing a unique source of information.

## Action

> You **must** make changes on the v2 branch of this repository and make a pull request on the remote v2 branch as well.

You can import the existing openapi file to [Swagger Editor](https://editor.swagger.io/) for a better developer experience.

Based on the [Swagger documentation](https://swagger.io/docs/specification/adding-examples/), move the content of the current [response format documentation](https://gothinkster.github.io/realworld/docs/specs/backend-specs/api-response-format) to the [openapi file](https://github.com/gothinkster/realworld/blob/v2/api/openapi.yml).

> Populated them in the `components` part of the yml file.

Delete the [API response format file](https://github.com/gothinkster/realworld/blob/v2/documentation/docs/specs/backend-specs/api-response-format.md)

**Comment by mcroissant** [comment]
Hello, I've just checked the [open api spec](https://github.com/gothinkster/realworld/blob/v2/api/openapi.yml) of the v2 branch and it already contains the objects.

**Comment by KostyaTretyak** [comment]
For now in [open api spec](https://github.com/gothinkster/realworld/blob/v2/api/openapi.yml) expected 422 error when user not provides any IDs. For example `GET /tags`.

**Comment by hippo604** [comment]
Hi, I created PR #842 in response to this issue. Thanks.

**Comment by geromegrignon** [comment]
Hey @mcroissant, sorry for the late response.
The file includes properties but not examples.

**Comment by geromegrignon** [comment]
> For now in [open api spec](https://github.com/gothinkster/realworld/blob/v2/api/openapi.yml) expected 422 error when user not provides any IDs. For example `GET /tags`. I think this is need fixed.

Hey @KostyaTretyak, please open a bug report [here](https://github.com/gothinkster/realworld/issues/new?assignees=geromegrignon&labels=bug&template=BUG_REPORT.yml&title=%5BBug%5D%3A+) as this issue is about adding existing examples

**Comment by geromegrignon** [comment]
Closed by #842
