### ISSUE TITLE
[Bug]: Follow/Unfollow Functionality is not working

### ISSUE THREAD

**Issue by vgautamm** [gothinkster/realworld#798]
### Relevant scope

Frontend specs + Backend specs

### Description

```markup
Steps to reproduce:
- Go to conduit main page (https://demo.realworld.io) and click on random profile
- Follow the person
- Refresh the page
- You will notice that it doesn't work
```

**Comment by vgautamm** [comment]
https://user-images.githubusercontent.com/43140948/140627900-497e9f10-fafb-4713-aa95-531af7e77e8e.mov

**Comment by geromegrignon** [comment]
Thanks for this report. I confirm I'm reproducing it as well.
I'm going to do local tests to identify the bug.

**Comment by geromegrignon** [comment]
It's now fixed: The value of **following** was based on the username of the profile itself, always returning false.

**Comment by kaeedo** [comment]
I'm still seeing this bug when viewing a specific article by the followed user: 
e.g. https://angularjs.realworld.io/#/article/Explore-implementations-1

It's possible to follow and unfollow a user on an article page, but when you refresh the article page it doesn't load the following status. The `following` property is missing in the API response

**Comment by geromegrignon** [comment]
Thanks @kaeedo!

Indeed it was never included in the specs and by creating the new API I missed it.
It's now fixed on the demo side.

I still have to update the documentation.

**Comment by geromegrignon** [comment]
Fixed
