### ISSUE TITLE
[Bug]: "500 tagList.map is not a function" if empty string sent instead of tagList

### ISSUE THREAD

**Issue by concise-studio** [gothinkster/realworld#803]
### Relevant scope

Deployed demo

### Description

If user did no fill the field 'tags', it is possible that frontend will send empty string in the 'tagList' parameter. In my opinion, if empty string is not allowed, API should return validation error (422), not internal error (500).

**Comment by geromegrignon** [comment]
Hey @concise-studio, by creating the current API, I didn't include this 'feature' (tracked by #410).
I'll deploy a bug fix to match the previous API not to break existing implementations.

**Comment by geromegrignon** [comment]
It should be fixed by now.
