### ISSUE TITLE
[Feature Request]: Default articles and tags list for Global Feed (currently it's empty)

### ISSUE THREAD

**Issue by Postavshik** [gothinkster/realworld#804]
### Relevant Scope

Backend specs

### Description

```markup
Application Global Feed has an empty list of articles and tags as default values for the demo purpose
```

### Describe the solution you'd like

```markup
Add several default articles and tags to Global Feed.
```

**Comment by geromegrignon** [comment]
Hey @Postavshik,

I added fake data and moved the Heroku dyno to a paid plan to avoid the server to sleep on inactivity to see if it impacts the data persistence (the fake data being deleted without any clue on a regular basis).

Keeping this issue open for 2 weeks as a reminder.

**Comment by Postavshik** [comment]
@geromegrignon WOW, that was very quick! 
Thank you so much! :))

**Comment by geromegrignon** [comment]
You are welcome.
I made another fix as the cron was deleting all tags.

**Comment by geromegrignon** [comment]
fake data is still somehow deleted.
I'll move the database from Heroku to Supabase today.

**Comment by geromegrignon** [comment]
Database moved to Supabase! :rocket:

**Comment by geromegrignon** [comment]
popular tag list fixed too, closing this issue.
