### ISSUE TITLE
[Refactor]: remove slug segment from DELETE comment API URL endpoint

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#810]
## Description

The current API URL to delete a comment is `/articles/{slug}/comments/{id}`.
The slug segment is the slug of the related article.
To delete a comment, this slug isn't required.

## Solution

Change the URL to `/articles/comments/{id}`.

**Comment by spiroskmaris** [comment]
can i work on this issue please?

**Comment by geromegrignon** [comment]
discontinued task
