### ISSUE TITLE
🗄🔧 QEWD Implementation

### ISSUE THREAD

**Issue by robtweed** [gothinkster/realworld#83]
# Current Status

- ### Codebase in progress:<br /> [robtweed/qewd-conduit](https://github.com/robtweed/qewd-conduit)
- ### Interested in helping out? Say hello! 🎉 <br />**[gitter.im/realworld-dev/qewd](https://gitter.im/realworld-dev/qewd)**

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [x] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

I've created an implementation of the Conduit REST back-end using the Node.js/Redis-based QEWD platform.  See https://github.com/robtweed/qewd-conduit

QEWD logo is here: https://s3.amazonaws.com/mgateway/qewd/qewd_logo5.png

I'd love you to add this to your list of implementations.
Rob Tweed

**Comment by EricSimons** [comment]
Awesome work!! Here's a logo I made that you can use: 

![qewd](https://cloud.githubusercontent.com/assets/556934/25587724/182f95fc-2e5a-11e7-83db-1541c1bee128.png)

Just added the RFC tag, so lets if we can get some folks in here to help review the code!

**Comment by robtweed** [comment]
Updated the repo with the logo!

**Comment by robtweed** [comment]
Also added a Guided Tour to the repo's ReadMe which I hope will be helpful.

Will you add this QEWD implementation to your list on the main site?

**Comment by SandeeshS** [comment]
I tried testing your api which is live at http://178.62.26.29:8080/api, but it doesn't have cors enabled. I'll run a test using postman and give u feedback. If everything looks fine then @EricSimons can setup the project on here and add you to it. Cheers :+1:

**Comment by robtweed** [comment]
Ah OK - can you try again and see if it's now sending the correct CORS response headers?

**Comment by SandeeshS** [comment]
Yes, it works now. But you haven't added the authorization header to the allowed headers. So authenticated endpoints are failing. You also have some unwanted headers in the allowed list, some of which are allowed by default. You can add these and it should work fine.
'Content-Type', 'X-Requested-With', 'Authorization'

First test on register endpoint shows that there is no validation logic for the inputs. Is it the same for all the forms?

**Comment by robtweed** [comment]
Thanks Sandeesh - can you try that now?

**Comment by robtweed** [comment]
Sandeep

The register validation I've implemented is:
- username, email and password must exist in the request and none can be an empty string
- the username cannot already exist
- the email cannot already exist

That's the only validation I could determine was needed from the spec, unless there's some more detail that I haven't seen?

**Comment by SandeeshS** [comment]
@robtweed I appreciate all your effort. But you need to do a local test first. The user profile page doesn't work since you've added logic so that a user can't view his own profile. Then there is the input validation issue. I would suggest you clone one of our frontend repo and run it locally to test it. This will help you find and fix issues faster.

Also the authorization header is allowed now :+1:

**Comment by SandeeshS** [comment]
The api spec is lacking in lacking in explanation. We'll update it soon with a complete new detailed spec. The validation that i'm talking about is the check for valid email, valid characters in username, length of inputs etc

**Comment by robtweed** [comment]
if you can give me the username valid characters and field lengths I can easily add them.  I assume the valid email check is that it conforms to the expected pattern, not that it is actually live and valid

**Comment by robtweed** [comment]
user should be able to view own profile now

**Comment by SandeeshS** [comment]
This isn't finalised but i pulled a rough validation logic. You can go ahead with this for now and it should work fine with any of the frontend.

**Register**

    username 	- required, max length:50, alpha numeric only, unique in db
    email 		- required, valid email format, max length:255, unique in db
    password 	- required, min length:6

**Login**

    email 		- required, valid email format, max length:255
    password 	- required, min length:6

**Update profile**

    username 	- required, max length:50, alpha numeric only, unique in db other than itself
    email 		- required, valid email format, max length:255, unique in db other than itself
    password 	- required, min length:6
    bio 		- required, can be empty, max length:255
    image 		- required, can be empty, valid url format

**Create article**

    title 		- required, string, max length:255
    description 	- required, string, max length:255
    body 		- required, string
    tagList 	- optional, array format


**Update article**

    title 		- optional, string, max length:255
    description 	- optional, string, max length:255
    body 		- optional, string

**Add comment**

    body 		- required, string

**Comment by SandeeshS** [comment]
FYI the favorited by user endpoint returns all articles. You might want to check that.

**Comment by robtweed** [comment]
Not sure what you mean - according to the activity log, the request you sent: POST /api/articles/ripple/favorite returned the Article that had been favorited - which is as per the API spec

**Comment by robtweed** [comment]
Ah sorry - you're referring to /api/articles?favorited=adadsad&limit=10&offset=0
I'll fix that

**Comment by robtweed** [comment]
Sandeesh - many thanks for the info.  I think I have those fixes in place now

**Comment by SandeeshS** [comment]
No problem. I'm a bit busy at the moment. If possible setup a local frontend and do a thorough test using with api. Give us a confirmation once you're done. I'll double check once on my end and then we can plan on moving the repo after all tests have passed. Good job :+1:

**Comment by robtweed** [comment]
I'll do that tomorrow, Sandeesh - run out of time here myself now :-)
Thanks again for the help today, and I'll ping you tomorrow when I've checked it all through
Rob

**Comment by SandeeshS** [comment]
Sounds good. Looking forward to it.

**Comment by robtweed** [comment]
Hi Sandeesh - is the conduit.productionready.io backend down?  Can't get the demo app working to compare with how mine responds

**Comment by SandeeshS** [comment]
Just checked and it seems to be down. @EricSimons can you check the api server.

**Comment by robtweed** [comment]
Think I've found an error in the React/Redux front end - if you start from a position of a clean slate where there are no articles, and you try to enter a first article and generate an error response at the back-end (eg if there's no title or description), the front end logs the error, but then tries to display articles and fails because slug isn't defined - at which point the front end is in a frozen state.  Restart, enter a proper article without error and it completes OK and displays the new article

**Comment by robtweed** [comment]
Nope I can't get the front end to properly behave when articles are updated and an error is returned - eg
common.js:23 Uncaught (in promise) TypeError: Cannot read property 'slug' of undefined
    at exports.default (common.js:23)
    at combination (combineReducers.js:132)
    at dispatch (createStore.js:179)
    at index.js:104
    at middleware.js:55
    at middleware.js:41
    at Object.dispatch (applyMiddleware.js:45)
    at middleware.js:34

Don't know why the front end is complaining about the slug property?

**Comment by robtweed** [comment]
I'm pretty sure the demo system copes with this OK - once it's back I'll see if I can find the difference(s) - very odd as the back-end seems to be doing what it should up to this point

**Comment by SandeeshS** [comment]
@robtweed good find, can you post an issue over at https://github.com/gothinkster/react-redux-realworld-example-app/issues

The react and angular frontend's have few pending issues that are being worked on. We can have someone create a PR for this over at the repo. In scenarios like these you can stick to postman test to verify the api integrity. Since we want an error free api to be consumed, while the frontend gets fixed simultaneously.

PS : I don't maintain the frontend repo's but i did encounter issues myself. Reporting those would be the best solution so that the maintainers/community can create a fix.

**Comment by robtweed** [comment]
Another question, Sandeep, if I may: if the back-end session expires, do you know what the expected response should be to /api/user?  Currently I return a 403 response with the payload

{"error":"Invalid token or session expired"}

According to the console, the UI registers this but continues anyway to try set itself up, and eventually gets into a frozen state.  If 403 is the correct response, then I guess another UI bug to report :-)

**Comment by robtweed** [comment]
BTW in QEWD, the back-end session and JWT token expiry are linked, so this equates to the back-end confirming that the received JWT has expired

**Comment by SandeeshS** [comment]
The current api spec lacks information with regard to JWT generation, authentication, validation. The three main backend here generate JWT with 60 days expiration which is not advised. JWT's are supposed to be short lived and refreshed. I've implemented the same in the laravel backend for now to keep things in sync with the main backend repo. I'm planning to re do the api spec from scratch which will include the JWT part that i mentioned. So i'd recommend that for now you increase the life of the tokens and handle the errors with 401 and 403. You're free to make suggestions regarding changes to the api spec. I'll create a new issue later today for the discussion on updating the spec.

**Comment by robtweed** [comment]
OK understood, Sandeep - makes sense.  I was keeping my JWTs down to 10 minutes, but I'll push that up to 60 days as you suggest and avoid the UI issues for now. I'll be interested to see your updated JWT spec.  I've copied the structure (Id and username) used in the demo.  BTW I assume that you'll be allowing use of reserved claims such as jti which QEWD currently uses for back-end identification?

**Comment by SandeeshS** [comment]
It's Sandeesh btw :)

Absolutely. None of the reserved claims will be touched as per the RFC. In fact the current frontend's don't even make use of any claims to verify the user. The api endpoint to fetch the current user using the token is being used for that purpose. Therefore as long as the server validates the token, the frontend doesn't care about any of it's claims. Imo the current implementation of JWT as the given spec is far from standard.

**Comment by robtweed** [comment]
Apologies Sandeesh! Not enough coffee yet and too quick to click the submit button!  :-)

**Comment by robtweed** [comment]
Ok Sandeesh, I and a colleague have given it a pretty thorough testing and the QEWD back-end seems to be holding up well now against the UI.  The one issue I see is that weird issue with the UI stalling when there are errors in creating and updating articles.  I'm pretty sure the back-end behaviour is correct.  However, until the demo system is back I can't really find out any more on that one, but provided you avoid forcing article errors, perhaps you could give it a once-over and see what you think?

BTW my colleague, Tony Shannon, has logged a UI issue for behaviour he's not sure is intended - something he found during testing

**Comment by robtweed** [comment]
BTW, my local UI instance can be accessed at http://178.62.26.29:3000

**Comment by robtweed** [comment]
qewd-conduit back-end working on a Raspberry Pi here at my house: http://www.mgateway.com:3000/api

**Comment by SandeeshS** [comment]
@robtweed that's awesome :+1: I've been quite busy today. I'll have a go at your api with the angular frontend setup i have on local and give you my side of the pass. We can then have @EricSimons move the repo over here and get it finalised. Great job!

**Comment by robtweed** [comment]
Thanks Sandeesh! :-)

**Comment by robtweed** [comment]
Tried the demo system now that it's back up and running, but it doesn't exhibit the same behaviour as I see with my local version.  Anyway I've logged an issue - I can't see any difference in the sequence or content of responses when you submit an article with a blank body, so I suspect there's a difference between the versions of the UI used in the demo and what's on Github.

**Comment by robtweed** [comment]
@EricSimons While awaiting Sandeesh's testing, could you add QEWD to the Work In Progress list of backends on the main realworld page?

**Comment by SandeeshS** [comment]
@robtweed I tested your api which is live at http://178.62.26.29:8080/api, i hope this is updated. Everything works perfect except for 2 small hiccups.

The comment form on first submit after page load with no body sets the field to null and not an empty string. I guess your validation is failing for some reason and an empty comment actually gets parsed and saved. Subsequent request to add gets validated correctly.

The comments can't be deleted. Once the delete request just responded with status code 200 with "errors is not defined" in response. Now i tried the same again and it's giving me a 403 error with "not owned by author" message.

Another thing i wanna mention, when i first signed up i was already following user "tonyshannon" for some reason. But on next 2 registration it worked fine with a clean user feed. I assume this might be due to some test follow data in the db which wasn't removed.

**Comment by robtweed** [comment]
Hi Sandeesh

Yes I noticed the Comment error came up and fixed the logic mid-testing :-)

The logic I'm using says that only the author of a comment can delete it.  Is that correct?  Or can the article author also delete it?

Regarding the following tonyshannon - that was when you first registered your new username, right?  I'll see if I can figure out why that might have happened - seems a bit odd

Thanks!  What's the next step?

**Comment by SandeeshS** [comment]
Only the owner/author can delete their own comment. But i'm getting the error when trying to delete mine.
Regarding the following issue, yes it happened only on the first sign up. 

You're the author of QWED, i don't think we can ask for a better review than your own :) Once all the tests have passed we can clone/move the repo here and add it to the list :+1:

**Comment by robtweed** [comment]
Could you try deleting that comment again, logged in as its author? I think I found the problem

**Comment by SandeeshS** [comment]
Same error

**Comment by robtweed** [comment]
Hmm - still doesn't look like its working....let me put some trace code in....one sec

**Comment by robtweed** [comment]
Duuuh! Stupid error - can you try that again now?

**Comment by SandeeshS** [comment]
Btw join i just created a Gitter room https://gitter.im/realworld-dev/qewd, we can continue our discussion there. It'll be much easier to test.

**Comment by SandeeshS** [comment]
Ok that concludes my testing. :+1: from me

**Comment by robtweed** [comment]
OK I've committed the latest changes that were needed to fix the last bugs to https://github.com/robtweed/qewd-conduit

**Comment by EricSimons** [comment]
Just created [official repo](https://github.com/gothinkster/QEWD-realworld-example-app) and added @robtweed to it! You're also now listed on the readme :)
