### ISSUE TITLE
[Bug]: for now, realworld website not works correctly

### ISSUE THREAD

**Issue by KostyaTretyak** [gothinkster/realworld#838]
### Relevant scope

Other: describe below

### Description

Did you know that [realworld](https://gothinkster.github.io/realworld/) doesn't work right now?

**Comment by geromegrignon** [comment]
Hey @KostyaTretyak, I moved the documentation to Netlify today and updated the url on the repository. I might have missed a link somewhere. Where did you find the broken link?

**Comment by KostyaTretyak** [comment]
Hey. Oh, I'm browsing your website from a pinned tab in chrome. Now I've seen the new version your website. I close the issue.
