### ISSUE TITLE
Extra credit: Recommender system for feed

### ISSUE THREAD

**Issue by anishkny** [gothinkster/realworld#85]
The current feed API `GET /api/articles/feed` returns articles created by followed users, ordered by *most recent first*.

Using machine learning, could you enhance the feed to _also_ mix in some articles from authors I am not currently following but which I may like, based on various signals like say:

- currently followed authors
- articles read in the past
- other ML magic?

Note that I am proposing this as **extra credit**. Thus simply returning followed authors' articles most recent first is perfectly acceptable. But what would a [Recommender System](https://en.wikipedia.org/wiki/Recommender_system), even a rudimentary one, look like for RealWorld Conduit?

**Comment by EricSimons** [comment]
Fantastic idea! I'd _love_ to see a TensorFlow version of this 🙃

**Comment by SandeeshS** [comment]
When i first heard about this project, the thing that came to my mind was the simplicity and ease of use. These are valuable resources for beginners and intermediate users to learn and get started. I feel implementation of machine learning to the existing architecture ruins the point.

With that said i love the idea though. Though it shouldn't be hard wired in manipulating the users feed, instead a new endpoint for recommendations could display all the articles based on user's favorites and following pattern.

`GET /api/articles/recommend`

Any thoughts on having this as a separate machine learning project? The focus currently is with web frontend and backend. Having this as a ML starter would be amazing and if we can get this in a separate project, we can consume it's api in all other backend's to have the recommendation feature.

**Comment by anishkny** [comment]
I suppose communication is key here. With [19](https://github.com/gothinkster/realworld/issues?utf8=✓&q=is%3Aissue%20is%3Aopen%20label%3Abackend%20label%3Awip) backends WIP right now on top of the three reference backends, it is not possible to force everyone to enhance their backends to provide a recommender system. Hence it should be made clear this is **extra credit**, you don't have to do it, but if you did how would it go?

Perhaps we could ask folks to show the recommender work in a separate fork or branch so that readers can clearly see the diff with and without it.
