### ISSUE TITLE
Add list of "challenges" to the readme

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#86]
(aka our extra credit ideas :)

**Comment by anishkny** [comment]
Hey, where was this added?

**Comment by brwr** [comment]
This hasn't been done yet. I think it was closed as in favor of #90. It still needs to get done though.

**Comment by EricSimons** [comment]
Yeah #90 was why I closed this; still does need to get added somewhere though. Any thoughts on how/where?

**Comment by Cameron-C-Chapman** [comment]
@EricSimons I saw you started playing around with the idea of a wiki for the project. I think we could leverage that to help document some of this stuff and link to that in the readme. We could do a Roadmap, Spec details, Extra Credit Challenges, etc as wiki entries.

**Comment by EricSimons** [comment]
Reopening issue! Here's my thoughts that I posted into our gitter channel:

--------

Regarding extra credit, I like the idea of keeping issues around so people can keep discussing them and what not. I also like the idea of having a directory of extra credit ideas so folks can browse & get inspired to create them.

Proposal: What if we had a “Challenges” section underneath our supported stacks on the readme that listed out all of the current challenges (w/ 1-2 sentence description), linked to the github issue thread about it, and also linked out to any “completed” challenge repos

I like “challenges” because I think it will play into Maslow’s heirarchy better than the term "extra credit” (which is important bc we want to intrinsically motivate folks to get involved :)

Having it on the readme would also ensure that all of the cool ideas being presented are seen by a wider audience, and therefore are more likely to actually get implemented by someone
especially if that person can see other people’s completed challenge repo’s listed on the readme
