### ISSUE TITLE
[Feature Request]: Fake current moderated content from the API

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/realworld#863]
### Relevant Scope

Other: describe below

### Description

I will change the API limitations introduced in 2021 regarding the spam of undesirable content we faced.

Thanks to #859, I realized that while such limitations are needed, it adds constraints on frontend implementations creators. They can't test pagination and full popular tags size without spending (wasting) time creating their content.

I'll remove the limitation upon demo/user content being retrieved from the database.
**But** I'll moderate by default the previously blocked content by faking the data retrieved.
It'll affect articles, comments, tags, and user info.

Such change will introduce a new endpoint to query articles without this content:
On implementation creation, It can be difficult to test article creation due to the current traffic on the API. By the time you come back on the article list, your new article might already be hidden due to pagination and new articles.
Such an endpoint will mimic current behavior by only displaying demo and user content. It won't be part of the required specs for proper implementation as acting for experimental purposes only.

### Describe the solution you'd like

Changes will be made to the documentation and the current API

**Comment by adamerose** [comment]
I understand the need to censor content but I think there really needs to be more than 3 sample posts by one user "Gerome". When I recently looked at [demo.realworld.io](http://demo.realworld.io/#/) after #718 I thought the backend was broken or something. 

> I'll remove the limitation upon demo/user content being retrieved from the database.

This issue has been open for a while now, may I suggest as a temporary solution just adding more hard-coded sample content? If you just kept it as it is now but added 10 more users and 50 more articles with tags (with something like faker.js / dummyJSON / jsonplaceholder) it would fix most of the major problems you mentioned like lack of pagination

**Comment by geromegrignon** [comment]
Done @adamerose (30 new users with 20 articles and multiple comments for each of them).
