### ISSUE TITLE
[Feature Request]: ASP MVC Core frontend Demo

### ISSUE THREAD

**Issue by fasteddys** [gothinkster/realworld#868]
### Relevant Scope

Frontend specs

### Description

Hello can you please include an ASP Core MVC front end in this as well.

### Describe the solution you'd like

 ASP Core MVC with ViewComponents and the other advanced frontend techniques to interweave dual binding, rx.js etc

**Comment by geromegrignon** [comment]
Hello @fasteddys,

Implementations are created by the community.
Feel free to work on one matching your expectations to share it with the community.
