### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by aliataf** [gothinkster/realworld#876]
### Relevant scope

Backend specs

### Description

Register a new user
`POST /users`

Returns 422 error with object:
```
{
    "errors": {
        "email": [
            "can't be blank"
        ]
    }
}
```

**Comment by geromegrignon** [comment]
Hey @aliataf, I can't reproduce your issue.

Is the body of your request matching the expected format?
Here is the related documentation: https://realworld-docs.netlify.app/docs/specs/backend-specs/endpoints#registration

**Comment by aliataf** [comment]
@geromegrignon
Yes, it was my fault I forgot to wrap the fields in a "user" object.
