### ISSUE TITLE
[Bug]: api.realworld.io appears to be down?

### ISSUE THREAD

**Issue by robtweed** [gothinkster/realworld#877]
### Relevant scope

Other: describe below

### Description

The api.realworld.io back-end appears to be down.  Is there a problem?  If so any ETA on when it will be available again?
Thanks!

**Comment by geromegrignon** [comment]
Hey @robtweed,

The API is hosted on Heroku.
They are facing an issue right now: https://twitter.com/herokustatus/status/1496890980531773455

**Comment by geromegrignon** [comment]
![image](https://user-images.githubusercontent.com/32737308/155572113-84d0d592-c2ff-439d-9d6b-a72c25e65466.png)

**Comment by robtweed** [comment]
Thanks - it came back soon after :-)
