### ISSUE TITLE
🗄🔧 Phalcon

### ISSUE THREAD

**Issue by linxlad** [gothinkster/realworld#88]
Current Status
======

* **Codebase in progress:**
	[https://github.com/linxlad/realworld-phalcon](https://github.com/linxlad/realworld-phalcon)
    
* **About Phalcon:**
 [https://phalconphp.com/en/](https://phalconphp.com/en/)

- [x] 🏁  Fork the starter repo & post the link in this issue
- [x] 🎨  Create logo for repo & update issue status (@ericsimons)
- [x] 🔨  Implement all of Conduit's functionality per the spec & API
- [x] 👀  Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉  Tag v1 release, move repo to main org, and officially list it on the README!

---

Hey, I would like to implement a backend example with Phalcon.

**Comment by linxlad** [comment]
@EricSimons Is it possible to work your magic on the logo? :)

**Comment by EricSimons** [comment]
@linxlad yessir! :) 

![phalcon](https://cloud.githubusercontent.com/assets/556934/25671103/b812cfdc-2fe3-11e7-9982-bd96f7f34adc.png)

**Comment by linxlad** [comment]
Thank you kind sir :)

**Comment by linxlad** [comment]
**API Tasks:**

 Articles

- [ ] GET - Feed
- [ ] GET - All articles
- [ ] GET - Articles by author
- [ ] GET - Articles favorited by username
- [ ] GET - Articles by tag
- [ ] POST - Create article
- [ ] GET - Single article by slug
- [ ] DEL - Delete article
- [ ] PUT - Update article
- [ ] POST - Favorite article
- [ ] DEL - Unfavorite article

 Auth

- [x] POST - Login
- [x] POST - Login and remember token
- [x] POST - Register
- [x] GET - Get current user
- [x] PUT - Update user

 Comments

- [ ] GET - All comments for article
- [ ] POST - Create comment for article
- [ ] DEL - Delete comment

 Profile

- [ ] GET - Profile
- [ ] POST - Follow profile
- [ ] DEL - Unfollow profile

 Tags

- [ ] GET - Get all tags

**Comment by linxlad** [comment]
@EricSimons Not a biggie but Phalcon is missing from the `Work In Progress` section :)

**Comment by SandeeshS** [comment]
@linxlad ah sorry about that. Guess Eric missed it on the last update. I'll create a PR to add this :+1:

**Comment by SandeeshS** [comment]
@linxlad added with #114 @EricSimons will merge it when he's online. I've also sorted the list alphabetically so that people don't take offense with one being ahead of another :D

**Comment by linxlad** [comment]
Thanks :)

**Comment by EricSimons** [comment]
Thanks for the PR @SandeeshS! Sorry about that @linxlad — can be kinda hard to keep track of all of the implementations currently in the pipeline 😓

**Comment by linxlad** [comment]
@EricSimons It's no problem at all, just thought I'd mention it, I appreciate the size of the workload you have to deal with, keep up the good work :)

**Comment by linxlad** [comment]
@EricSimons @SandeeshS I have completed functionality. I am currently introducing CI and tests but would be nice to get the peer reviews started so I can make improvements

NB: I will probably making regular improvements to reflect the latest releases of Phalcon. Also there are some methods I would like to revisit at a later stage.

**Comment by linxlad** [comment]
👋

**Comment by SandeeshS** [comment]
@linxlad awesome :+1:  I missed the last notification and didn't read the message. You can add the tests slowly taking your time, no hurry. I'd love to test this on my end once but i don't see any instructions to get this running without docker. Is there any simple way i can get this up and running and test the api locally? Also we can move this repo and get this listed once all the tests come out green :)

**Comment by linxlad** [comment]
@SandeeshS 

I will update the readme this evening with everything.

Phalcon is a compiled C extension for PHP. So I provided the docker/nanobox as they have the extension pre-loaded. However if you want to run this in another environment (WAMP/LAMP for example) you would need to download the latest extension and add it yourself :)

**Comment by linxlad** [comment]
How can I continue having this peer reviewed? :)

**Comment by EricSimons** [comment]
@linxlad trying to get it running locally now :) Have you fully tested it against one of the frontends to make sure all works properly? If so, I'll set up the official repo for this!

**Comment by geoidesic** [comment]
@linxlad well, have you?

**Comment by geromegrignon** [comment]
Hello we are currently moving all work in progress to Github Discussions.
I'll close this issue by now, you can find instruction to open a discussion there : https://github.com/gothinkster/realworld/discussions/633

Thanks for your contribution !
