### ISSUE TITLE
[Bug]: Potential privacy issue

### ISSUE THREAD

**Issue by henno** [gothinkster/realworld#895]
### Relevant scope

Backend specs

### Description

Is the inclusion of followers' emails and password hashes a bug or an intentional feature:
https://api.realworld.io/api/articles/Create-a-new-implementation-1

**Comment by geromegrignon** [comment]
Hi @henno, thanks for bringing it to my attention.
It's a bug indeed.

I tried to release a new version with a quick fix but got an application error on heroku.
I'll dive later on today.

**Comment by geromegrignon** [comment]
Fixed! 🚀
