### ISSUE TITLE
[Bug]:  422 Error code

### ISSUE THREAD

**Issue by hosseinghs** [gothinkster/realworld#896]
### Relevant scope

Frontend specs

### Description

Hi , i'm making a post request to the following address : ' https://api.realworld.io/api/users '
 and my payload is an object with email , username  and password.
i'm sending all these values and I get an 422 Error with the error msg that says : ' email can't be blank ' , while it is not blank,
i'm using nuxt/axios module and i have set credentials to false , because when it was set to true I would get CORS error msg ,
any thoughts on my problem would be great!!!!

**Comment by geromegrignon** [comment]
Hi @hosseinghs, can you provide an example of the payload format sent here?

**Comment by hosseinghs** [comment]
![image](https://user-images.githubusercontent.com/72767346/158699269-d23588f3-c394-4f42-8366-b11b87404342.png)

**Comment by geromegrignon** [comment]
It doesn't match the expected format explained [here](https://realworld-docs.netlify.app/docs/specs/backend-specs/endpoints#registration)

```json
{
  "user":{
    "username": "Jacob",
    "email": "jake@jake.jake",
    "password": "jakejake"
  }
}
```

**Comment by hosseinghs** [comment]
you are a life saver =) !

**Comment by geromegrignon** [comment]
you are wlecome
