### ISSUE TITLE
[Bug]: Password hash returned in token from the login response

### ISSUE THREAD

**Issue by kujirajuunigou** [gothinkster/realworld#898]
### Relevant scope

Deployed demo

### Description

The bcrypt hash of the password is returned in the JWT token from the response of the login endpoint.

The payload of the JWT has a signature, but the payload is base64-encoded and everyone with a token can decode it to get the password hash.

There's no good reason to include the hash in the token payload.

**Comment by geromegrignon** [comment]
Hi @kujirajuunigou, thanks for pointing it out.
It's fixed now8
