### ISSUE TITLE
🗄🔧  Go + Gin

### ISSUE THREAD

**Issue by EricSimons** [gothinkster/realworld#9]
# Current Status

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Peer review of final codebase by RealWorld admins & community (RFC)
- [ ] 🎉 Tag v1 release, move repo to main org, and officially list it on the README!

-----

Not sure what the most popular web frameworks are for Go, but would be good to have support for at least one or two of them :)

**Comment by chrislewispac** [comment]
echo, gin, and guerrilla. although many Go implementations use the standard libraries as well.

**Comment by EricSimons** [comment]
@chrislewispac thanks for the info — which of those options would you recommend newcomers learn first? That would probably be a good place for us to start.

**Comment by chrislewispac** [comment]
gin is the most newcomer friendly I would say.

https://github.com/gin-gonic/gin

**Comment by EricSimons** [comment]
Awesome. Any chance you'd be able to [add support](https://github.com/gothinkster/realworld/tree/master/spec) for it? :)

**Comment by chrislewispac** [comment]
Yeah, I just have to finish up courses but I'll get started on it. I can also work on an elm version at some point. I had been meaning to do something similar anyways.

**Comment by EricSimons** [comment]
Sweet! Lmk if there's anything I can do to help & feel free to [fork the starter kit](https://github.com/gothinkster/realworld-starter-kit) and post the link here so that others can watch/help :)

**Comment by chrislewispac** [comment]
Contributions Welcome:

https://github.com/chrislewispac/realworld-starter-kit

**Comment by EricSimons** [comment]
Just set up [**the Gitter chatroom**](https://gitter.im/realworld-dev/golang-gin) for this! Lets do collaborator coordination in there 👍

cc/ @chrislewispac

**Comment by JackyChiu** [comment]
Hey, do you guys need an implementation with just the standard Go `net/http` library?

**Comment by EricSimons** [comment]
Not yet! Want to start one @JackyChiu? I can create a new issue for it if so 👍

**Comment by AlKoFDC** [comment]
I'd also prefer learning more about the implementation with the net/http package. I'm not sure I can contribute, but I'll definitely watch.

**Comment by EricSimons** [comment]
[New issue](https://github.com/gothinkster/realworld/issues/45) created specifically for net/http version. @JackyChiu feel free to fork @chrislewispac's repo and the post the link to the new issue, and then I'll update the issue's status.

**Comment by JackyChiu** [comment]
@EricSimons Yeah I'd love to help out!

**Comment by brwr** [comment]
@chrislewispac Hey! Any updates on this? Anything we can do to help?

**Comment by chrislewispac** [comment]
@brwr Feel free to clone the repo and get started. I have finals this week so won't be doing much until next week.

**Comment by wangzitian0** [comment]
Hi, Guys,
I just fork an another start-kit with Golang & Gin which has been implement most of those spec.
Could you please give me some reviews or tips?  :)
Here is my repo: https://github.com/wangzitian0/golang-gin-starter-kit

**Comment by EricSimons** [comment]
@wangzitian0 sorry about my delay here — this looks amazing!! How much is left to completely adhere to the API spec? Would love to list this on the main readme once that's ready!

**Comment by wangzitian0** [comment]
@EricSimons Thank you for your reaching out!  :)
I have finished all of the API spec and it can pass all of the cases in Postman Collection. Some tests still have some issue, but I think it's acceptable in the first version as the spec just require one test.

**Comment by EricSimons** [comment]
@wangzitian0 sorry about my delay here, things have been kinda crazy lately! I just marked this as RFC and will put it into the main org tmrw morning :)

**Comment by wangzitian0** [comment]
@EricSimons Thank you! I'm very happy to see it, anything else need I to do? :)

**Comment by EricSimons** [comment]
@wangzitian0 np! I just added it to the readme :) Thanks so much for your awesome work on this!!!
