### ISSUE TITLE
[Bug]: error 500 after login

### ISSUE THREAD

**Issue by kllpff** [gothinkster/realworld#903]
### Relevant scope

Backend specs

### Description

Error 500 after login. Authorization status disappears after update.
{"status":"error","message":"missing authorization credentials"}
"Argument where of type UserWhereUniqueInput needs at least one argument.\n
<img width="1440" alt="Снимок экрана 2022-03-22 в 01 40 22" src="https://user-images.githubusercontent.com/39679971/159374759-3132ee5c-045e-4f1a-8df3-417b0a98849b.png">
"

**Comment by geromegrignon** [comment]
Hi @kllpff, thanks for opening this issue.
I fixed it.
