### ISSUE TITLE
[Bug]: Timed out fetching a new connection from the connection pool

### ISSUE THREAD

**Issue by 1deviljohn1** [gothinkster/realworld#930]
### Relevant scope

API response issue

### Description

Often API is unavailable

"Timed out fetching a new connection from the connection pool. More info: http://pris.ly/d/connection-pool (Current connection pool timeout: 10, connection limit: 9)"

![1](https://user-images.githubusercontent.com/17460230/164507326-29eff2e7-bbac-4a4d-8575-2cdb0fd835eb.png)

**Comment by geromegrignon** [comment]
Hello,
It might be due to issue with Heroku at that time.

I added Sentry to the API to retrieve info.
