### ISSUE TITLE
[Bug]: `DELETE`  article api returns status code 204 

### ISSUE THREAD

**Issue by xuchaobei** [gothinkster/realworld#940]
### Relevant scope

Backend specs

### Description

`DELETE`  article api returns status code 204 as following:

![image](https://user-images.githubusercontent.com/5110783/168478339-67a5de9c-d4db-4710-ba53-fb192dae1d0f.png)

According to the [API specs](https://github.com/gothinkster/realworld/blob/main/api/openapi.yml#L426), it should return 200 with the `{}` content.

**Comment by geromegrignon** [comment]
Hi @xuchaobei, thanks for reporting it.
It's fixed now!
