### ISSUE TITLE
[Bug]: Update current user response issue

### ISSUE THREAD

**Issue by sssoldy** [gothinkster/realworld#949]
### Relevant scope

Backend specs

### Description

Hi there, thank you a ton for this amazing project.

Seems that there is an issue at [update current user put reqsuest](https://api.realworld.io/api-docs/#/User%20and%20Authentication/UpdateCurrentUser). 

The response always contain the "image" field with the "bio" field value.
![image](https://user-images.githubusercontent.com/25584118/173011351-7e42a60f-e6ca-4192-a91b-361293952bab.png)
![image](https://user-images.githubusercontent.com/25584118/173011427-23dd1ac4-e209-4f02-89da-0dbf24eccaa1.png)

So right now we have 2 options how profile looks like: 
1) bio and the bio text in the image href (technically without image just placeholder).
![image](https://user-images.githubusercontent.com/25584118/173011062-015c2fc7-5a3d-4733-a9d7-cac9dae6018b.png)

2) an image at my profile page and at the navigation. The image url in the bio. 
![image](https://user-images.githubusercontent.com/25584118/173011142-3e3694e6-d1b6-4166-a292-2688b79127e5.png)

Could you check that out please?

Thank you and have a good day.

**Comment by geromegrignon** [comment]
Hi @sssoldy, sorry for being late to the party. It's fixed now (was fixed a long time ago on the codebase side but not deployed as expected on Heroku).
