### ISSUE TITLE
[Swagger] UpdateUser DTO should be ‘password’ instead of ‘token’ field

### ISSUE THREAD

**Issue by mutoe** [gothinkster/realworld#950]
In fact, only the password field works. Although no error is reported when the token is passed in, the user's password will not be modified.

https://github.com/gothinkster/realworld/blob/3e581cb2de90fe68f25fd3bfc428af27e528336f/api/openapi.yml#L697

**Comment by geromegrignon** [comment]
Hi @mutoe thanks so much for noticing it.
It's now fixed!
