### ISSUE TITLE
[Bug]: Updating the image replaces the image with the bio

### ISSUE THREAD

**Issue by mikesol** [gothinkster/realworld#971]
### Relevant scope

Backend specs

### Description

In the examples below, I'm sending a `PUT` request to the server with an update of `image` in the settings and the response I get for the image is the `bio`. I'm pretty sure this is a bug (although I could also be misunderstanding the spec). Thanks in advance for your help!

<img width="1087" alt="Screen Shot 2022-08-12 at 8 24 44 PM" src="https://user-images.githubusercontent.com/525350/184411697-fbb2f42d-fe78-4c01-a1ed-0e32f11fa988.png">
<img width="1093" alt="Screen Shot 2022-08-12 at 8 24 23 PM" src="https://user-images.githubusercontent.com/525350/184411703-407ca265-3335-4b03-8620-7fe2a3e5aeeb.png">

**Comment by geromegrignon** [comment]
Hi @mikesol sorry for the delay, it's now fixed.
