### ISSUE TITLE
🗄🔧 Go + Gorilla mux

### ISSUE THREAD

**Issue by chilledoj** [gothinkster/realworld#99]
# Current Status

- ### Codebase in progress:<br /> [chilledoj/realworld-starter-kit](https://github.com/chilledoj/realworld-starter-kit)
- ### Interested in helping out? Say hello! 🎉 

### Todo:

- [x] 🏁 Fork the [starter repo](https://github.com/gothinkster/realworld-starter-kit) & post the link in this issue
- [x] 🎨 Create logo for repo & update issue status (@ericsimons) 
- [ ] 🔨 Implement all of Conduit's functionality per the [spec & API](https://github.com/gothinkster/realworld/tree/master/spec)
- [ ] 👀 Move repo to main org & Peer review final codebase by admins/community (RFC)
- [ ] 🎉 Tag v1 release and officially list it on the README!

-----

Hi,

I have made a start on a fork utilising Go + [Gorilla mux](http://www.gorillatoolkit.org/pkg/mux)

[Chilled OJ / realworld-starter-kit](https://github.com/chilledoj/realworld-starter-kit)

**Comment by EricSimons** [comment]
@chilledoj awesome! Can't wait to see this 👍

**Comment by chilledoj** [comment]
Hi @EricSimons, the api is now fully functional.

**Comment by EricSimons** [comment]
@chilledoj awesome! I'm gonna test this out when I get home later today — have you tried running it against one of the supported frontends yet?

**Comment by chilledoj** [comment]
I've only been testing against the Postman collections so far. Would appreciate someone else's view - maybe I missed something (error responses?). I've only been using the postman collections so far, but also studied the NodeJS code for a few things as I'm very familiar with NodeJS.

Let me know how you get on. This is my first stab at being part of open source code, and i'm a bit new to the git workflow. 

I'll have a go at downloading a front end and testing it against it. I have a feeling I need to add CORS support - but luckily there is CORS available in the gorilla toolkit.

**Comment by EricSimons** [comment]
@chilledoj yeah there's some nuances to the frontend/backend API that we're going to add to the spec ASAP (response codes, CORS, etc) — if you've been following the node codebase you should be good though!

No sweat btw, almost all of us are first timers to OSS here :) I've never used Go before so it's taking a while to get set up, but lmk if you get one of our frontends up & running and don't run into any errors!

**Comment by brwr** [comment]
Any update on this? Sounds like we're ready to mark this as complete, pending testing. Would love to close this issue out if we're good to go.

**Comment by chilledoj** [comment]
I have tested the code against the postman collection and all tests pass - plus I have a few code tests written. I have struggled to test against a frontend. I'm not sure if anyone else has managed to download my code and test separately

**Comment by sluongng** [comment]
I appreciate your wiki very much. Im a newb at GO and reading about options and decision making really helped.

I have a question though: 

- Why shy away from usage of config files. May be config.json or config.yml and push out hardcoded configurations such as `UsernameLengthRequirement` ? What made `github.com/namsral/flag` a better choice than traditional config files?

**Comment by chilledoj** [comment]
@sluongng i chose that package as it is a complete replacement for the standard flag package, but instead of just parsing command line options it will also check environment variables, and config files. In general my experience has been that things like http address/port and db urn are usually defined  as environment variables in line with the idea of having a twelve factor app. 
In terms of the username length requirement, that was personal preference, but also i see it as something bespoke to the models package. If I wanted to parameterise that item I'd need a way to pass in the value (and handle defaults) from the main package, by perhaps storing on the custom DB struct.

**Comment by chilledoj** [comment]
@brwr I have had confirmation on the Golang Gitter channel from @guillaumemaka that he has successfully tested with the react front end. I too have managed to test against this now.

**Comment by sluongng** [comment]
@chilledoj could you provide some sort of example template for config file? I agree with your point about Environment Variables but problems come when you try to communicate with a large group of people. Its better to have some documented guideline rather than forcing a Java/C# dev to read and understand GO code.

For example, something like:
```YAML
//config.yml.example
host: 111.222.333.444
port: 8085
```

Would be very beneficial. Newcomers can just get the file from repo, edit and rename

**Comment by chilledoj** [comment]
@sluongng The `github.com/namsral/flag` package determines the config file format. But I've updated the repo to contain a config file and included some more items for handling http(s).

**Comment by Dkairu** [comment]
@chilledoj Any progress on this?

**Comment by chilledoj** [comment]
@dkairu It’s been a while since I looked at this repo. I’m pretty sure that it was working across the whole API spec.

**Comment by geromegrignon** [comment]
Hello, we moved the addition of new implementations to this website : https://codebase.show/projects/realworld
Please submit your implementation there.
